### ISSUE TITLE
Quick observation to QDataGrid2 missing warning

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1019]
I see that QCubed3 version will be ready soon :). 

Then I quickly point out that,if in database can not find desired data, you should see a warning: "No data available in table". But this warning is not here at QDataGrid2.

<img width="1270" alt="screen shot 2016-06-28 at 23 25 39" src="https://cloud.githubusercontent.com/assets/2853034/16431570/e2076e30-3d89-11e6-841b-e28117012590.png">
In this table is it available...
<img width="1261" alt="screen shot 2016-06-28 at 23 26 19" src="https://cloud.githubusercontent.com/assets/2853034/16431586/f1b099ec-3d89-11e6-8c13-6939bf23acf0.png">

**Comment by spekary** [comment]
Datatables uses javascript to detect this state. QDataGrid2 does not.

There is an option to hide the entire table if no data is present. We could potentially add this message as part of the paginator so it shows up in the caption of the table, but if the datagrid has no paginator, then it will not work. Perhaps we put it in the caption even if there is no paginator?

Just trying to figure out a way to do this without actually adding rows to the table, and without needing javascript.
