### ISSUE TITLE
How do you do translations?

### ISSUE THREAD

**Issue by matthiaz** [qcubed/qcubed#1030]
We developed our own translation tool to edit the .po files that we have in the i18n directory.

Recently it was brought to my attention that I shouldn't be editing the .po files to add new lines. In most translation tools it isn't even possible to add a new line (see: https://poedit.net/ ). I google quite a bit but apart from http://examples.qcu.be/assets/_core/php/examples/communication/i18n.php I couldn't find a lot of information on this subject.

I do find references to a .pot file that should act as a template, but qcubed mentions nothing about this anywhere (that I can find).

So here is my question: how do you guys manage your translation files?

**Comment by spekary** [comment]
I haven't used it yet.

**Comment by vaibhav-kaushal** [comment]
I had not looked in it either. Downloading that tool.

**Comment by nlomb** [comment]
I do this parsing the sources, creating a .csv - file for manually editing and then create .po file from this
using a number of scripts (grep, sed, awk, sort).
it's not perfect but working for me.

**Comment by olegabr** [comment]
I've maintained the translation incrementally line by line. Add some code with new translations - add it to po file by hand. I've had only one po file for russian language. It is not scalable for real localization to many languages.

**Comment by nlomb** [comment]
anyone intere4sted in my "solution" ?

**Comment by matthiaz** [comment]
I am curious on how you do the parsing from source files.


2016-07-15 11:21 GMT+02:00 Norbert Lomb <notifications@github.com>:

**Comment by nlomb** [comment]
@matthiaz 

I run this script "translate.sh" normally after creating / editing several QForms so that it gets all new / changed textitems to translate.

"translation.csv" contains all already translated texts,
The parser (line 13 in "translate.sh") looks for lines containing "QApplication::Translate" string and tries to separate and format the text to translate, writes to "translation.tmp" one by one per line.

After that the script appends all not yet existing strings / text from "translation.tmp" to "translation.csv" and calls "vi" for manual editing. (You can use any editor you like ...)

After manual editing the rest is simple, just create ".po" file from csv.

translate.sh
```bash
#!/bin/bash
# get Language Strings into csv - File to create de_DE.po files
# quick and dirty helper for QCubed Translation
# 2016 integrale EDV norbert Lomb

HOMEPATH=`pwd`

# change this to the path of your sources / application
DESTPATH="../../application"

# scan files recursive and extract words / strings to translate
# HINT: maybe this can be done easier
grep -r QApplication::Translate $DESTPATH | sed -e 's/[()]/\t/g' | sed -e 's/![[:alpha:].]//g' |\
	sort | uniq | awk -f translate.awk | sed -e "s/'/\"/g" | sort | uniq > translation.tmp

# add marker to translation.csv
echo "# ------------------------------------------------------------" >> translation.csv
echo "# here are the new strings" >> translation.csv
echo "# marker will be removed after editing" >> translation.csv
echo "# ------------------------------------------------------------" >> translation.csv

# add new found strings to translation.csv only if not yet there
count=0
IFS=$'\n'										# make newlines the only separator
for string in `cat translation.tmp`
do
	if grep -q $string translation.csv 2>/dev/null
	then
		# echo $string >> translation.csv
		echo "dublicate found" > /dev/null
	else
		echo "$string	\"\"" >> translation.csv
		((count++))
	fi
done

# output message
clear
echo "$count new strings added to translation.csv"
echo "now starting vi, press ENTER to continue"

# to debug uncomment 
# exit

read x
vi translation.csv

echo "now creating \"de_DE.po\" - file"
# create .po file
cat translation.csv | sort | uniq | sed '/^$/d;/^#/d' | awk -F"\t" '{print "msgid " $1 "\n" "msgstr " $2}' > de_DE.po
# sort translation.csv
cat translation.csv | sort | uniq | sed '/^$/d;/^#/d' > translation.tmp && mv translation.tmp translation.csv
# copy .po - file to destinatin
cp de_DE.po ../../resources/project/includes/i18n

echo "ready"
```
translate.awk
```awk
# quick and dirty helper for QCubed Translation
# 2016 integrale EDV norbert Lomb

BEGIN {
	FS = "\t"
}

{
	for ( i = 1; i <= NF; i++ ) {
		if (match($i,"QApplication::Translate")) {
			j = i+1
			# print gsub(/'/,\",$j)
			print $j
		}
	}
}
END {
	# nothing to do
}
```
Only works if "QApplication::Translate" is uniq in a line and the text is also in the same line.

I admit, the script looks a little ugly, quick and dirty; 
as I said: not perfect but working ...

**Comment by kukrik** [comment]
@nlomb solution is complicated and uncomfortable for me. Poedit free version is good enough and flexible. I use it a lot.Need a little configure. Before willing do empty.po to you :)! Rename empty.po to en_US.po. Put en_US.po your folder. I just have to show multiple screenshots. Then you can better understand it.

In Poedit program, you need to look up and pull en_US.po. Then comes the first screenshot, as you see here. Go to the yellow label and click on the button "Set Language". Then do as in the screenshots below.
<img width="1280" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/2853034/16878826/b42091ba-4ab6-11e6-9f3f-b59554c03290.png">

Data must write itself.
<img width="1280" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/2853034/16878830/b425c18a-4ab6-11e6-9d86-d7ebed42e929.png">
<img width="1280" alt="screen shot 3" src="https://cloud.githubusercontent.com/assets/2853034/16878827/b422e7d0-4ab6-11e6-8a2a-740467dd040f.png">
<img width="1280" alt="screen shot 4" src="https://cloud.githubusercontent.com/assets/2853034/16878829/b4255178-4ab6-11e6-9fc3-b52e1a09cf3b.png">

Configuration Location ,if an update is needed or edit:
<img width="1280" alt="screen shot proporties" src="https://cloud.githubusercontent.com/assets/2853034/16878828/b423d082-4ab6-11e6-958a-2e1137b86f31.png">

Poedit pulls only source text, if only you need to translate :)
<img width="1280" alt="screen shot translation" src="https://cloud.githubusercontent.com/assets/2853034/16878831/b438f264-4ab6-11e6-9b56-ab974791a454.png">


Here is empty.po file [emty.po.zip](https://github.com/qcubed/framework/files/366315/emty.po.zip)...

When the development is completed after, en_US.po then cloned into a few files and rename to de_DE.po or ru_RU.po or etc ...

Send these files to translate, they will just have to download the free version of Poedit and translate. Very easy to use!

It a try!

**Comment by nlomb** [comment]
@kukrik 
thanks a lot, will try this ...
did not know something like this exists

**Comment by kukrik** [comment]
@nlomb 
This is an example. Sources paths must be changed, there is a development in which folders :).
If you add meanwhile new words development to files, then you will need to open up and look and click in Poedit Catalog -> Update from Sourses etc... The po file be updated :)

**Comment by nlomb** [comment]
@kukrik 
thanks for the additional info about "Update from Sources", 
that is what i was lookong for ...
seems I will have to compile it myself, have no WIN or MAC in use

**Comment by kukrik** [comment]
If you think about the Unix/Linux platform, it is also a Poedit exists. I have not tried...
<img width="1280" alt="screen shot 2016-07-16 at 13 54 49" src="https://cloud.githubusercontent.com/assets/2853034/16894379/536713e2-4b5d-11e6-9575-e6a2abadaac2.png">

**Comment by nlomb** [comment]
@kukrik @matthiaz 
just checked, no need to compile yourself:
on ubuntu just do
```
sudo apt-get install poedit
```
other distributions see here:
http://rpmfind.net/linux/rpm2html/search.php?query=poedit

**Comment by kukrik** [comment]
👍 👍 👍

**Comment by nlomb** [comment]
sorry, version in ubuntu repo ist outdated, looking for newer release

**Comment by spekary** [comment]
v4 now has a standalone i18n library that can work outside of QCubed, and has a number of different ways it works. But basically, it can work with .po files for translations, and it has a variety of ways it can cache them to make translations fast.
