### ISSUE TITLE
Namespace Discussion

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#1063]
This is a discussion on what the namespaces and the directory structure should look like in the next version of QCubed.
# Background

PSR4 requires that namespaces and the folder structure be the same. The reason for this requirement is primarily so that composer's auto-generated autoloader knows where to look for a class. It just looks at its namespace and use the namespace to create a path. Secondary to this is supportability, in that it allows humans to know where the file lives as well, but that is not such a big deal with modern IDEs that can easily find a file.

QCubed started before all the PSRs, and before even composer, and has always used a class map that lives in one of the qcubed.inc.php files. The desire to make QCubed more modular, allowing pieces of qcubed to be used without requiring the whole framework, may ultimately drive us to doing what PSR4 wants us to do. Being a full-stack framework, QCubed does not lend itself well to modularity, but we can try. Note that PSR4 has some flexibility, in that you can specify a base directory, meaning that the first portion of the namespace path does not have to directly map to a file structure. We get to define to some extent what portion that is.
# Strategy

As much as possible, logically self-contained pieces that have few dependencies should be in their own namespace. Whatever dependencies do exist, the composer.json file can refer to those. We need to balance the desire for modularity with the desire to keep things as simple as possible.
# Major Functional Areas

Architecturally, major functional areas of QCubed include:
- **Base classes**, that everything depends on. These live in framework, with other things:
  `QBaseClass`, `QDateTime`, `QException`, `QType`
- **ORM**, which has the following sub-parts and dependencies
  - Code generator, depending on:
    - `QCodeGen`, `QCodeGenBase`, and `QDatabaseCodeGen`
    - Support classes, like `QSqlColumn`, `QSqlTable`, `QReference`, `QReverseReference`, etc. Note that these classes are shared with the ui generation code.
    - code generation templates 
  - Database adapters and the database adapter base class
  - `QQuery`, and all the classes that live inside of there. Also the QQuery database specific extensions that now live in _db_ext_.
  - QModel.trait.php, which has some code shared between the generated base classes
  - The generated model classes, including
    - generated model base classes
      - dependency on some support classes, like QCache and QCacheProvider, but unknown as to what value those provide currently because of recent performance improvements.
    - generated node base (QQN class)
    - generated autoloader class map (_class_paths.inc.php)
    - The generated model subclass stubs that are one-time generated and avaialble for user editing, these live in the project/includes/model directory currently
  - Settings in the configuration.inc.php file
  - Unit tests
  - DB Watchers, that watch for changes in the database and trigger automatic UI redraws
- **UI Framework**: The UI framework is such that it does not require code generation to be useable, but does benefit from it. Some of it provides support to code generation.
  - QControl base and subclasses
  - Actions and events
  - Enumeration classes
  - QApplication and prepend.inc.php
  - QForm
  - Javascript files, mainly qcubed.js, but also js files that are referred to by the QControls
  - styles.css file. QCubed has a very light depency on css. More could be done here.
  - translation files (i18n directory)
  - Support classes in framework directory, like QCss, QHtml, etc.
  - control registry for supporting code generation
  - Unit tests
- **UI code generator**
  - code generation templates
  - code generator settings file
  - model connector edit dialog and json file
  - generated model connector base and subclass stubs
    - These strongly depend on the generated ORM
  - generated form base and subclass stubs
  - generated panel base and subclass stubs
  - Unit tests
- **Standalone support classes in framework**
  - Unit tests?
- **App starter tools**
  - app starter and composer projects
  - installation wizard
  - start page
  - install directory, including default configuration.inc.php file, and default prepend file which contains the default QApplication class(should be broken out into separate file).

Edit (Vaibhav): Improved formatting.

**Comment by vaibhav-kaushal** [comment]
I think you have categorised them well. We can start with the code generator and the *generated* code to begin with. 

Also, I think we could use `QCubed` or `QC` as the base namespace for everything in QCubed. 

So the parts can be like 

`QCubed\ORM\UserGen` for UserGen class
`QCubed\Controls\Base\QTextBoxBase`
`QCubed\Controls\QTextBox`

and so on. 

We can start with the major chunks as you have described. 

  - **Base classes** can go into `QCubed\Framework`
  - **ORM** can go into `QCubed\ORM`. An alternate can be `QCubed\Model`
  - **UI Framework** can go into `QCubed\UI`. Alternatively `QCubed\View`, because they deal with presentation but it can be confusing because they are mostly the 'Controller' part of MVC.
  - **UI Code Generator** can go into `QCubed\ORMUI` or `QCubed\UI\Codegened` (I believe the name could be a little better)
  - **Tests** - `QCubed\Tests`
  - **App Starter tools** - `QCubed\Start`

We can then decide on branching.

**Comment by spekary** [comment]
The base of the namespace should be the same as the github name of the project, so "Qcubed" I think is going to be required.

**Comment by vaibhav-kaushal** [comment]
@spekary The project has already been renamed.

**Comment by spekary** [comment]
v4 has namespaces for all core files. Namespaces for generated files is not implemented however. If anyone really wants that, open another issue.
