### ISSUE TITLE
Roadmap for version 3.1 (Bigger goals)

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1082]
We are nearing version 3.0 release, and that calls for task separation for version 3.1 as well.

Let us list some of the issues we want to deal with in version 3.1
- [ ] #1063 : Namespacing
- [ ] Dealing with database specific types like JSON, tsvector, BLOB ( #1079 brought the issue forward and Issue #1083 is the place to discuss the problem )
- [x] Full-blown PHP7 and HHVM support

Feel free to add more to the list.

**Comment by vaibhav-kaushal** [comment]
I am running one of my projects on PHP7+QCubed since about 2 months now. It is not causing me any trouble. So I would check that one out.

**Comment by spekary** [comment]
Closing this. The issues mentioned are now individual requests and should be assigned to the correct version as anticipated.
