### ISSUE TITLE
Remove old plugins

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#1126]
Our repo space has too many old repos. We should move all the old ones into one archive because the source is still valuable for anyone who wants to prot them to composer-compatible plugins.

**Comment by kukrik** [comment]
Good idea! Let's put them in the archives, which may be needed, such as conversion, etc.

**Comment by vaibhav-kaushal** [comment]
I too support this.

**Comment by vaibhav-kaushal** [comment]
@spekary Can you list which ones should be merged? I would do it in spare time.

**Comment by spekary** [comment]
Anything that does not have plugin_ at the beginning of its name should be moved.

**Comment by spekary** [comment]
Done
