### ISSUE TITLE
Remove the old installer

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1134]
The old installer is not being called anywhere. I suggest we remove it altogether. That will help us keeping the code relatively clean.

**Comment by vmakre** [comment]
What about production environments with shared hosting without composer install?. We need one development folder with all install, codegen or other debugging like php scripts , we can remove them when we don't need anymore,  without breaking the code.

**Comment by spekary** [comment]
That isn't how developers should use composer, nor how qcubed is designed to be used. Composer is a tool for local development. Its not an install tool for a production environment. In the situation you describe, the developer should use composer to do local installs on a development machine, and then transfer the files from the development machine to the production machine using ftp or something similar. If the hosting server cannot do that, then the developer should find another host.

**Comment by spekary** [comment]
This is done in 4.0.
