### ISSUE TITLE
Change type in composer.json to "qcubed-qcubed"

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1135]
For some reason, **qcubed/app-starter** is not working according to what is needed and responds to `qcubed-qcubed` instead of `qcubed-framework`. 

We can rename the *type* in qcubed repo to make sure that in case the intended/documented behavior is restored, we will not need to work on the installer plugin again. This will bring us in line with packagist/composer better than before and prevent future problems with installation.

**Comment by spekary** [comment]
qcubed-framework is a perfectly fine type name. I have fixed the problem in the composer package and the installer should be working again. Let's be more careful about changing things in the installer.
