### ISSUE TITLE
QQN.class.php: No such file or directory and Class '*Connector' not found

### ISSUE THREAD

**Issue by ratno** [qcubed/qcubed#1143]
i'm trying to create new project with qcubed, after code generation, i go to form draft, when i click view list, qqn class not found, then i search manually, there is no qqn.class anywhere.

also when i click on create new link, i got class 'tablenameConnector' not found, then i add manually require model_conector to edit panel, the error become model not found, after i add manually require model, the error become qqn class not found again.

**Comment by spekary** [comment]
We will need your installation steps. The QQN.class.php file is created by the code generator and is placed in the project/generated/model_base directory. The code generator should have generated messages that will tell you what files it created and where. Take a look at those and any error messages during code generation.

**Comment by ratno** [comment]
i've try again using the sample database, and it is generate QQN.class.php in model_base, so i think my database is somewhat not comply to qcubed standard. i will check again to my database schema.
thanks @spekary.

**Comment by brynjaro** [comment]
@ratno I have similar problem after fresh composer install, generating against old database (I'm still using QCubed version 2.0.2 and codegen is working there).  I don't get any QQN.class.php file, but everything else seems to be OK. Did you find out what was wrong with your DB?

**Comment by axcsrs** [comment]
Hi, I am also having the issue where QQN.class.php is not being generated (and neither are _class_paths.inc.php nor _type_class_paths.inc.php).  I am using QCubed 3.1.0, which I installed using the Composer starter app install.  I am using a (heavily) modified version of the Oracle DB adapter, which I know is not supported, but I did not have this issue in v2.3.0.  I am not seeing any errors in the [codegen output](https://github.com/qcubed/qcubed/files/2094290/QCubed.Development.Framework.-.Code.Generator.pdf) that would indicate where the process is failing.  All of the generated and stub classes are being created properly, but it looks like the aggregate_db templates are not getting parsed for some reason.  Any ideas or thoughts on where I might look to debug?

**Comment by matthiaz** [comment]
You could add
*error_log("Running this function here");*
to different parts of the codegenerator, to see where it is skipping the QQN

Alternatively you could use xdebug to step through it.



2018-06-12 16:02 GMT+02:00 axcsrs <notifications@github.com>:

**Comment by spekary** [comment]
Looking at the codegen.php file, at the bottom, it looks like the aggregate files only get generated if there are no error strings. You have a number of errors in your code generation. So, either:

1) Get rid of your codegen errors by modifying your database, or 
2) Modify codegen.php to run the aggregate generator even if you have errors, though I am not sure if it will work or blow up at that point.

**Comment by axcsrs** [comment]
OK, getting rid of the errors solved the problem.  Thanks!
