### ISSUE TITLE
Redis as Caching Backend

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1144]
I have been using Memcached backend built into QCubed. However, I believe that there are going to users who will need more than that. I, myself have run into a situation where I need to use Redis as the caching backend. However, Redis support is not available in QCubed yet. What do you guys say about using Redis as a caching backend?

Also, we are not using the 'expire-time' parameter for our caches. Both Redis and Memcached allow you to set a timespan after which the cached object will expire. This is pretty useful but unavailable in QCubed. We need to modify the signatures of the `Set` methods in there.

**Comment by kukrik** [comment]
@vaibhav-kaushal, make surely a support for Redis! It would be a big deal!

Surely make a few test and  example for our.

**Comment by spekary** [comment]
It should be pretty easy for you to create a Reids version of QAbstractCacheProvider. Just follow the examples.
