### ISSUE TITLE
QAjaxaction problems

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1147]
If anyone noted that javascript does not work always so let's share some experience. I had a lot of troubles but i am not sure is there some incompatibilities with jquery or i am messing with different javascript versions. When i have problem for example with click event , i get whole page in back request and no JSON array. When i look in html there is generated javascript code and everything looks good . I am using Firefox as main browser for development and i know caching javascript is bad for debugging and development , but problem stays in other browsers also. My qcubed isn't latest maybe some major changes in code and something is broken?. I am using QAjaxaction and QServeraction combined in one form. Is somebody having these problems?

**Comment by spekary** [comment]
Your going to have to be more specific about what you are trying to do. A specific test case of failure would help, or an error code. Whenver I am having trouble with javascript code, its almost always something I am doing wrong. The handoffs between the javascript and ajax are complex though.

Combining Ajax and Server actions on the save form are not a problem, but having one action trigger both ajax and server actions might be a problem, at least, they might not execute in the order you want.

**Comment by vmakre** [comment]
I installed new stable version and  problem is solved. I need to start my project from ground up , we can close this issue , maybe modifying core things is going to make a lot of troubles.
