### ISSUE TITLE
Different thoughts and suggestions to @spekary

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1151]
@spekary , I do not know that either looked into https://github.com/qcubed/plugin_bootstrap/issues/40?

My question is that are talking about custom themes using bootstrap options. Do you Bootstrap_plugin supports other possible solutions such as radio and checkbox different appearance?

Secondly - and I do not want to change good the structure Bootstrap_plugin. But to provide additional features, etc?

You are the author of this plugin and that is why I wanted to hear your thoughts and suggestions!

**Comment by spekary** [comment]
To do custom bootstrap themes and/or use bootstrap like controls, you would start with the QBootstrap plugin, and then create other plugins that require that plugin. Composer let's you specify those kinds of dependencies, so once its set up, it would be easy to install. That also lets you separate the core Bootstrap functionality from the add-on bootstrap items. There are so many bootstrap add-ons on the Internet that its not practical to put them all in the QBootstrap plugin. But building them as separate QCubed plugins should work just fine.

**Comment by kukrik** [comment]
Clear! I try to follow your recommendation. Thanks, that gave a good signpost :)!
