### ISSUE TITLE
exception on example page for checkbox column

### ISSUE THREAD

**Issue by haegensnico** [qcubed/qcubed#1152]
on following page, I get an exception when accessing it:
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/qcheckboxcolumn.php](url)
Access level to ExampleCheckColumn2::SetItemCheckedState() must be public (as in class QDataGrid_CheckBoxColumn)
 /var/www/html/examples/vendor/qcubed/framework/assets/php/examples/datagrid/qcheckboxcolumn.php Line: 12
Line 12:    	class ExampleCheckColumn2 extends QDataGrid_CheckBoxColumn {

**Comment by spekary** [comment]
Fixed
