### ISSUE TITLE
Proposal of Documentation with main Repo

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#1154]
QCubed's documentation from a new developer's perspective is not good, or complete. Lot of effort is required for documentation - for explaining features and telling new developers how things are done in this framework. To tell them nifty tricks, shortcuts, methodologies and at time, flaws of QCubed. 

## Experience so far
I have personally tried to do what I can with Documenting. When I came in, there were about a dozen pages of documentation in the old **trac wiki**. Since then we have moved to GitHub and some documentation is there on the wiki, which is good but we are still far behind. I have tried multiple things. I will explain a little about what I have tried and why I am proposing what I am proposing. 

I have tried creating a blog for QCubed and then I thought that I needed something more suitable for documenting. So I started with another blog. More organized but still a blog. Then I tried writing it in Wiki format and launched the site http://qcubed.in (This one is DokuWiki which is easy to setup, maintain and compose on). However, when version 3.0 was released and there were changes required, I had to take a decision and move pages from one URL to another, introduce versioning (new features added, deprecated etc.) and so on. This was not easy because:

## Challenges in Documentation
- Hosting: I had to host that site. Maintaining yet another site is a pain. More so when it is different from others, is not bringing in any profit (hard truth), does not look all that great and needs some major work. It is demotivational at times. It is the same reason why maintaining the forum on qcu.be became a trouble, trac became a trouble and our examples site was sitting there broken for almost a week before @olegabr and @spekary fixed it.
- Documenting a framework, especially an open source one is a difficult thing. People tend to disagree on most things - domain name to use, CSS style, language styles, indentation etc. Versions add pressure on someone who documents the framework/library - he has to understand everything that was changed between versions and write about them - migrations, deprecations, features, bugs, tips, recommendations etc. Someone doing this can probably make mistakes - something not good for a documentation project.
- Documentation and Coding happen at different times. Normally people write and test the code first. Then they go and update the documentation (code level or tutorials/references). Many a number of times, after completing the feature/fixing the bug, updating documentation some place else feels like a burden. 

## The Proposal
**We document in-repo**: We will create a `docs` folder in the codebase and write our documentation in `.md` files in that directory in a particular layout (undecided till now). You might think - why not **wiki** if it is to be markdown files? I have explained it below (in form of disadvantages and advantages).

### Disadvantages
- Breaking the norm: this is not how most frameworks do the documentation.
- Can be a little messy: it is not easy to create the perfect folder structure for documentation. 

### Advantages
- **Markdown**: Markdown is easy and popular. GitHub will display it well. Writing tools are available. Unlike Blogs and Wikis (like DocuWiki/MediaWiki), we do not have to learn another markup language or deal with HTML problems.
- **Versioning**: One of the biggest problems with documentation I see is versioning. With this approach, at each point of time, the code and it's documentation will remain in sync. We can have all the stuff we cannot write as Doc-Comments can be with the codebase. Anyone can refer to it without having to launch a web-browser. His/Her IDE would be enough! This takes me to the next point.
- **Good to start with**: Since we do not have a full-on documentation site where we can setup a system with versioned information, layouts and style, this would help us get started well enough. 
- **Better than Wiki**: GitHub's Wiki, in its current format is bad, especially from the versioning perspective. We would have to change the wiki separately from the code and this is where we are failing right now!
- **Conversion to site would be easy**: There are too many projects right now who have another repo for documentation. One can help edit them on GitHub. The sites are rebuilt once PRs are accepted (based on GitHub pages). I am okay with this one too. Documentation for many Facebook, Microsoft and Amazon products are in this style. We can use offline site generation if we need. We can also use the format to create online book/documentation using gitbook or any other site offering similar functionality.
- **If all else fails**: The documentation will be available on GitHub for anyone to refer.
- **No hosting required**: Even if we cannot come to a conclusion about when, who and how will a documentation site will be set up, the documentation can progress.
- **Easily maintained**: We write docblocks because referring to functionality and purpose of methods becomes easy. Similarly, writing the code, its tests and its documentation is easy in one go! I do not have to login to another system and then write the documentation. Just writing in the repo makes everything easy.

## Thoughts?

Are you guys okay with a **docs** folder in the codebase?

**Comment by spekary** [comment]
Wiki has the advantage of being able to easily create links between documents. How would that work in this method?

I would love to know how Datatables does their documentation. That is a great site to navigate.

**Comment by vaibhav-kaushal** [comment]
For links, syntax remains the same. 

For linking other documents, you do relative links:

- [here.md](./here.md) refers to "here.md" in current directory. See the link it points to: [here.md](./here.md)
- [below.md](./subfolder/below.md) refers to "below.md" in a sub-directory. See the link it points to: [below.md](./subfolder/below.md)
- [above.md](../above.md) refers to "above.md" in the parent directory. See the link it points to: [above.md](../above.md)

That's how we do linking. GitBook allows conversion based on these. They also work on GitHub's main site as well as when publishing via Pages (when you are publishing without style and liquid templates).

**Comment by vaibhav-kaushal** [comment]
Also I cannot confirm how Datatables gets the job done for their website. But you can have a look at these:

1. https://github.com/microsoft/azure-docs
2. https://facebook.github.io/react-native/docs/getting-started.html
3. https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md
4. https://github.com/nikic/PHP-Parser

**Comment by matthiaz** [comment]
I'd like to add my 2 cents. I have been using a database migration tool called Phinx together with qcubed and I love the way they did their documentation. 
I looked around and aparently they use ReadTheDocs https://readthedocs.org/

Read the docs has a paid version to support development. But is available for free and is opensource. 

http://docs.readthedocs.io/en/latest/open-source-philosophy.html

**Comment by StevenWarren** [comment]
Haven't been around for a while as I do not write as much PHP as I use to, but I have been keeping up with the progress you guys have been making. Documentation has always been an issue with QCubed, even in the QCodo days. I have worked with a few projects that used Read The Docs. It is easy to use, hosted and can be kept up to date in a git repo. An update/edit to the docs is a simple merge request to the documentation repo which is then kept in synch.

**Comment by vaibhav-kaushal** [comment]
@StevenWarren and @matthiaz Thanks. I think this is a wonderful idea. It solves multiple problems regarding documentation.

**Comment by vaibhav-kaushal** [comment]
In my defence: https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Comment by spekary** [comment]
I agree with @vaibhav-kaushal. We should start with a github solution, and then move to something more involved if we ever get the time or inclination.

There is a lot to do. Just the basic API doc, pulling that out of the sources, will be difficult to work through. But we also need user level and developer level documentation (which I realize is a lot on me since I have rewritten a good chunk). I will see what I can do, but would like to structure it similar to our proposed namespace structure.

**Comment by vaibhav-kaushal** [comment]
@spekary Alright then. I have an idea about automating a few things on documentation side. Let me work on that and I will push it here (in a new repo, probably). As far as namespacing is concerned, we can have a discussion on that. For now, we can use classpaths to solve the path issues.

**Comment by spekary** [comment]
Great. Perhaps discuss a little bit what you are planning. I know you worked on the PHPdocumentor stuff. I think we can make that thing work given some custom template work, but its going to be some work.

I am going to start with an index.md document and some top level stuff. If you are doing automation, then you might think about just putting your stuff in a folder inside the docs folder and doing it directly in the main repo for now.

**Comment by vaibhav-kaushal** [comment]
I was thinking to build a small tool which does the following:

----

1. It will read the entire directory structure and create the document tree. 
2. It will filter out the `.md` or `.markdown` files and keep them separately. 
3. In each folder it would create a `toc.md` file automatically. These TOC files will be responsible only for the folder in which they are put.
4. It will create a master TOC in the Top Level Directory which will link to the TOCs in child directories. 
5. *Optionally*, it would put a "Back to Index" line at the bottom if it is not present. 
6. *Another optional feature* is to make sure that the **order** of documents could be customized by renaming the files. This comes from the thought that if we read randomly, or even in alphabetically, **installation** comes before **requirements** but it should be the other way round. 

----

This can be put in a pre-commit hook if needed so that with each commit, changing, adding, removing the Documenation files would rebuild the index automatically. This can be benefitial for other projects as well. While one can use the `docs` folder for a complete Jekyll based site, not everyone is going to need/prefer that (I do not like to put a complete site inside myt `docs` folder).

**Comment by spekary** [comment]
Yeah, I think this should all be done in a subfolder. I will not be doing any jekyll work initially, but a new user's first impression to the docs should be a good one. API docs are important, but should be off of the main page.

**Comment by vaibhav-kaushal** [comment]
Jekyll should probably be another repo altogether. Later we can have a server (probably the one where qcu.be resides) where we can setup GitHub hooks for automated update to GitHub pages and API documentation of all sorts. Till then, a simple approach can work. We will improve this along the way.

API Docs IMO must always reside separate from main repo so that the main repo stays clean. Generated HTML files from any API dcumentation builder (ApiGen/PhpDocumentor) look like a huge mess.

**Comment by vaibhav-kaushal** [comment]
This is what I have built till now:  https://github.com/vaibhav-kaushal/tic-toc/ Not a great thing. But this is what I have been able to build till now.

**Comment by spekary** [comment]
Page not found.

Incidentally, I am thinking about having 2 levels of documentation:
1) General user and overview documentation, and overall architectural information, located in the docs folder and having Github auto-copy that to the web page.
2) Using the Wiki pages as a place for API documentation, and structuring it so that users can easily contribute. 

Github's wiki pages are a blessing and a curse. They can be configured so that anyone can edit them, which is great for encouraging user contributions. However, they cannot easily be structured. I need to experiment with that a bit. Supposedly you can create a folder structure to make customer headers, footers and sidebars, but the files in the whole system need to have unique names, and you have to use traditional Markdown references, not Wiki references to the sub-folders. 

I saw that someone on the web had created a PHPDocumentor -> Markdown filter. If we can use that to generate the initial API doc, and then copy it to the top of a file, saving the bottom part for user comments, sort of like the PHP documentation, that I think would be helpful.

**Comment by vaibhav-kaushal** [comment]
Sorry for the 404. You can try again. The repo was private while I was working on it and since Github has updated their styles, the color for the 'Private' besides the repo name is gone, making it harder to notice. 

About the documentation, I agree. Even a quick _tutorial_ sometimes falls in _documentation_. I think your approach on this one is right. We should have some API documentation on Wiki. Because after all it is more accessible than the docs folder and people can contribute more easily. In case we need to move the contents later on to the docs folder, it wouldn't be difficult at all. 

As far as this tool is concerned, I think we can discuss it separately. The decision to use the `/docs` folder is almost done. So we should close this issue and move on with it.

**Comment by spekary** [comment]
We will leave it here as a v3.1 marker to do the docs.

**Comment by spekary** [comment]
Moving this to 4.0. SInce 4.0 is a major architecture change, and is now in alpha, there is no sense in documenting the old version.
