### ISSUE TITLE
override QModelTrait

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/qcubed#1157]
I'm trying to override QModelTrait but the one from the vendor folder is still getting picked up.

I've copied the file to my app_includes folder and added the line
        QApplicationBase::$PreloadedClassFile['qmodeltrait'] = __INCLUDES__ . '/app_includes/models/core/QModelTrait.trait.php';

to my app_includes.inc.php file. 

When I output QApplicationBase::$PreloadedClassFile['qmodeltrait'] to the screen, it is showing my file as the value, but when stepping through my code, it is picking up the one from the vendor folder. 

Any ideas on why this is happening or how I can get it to use my version?

**Comment by spekary** [comment]
I don't know. Looking at the code, that should work.

Set it right before 		

```QApplication::Initialize();```

In the prepend.inc file. You must set the value after the qcubed.inc.php file is included.

The other alternative is to include the file in your model class.

**Comment by kpirbhai** [comment]
That worked. Thank you!
