### ISSUE TITLE
 Who offers better or work solutions for QCubed 3.0?

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1159]
I'll have shortly a new project to work. I think a long time, what solutions could be... I've never used a system of panels. I have made very little use the panel as here http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/multiple_qform/intro.php. 

It is not very comfortable, because one the panel ($pnlLeft) is top and a second panel ($pnlRight) be down. This is not convenient with tablet PC or mobile browser, the browser to scroll up or down, etc.

My vision is this. I have a little bit difficult to explain in English, because the drawing here. Then you can better understand what I want to do.
![vision](https://cloud.githubusercontent.com/assets/2853034/22409436/701333ce-e692-11e6-8d73-da911f949ef2.png)
I have also read this: https://github.com/qcubed/qcubed/wiki/Front-Controller-Pattern. But I am not sure if this solution is suitable?

Something like jQuery solution found, it would be suitable. But how do for QCubed 3.0? 
```
<div id="page">
    <div id="maincontent">
        <div id="firstcontent">first content</div>
        <div id="secondcontent">second content</div>
        <div id="thirdcontent">third content</div>
    </div>
    <div id="menuleftcontent">
        <ul id="menu">
            <li><a href="#firstcontent" class="active">first</a></li>
            <li><a href="#secondcontent">second</a></li>
            <li><a href="#thirdcontent">third</a></li>
        </ul>
    </div>
    <div id="clearingdiv"></div>
</div>
```
```
$(function () {
    $("#maincontent > div:gt(0)").hide();
    $("#menu a").on("click", function () {
        var href = $(this).attr("href");
        $('#menu a').removeClass('active');
        $(this).addClass('active');
        $("#maincontent > " + href).show();
        $("#maincontent > :not(" + href + ")").hide();
    });
});
```
This is only a for thinking :). Here, the question as to who to use and provides the best solutions or ideas? That is why there is no sense new to reinvent the wheel :)!

Thank you in advance! I stay to hear.

**Comment by spekary** [comment]
You seem to be combining different ideas into one screen, which could be confusing. The menu and tab function in your html and js is the same as what is provided in Bootstrap, so you should see that for controlling and getting the state of the selections. 

You diagram shows swapping list and edit view, which I don't recommend. Instead, have a list next to an edit view, and selecting the list shows the edit view.

**Comment by vaibhav-kaushal** [comment]
@kukrik I use Front Controller pattern to solve the same problem on one of my sites and it serves well. It looks problematic at first but is very good a solution and easier to implement. However there is one problem: If you use QPanels to represent the right side body, then clicking them will not update the URL (QAjaxAction or QServerAction does not update URL). Apart from that, this method works really well.

If you take the JS route, then there is a small problem: you will have to pre-render all the 4 panels while only 1 will be visible. QCubed's rendering is perfect but *slow*. It slows down the page. I would recommend that you stick with Front-Controller pattern.

**Comment by kukrik** [comment]
Thank you for the explanation, @spekary and @vaibhav-kaushal! Everyone gives their vision.

I have been one and the same solution, that's why I wanted to interesting solutions with a new project.

It would be interesting to hear from other solutions.

**Comment by spekary** [comment]
You can use Bootstrap to put panels side-by-side, or flexbox styling.

v3 of QCubed, I haven't noticed to be particularly slow. Its mostly dependendent on the server.

**Comment by kukrik** [comment]
I do not like anyway three panels side-by-side, one panel of the menu, the second panel of the list view and third panel of the edit view.

Maybe I drew a little bit wrong.

My thought was that the Draft of the working principle is exactly the same, beginning of the list view are displayed in a panel (for example, $this->pnlListView->Visible = true; $this->pnlEditView->Visible = false). A table one row by clicking displayed the edit view in the panel ($this->pnlListView->Visible = false; $this->pnlEditView->Visible = true) and so on. The important thing is to stay to one of the dynamic window.

Is it possible?

**Comment by spekary** [comment]
If I understand this correctly, you want to swap the list view for the edit view, and then go back to the list view. Yes, you can use ->Visible, or use ->Display to do that. Experiment with both.

But perhaps look at the new Dialogs to do what you want. That is what I do. I have a list view, and clicking an item in the list view pops up a dialog for editing the item. v3 will codgen these dialogs for you making it very easy to do.
