### ISSUE TITLE
Blank page afther configuration database qcubed 

### ISSUE THREAD

**Issue by MaribellaAguilar** [qcubed/qcubed#1208]
Hello!!

Help me, Blank page for afther configuration database qcubed 3.0 on linux
what am I doing wrong???

**Comment by kukrik** [comment]
I have also. Just to be hand-written.

**Comment by spekary** [comment]
Yeah, this is always difficult. Its hard for QCubed to catch errors in the boot up stage. 

A couple of things to do:
1) Check your log files. 
2) Setup xdebug and step through the code from prepend.inc..php file.
3) Insert "Print "blah"; exit;" in the prepend.inc.php file and see how far you get before it errors, then narrow it down.
4) Set a breakpoint in the QCubedShutdown function in qcubed/includes/error.inc.php

**Comment by MaribellaAguilar** [comment]
And this error:


FATAL ERROR: No databases are listed in the configuration file.

**Comment by kpirbhai** [comment]
Are you using composer and the app_starter to setup your project? 

Also, I've had problems with the setup page in the past. If you go into project/includes/configuration/configuration.inc.php you can setup your database definitions. There is a commented out one in there already you can use to see what you need to do.

**Comment by vaibhav-kaushal** [comment]
It happened a couple of times with me. For me the reason was that I did not change the defaults. Another time, I did not have the extension installed. There are a few possibilities why this might be happening. 

@MaribellaAguilar Can you reveal a little more information?

**Comment by spekary** [comment]
Lets try to get as many of these things to produce real error messages as possible.
