### ISSUE TITLE
Make QApplication a real object

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#1214]
QApplication unnecesarily is an abstract object and refers to a bunch of static variables. 

We should make it a real object that is created before the form object, like so:

```
$app = new QApplication();
MyForm::Run($app, 'MyFormId', 'mytemplate.tpl.php');
```

prepend.inc.php should be modified to move as much of that code into the QApplication object. However, prepend.inc.php might need to create a  global application object if its in command-line mode.

This will make it much more clear what is happening with the object, how to override functionality, and how to mock parts of it.

One problem though, if this becomes a member of the QForm, it will need to be removed from the form object before serialization so it is not included in the formstate. We must be clear that the application object must get recreated on every program entry.

**Comment by kpirbhai** [comment]
How would this affect using the framework for pieces of an application which are not at all a QForm or any other QControl based php page? For example...I have a bunch of code which I use for api or utility type functionality that "do stuff" involving various models but have no user interaction through a browser interface.

**Comment by spekary** [comment]
Good question. We would have to think through that, but basically it means creating either a global application object, or a local application object and passing that around.

In 4.0, we are going to try to make the ORM a standalone repository. The only dependency I see between the models and the application is the database adapter. @lackovic10, perhaps you can make a recommendation on how to get the database adapter that corresponds to a particular model? Given our current architecture, I think the application object would need to be a global variable, and it becomes the one essential dependency throughout the system. Either that, or we would need to pass the application object in to every database call. Thoughts?

**Comment by lackovic10** [comment]
I've added my thoughts [here](https://github.com/qcubed/qcubed/pull/1138#issuecomment-298202993)

**Comment by spekary** [comment]
Application is now an object in v4, and you can get a singular instance of it.
