### ISSUE TITLE
Fix Binary Support

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#1217]
I don't think we should have Blob types, but rather Binary types. PHP does not care if something is a Blob, VarChar, Char or Text, it treats them the same. However, there are situations where they should be treated differently by QCubed. Right now, when we see a Blob or Text type in the database, we treat them the same way, both as a Blob. But really, we don't need to know how SQL is internally storing objects, but rather we need to know whether the object is Binary data or string-based data. There are also Binary data types that we handle as strings. 

String data we can sort on and create text fields for in the code generator. If we think something is Binary data, we should not do any UI creation, but we DO want to make sure we Base64 the data before sending it to json.

**Comment by vmakre** [comment]
@spekary  i think will be good solution to make one db creator script together with codegen.
We can design database from scratch with one file , maybe xml like with predefined types of columns 
like: 
<table name="users">
   <column name="id" type="primary" autoincrement="1">
   <column name="user name" type="VARCHAR" size="15">
 </table>
 And one dynamic query builder for different database engines , mysql , postgres, sqlite, mongo .
Also we can do a codegen from this file much better and understandable , than codegen from existing database.
We need to define types of columns we will use for compatibility between different database engines. I saw somewhere in qcubed  SOAP codegen builder from WSDL structure , good idea to think about.

**Comment by spekary** [comment]
Moving to 5.0 because its database related.

**Comment by matthiaz** [comment]
is fixed in 3.2 https://github.com/qcubed/qcubed/pull/1218
