### ISSUE TITLE
session timeout and ajax calls

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1222]
Can we implement form submit timeout like session timeout?
My idea is with small ajax requests on certain time intervals to make session prolonged 
 without modifying php.ini session timeout variables (not always possible).
[http://stackoverflow.com/questions/12597176/how-to-keep-session-alive-without-reloading-page](http://stackoverflow.com/questions/12597176/how-to-keep-session-alive-without-reloading-page)
To be like method of QForms  , $this->formtimeout(15);  // define 15 minutes for this form

**Comment by spekary** [comment]
Yeah, session timeouts are a pain. We should look at this.

**Comment by vmakre** [comment]
all my projects are on shared hostings , and problems are getting worse when customer needs to fill a lot of fields in a long form. So good solution  for me is i can extend timeout on some forms with form timeout method. This method should enable javascript timer (can be i one minute) and repeat it till another counter reach timeout in minutes ( counts to 15 for 15 minutes and stops binding). Must be in ajax to have form unchanged. And timer is standalone and does not depend on other actions.

**Comment by spekary** [comment]
Will a QJsTimer work?

**Comment by vmakre** [comment]
Yes looks promising . But timer cannot stop without user intervention. I will check it again.

**Comment by spekary** [comment]
Does it really matter? A timer that triggers every 15 minutes is not a big deal. Also, when it triggers, all entered data will be sent to server so that on refresh, all the data is restored. If the session times out, v3.0 essentially just does a page refresh. So a timer is a good thing.

**Comment by vmakre** [comment]
I think it is not possible to put 15 minute timer on php.ini session smaller than that . The point is to extend session timeout in small intervals , that is my understanding.

**Comment by spekary** [comment]
15 minute timer for QJsTimer.
