### ISSUE TITLE
Add OnClick and other common handlers

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#1224]
From #997 . Currently, to add an event, you must use ->AddAction(new QClickEvent ...

We should make a shortcut to do common event handlers.

For example, do:

```
$this->OnClick($handler, $options);
$this->OnKeyDown($handler, $options);
```
where:
- $handler = Either an action object, or just a string for javascript or a Callable for ajax action.
- $options - key/value array for things like timing delays, synchronous processing, etc.

**Comment by matthiaz** [comment]
Added a pull request:
https://github.com/qcubed/qcubed/pull/1297
