### ISSUE TITLE
A Reflected XSS vulnerability in step_2.php

### ISSUE THREAD

**Issue by jgj212** [qcubed/qcubed#1230]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in " installation_path" HTTP parameter that will be passed to " qcubed-master/assets/php/_devtools/installer/step_2.php". The infected source code is line 33, there is no protection on $_GET[' installation_path'], if it contains evil js code, line 60 will trigger untrusted code to be executed on the browser side.
![1](https://cloud.githubusercontent.com/assets/1484292/24279839/4e379f3c-1087-11e7-82e7-4025a7fd33a0.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/ qcubed-master/assets/php/_devtools/installer/step_2.php?installation_path="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![3](https://cloud.githubusercontent.com/assets/1484292/24280747/07ce4530-108e-11e7-8c0a-abb425573de9.png)

Discoverer: ADLab of Venustech

**Comment by kukrik** [comment]
I think that this should not be a problem. It is intended only once for the installation. These codes are not intended for the production of. 

Obviously, it is wiser to remove these files after installation, etc ...

**Comment by jgj212** [comment]
@kukrik  yes,  someone maybe forget to remove this files, and that will be a problem

**Comment by kukrik** [comment]
Let's see what speaks @spekary?

**Comment by kukrik** [comment]
@spekary, thinking a little bit, it could be done next. After installation, could come up with as to say that the Start page displays a warning that recommends installilehed removed. What do you think of this?

**Comment by spekary** [comment]
This is certainly not our biggest vulnerability. Its part of the bigger issue of creating a robust process for deployment. Deployment should obviously leave out the _devtools directories. I think making sure its part of the ReadMe in that directory for now would be best.

**Comment by kukrik** [comment]
Good idea!

**Comment by vaibhav-kaushal** [comment]
This was part of the old installer. Since we have moved to composer, it does not make much sense anyway! I think this should be removed, actually.

**Comment by kukrik** [comment]
I understand. This would be a good start for beginners, for configuring.

@vaibhav-kaushal What do you think of this?

**Comment by matthiaz** [comment]
Installation has some PR requests that improve this.
