### ISSUE TITLE
new codegen possibilities

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1231]
My idea is if we have all those files except db model , as panels , objects and forms to be generated in one file or two with template. What do you think about? Sometime our life become simpler and we need one file form why not?
We have all code but output it to one file with good understandable code  structure. I am talking about visible components and their working logic , not about modelconnectors and db related methods.
Or we can extend codegen with parameter to make all things in  parallel  to one folder with statically generated files only. This can help us to understand qcubed better, and to work on codegen optimization in the future.

**Comment by spekary** [comment]
The templates are easily customized. You can always post whatever your ideas are on the templates, and anyone can try it out by just pointing to your templates. You can do templates as a plugin, or just put them in your own repository.

The reason the templates are a bunch of small files is it makes it easier for the template user to override particular parts of the codegen process without having to override the whole thing.

The templates also refer to control generators now too, so you need to take that into consideration.

**Comment by spekary** [comment]
Rereading, I think your are proposing to have the templates put everything into one form file. That is how QCodo 1.0 worked. I think people found it easy to understand, but hard to expand an application after that. 

After building a form, you will want to make changes to it. But if you modify the form, you cannot codegen again. It will overwrite the form.

The other issue I found is while expanding an application, I didn't want an edit screen in a different form, I wanted it in a dialog. There were also times where one form needed to edit multiple tables. To do these things efficiently meant the edit objects needed to go in a panel, not directly in a form.

The list view had the same problem. Sometimes I want to see the same table in different ways on different forms. I need multiple lists looking at the same table. If it is all in one form, its not possible to combine different list views.

But that is just my experience. Perhaps you can find a way around these problems while putting everything in one form.

In either case, it really is no problem now to have many different template approaches. I think we should make a Wiki page that allows people to post their templates for others to use.

**Comment by vmakre** [comment]
I think it is good as an option , we always have projects with different opportunities and will be good to have different options. If we tend to divide db orm from application code then we must have codegen form with all visual objects and child objects in one.
In fixed form i will expect panels and objects to be shown together , then i can modify everything in one place and extend or modify them there. Then we can modify database (regen only model connector) with same form.
