### ISSUE TITLE
QHtmlTable paginator not rendered automatcally

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1252]
if i have : 
```
        $this->dtgconfig = new QHtmlTable($this);
        $objPaginator = new QPaginator($this->dtgconfig);
        $this->dtgconfig->Paginator = $objPaginator; 
```  
QHtmlTable object does not render paginator
i must put it manually in template:
```
<?php $this->RenderBegin(); ?>
    <p><?php $this->dtgconfig->Paginator->Render(); ?></p>
    <p><?php $this->dtgconfig->Render(); ?></p>
<?php $this->RenderEnd(); ?>
```
If i want all filters and paginaton controls i must put them manually to render , is this right or i am wrong?

**Comment by spekary** [comment]
If you want auto rendering of paginator, use a QDataGrid. QHtmlTable just renders rows and columns.

**Comment by kukrik** [comment]
Whether can not do QHtmlTable to a more capable?

**Comment by spekary** [comment]
No. We are trying to keep things modular. QDataGrid does pagination. Use that if you want pagination. There are other subclasses of QHtmlTable that do not want to use pagination, so why should they be forced to have it?

Also, if anyone wants to add filters, it should be a subclass of QDataGrid.

**Comment by kukrik** [comment]
Clear!

**Comment by vmakre** [comment]
QDataGrid is a subclass of QHtmlTable and paginator works , but autorender doesn't.
 Problem with QDatagrid is i don't have additional functionalities of QHtmlTable.
Also i can't get table header with column orders.
But i like paginatoin to put manually because it is better for templating. Maybe updating of tutorials can help a bit .

**Comment by vmakre** [comment]
Paginator doesn't work at all. I think problem is counting of results and catching requests. But i think it is possible to make it working.

**Comment by kukrik** [comment]
I would like to open the ticket and ask for more than that, how is the Bootstrap table?

How to use QDatagrid or QHtmlTable for Bootstrap?

**Comment by kukrik** [comment]
I'm sorry that the issue goes a little bit down, but still a very important issue is the use of tables.

The point is that we need a new life to go along. Very much used in tablet PCs and mobile devices, where people spend a lot of time.

I am speaking of the table with extension Responsive being. One example is here (it's DataTables): https://datatables.net/extensions/responsive/examples/styling/bootstrap.html.

But how to use it with QDatagrid or QHtmlTable?
