### ISSUE TITLE
Finishing V3.1, testing examples

### ISSUE THREAD

**Issue by matthiaz** [qcubed/qcubed#1253]
As @spekary mentioned in https://github.com/qcubed/qcubed/issues/1228 the plan for the future milestones. One of them is: 
v3.1:

No more features. We need to finish two things for release I think:
1 Documentation
2 **Someone needs to run through a default installation, and then try all of the examples to make sure they are working, reporting any bugs we find. Once those bugs are cleaned up, we should be ready to release.**

I have a new employee that would like to learn how to work with QCubed, I'll let him set up a new installation, and test out all the examples. It's good practice, and he can report or even fix the bugs that he encounters. 

I don't know how to assign this issue to a particular milestone. But this should obviously be included in https://github.com/qcubed/qcubed/issues?q=is%3Aopen+is%3Aissue+milestone%3A%223.1+Release%22

**Comment by spekary** [comment]
Thank you!

**Comment by vmakre** [comment]
QDataGrid row click event overwrite filter (order) click bug.
Table header needs to be disabled from click row event.
From this example just click table header.
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/rowactions.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/rowactions.php).

**Comment by kukrik** [comment]
Yes, this table header does not work. But the Draft tables, headers are working properly.

**Comment by spekary** [comment]
Enter an issue for this please.

**Comment by kukrik** [comment]
This @vmakre's question made me look up and try. Examples table header is indeed broken: http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/rowactions.php

I tried Draft tables headers, they are working on. I just checked the @vmakre's issue.

**Comment by nickverstocken** [comment]
Error in example : http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/rowactions.php. 
![error](https://cloud.githubusercontent.com/assets/12858587/25280250/8e3ba2da-26a9-11e7-99e6-06df17ab94dd.png)

**Comment by spekary** [comment]
v3.1 is now released. v4 is going to alpha. v4 now passes all travis tests, and all example code is up to date. See qcubed/application for v4 info.
