### ISSUE TITLE
MultiQuery error handling not supported

### ISSUE THREAD

**Issue by nickverstocken** [qcubed/qcubed#1255]
When you try to run multiple queries and one of the queries fail (eg duplicate error) the error will not be captured.
To change this I have updated the code of : 
 _vendor/qcubed/database/QMySqli5Database.class.php line 65 :_ 
```
		public function MultiQuery($strQuery) {
			// Connect if Applicable
			if (!$this->blnConnectedFlag) $this->Connect();

			// Perform the Query
			$this->objMySqli->multi_query($strQuery);
			if ($this->objMySqli->error)
				throw new QMySqliDatabaseException($this->objMySqli->error, $this->objMySqli->errno, $strQuery);

			$objResultSets = array();
			do {
				if ($objResult = $this->objMySqli->store_result()) {
					array_push($objResultSets,new QMySqli5DatabaseResult($objResult, $this));
				}
			} while ($this->objMySqli->more_results() && $this->objMySqli->next_result());

			return $objResultSets;
		}
```
to this : 
```
		public function MultiQuery($strQuery) {
			// Connect if Applicable

			if (!$this->blnConnectedFlag) $this->Connect();
			$objResultSets = array();
			if($this->objMySqli->multi_query($strQuery)){
				do {
					if(!$this->objMySqli->more_results()){
						break;
					}
					if(!$this->objMySqli->next_result()){
						throw new Exception($this->objMySqli->error, $this->objMySqli->errno);
						break;
					}
					if ($objResult = $this->objMySqli->store_result()) {
						array_push($objResultSets,new QMySqli5DatabaseResult($objResult, $this));
					}
				} while (true);
			}
			return $objResultSets;
		}
```

I don't know if this is an issue or not I just wanted to help the community. 

Regards, 
Nick

**Comment by dzawata** [comment]
I'm working on QCUBED project which use MySQL as main database. And now I'm migrating from MySQL to PostgreSQL. There are many class that run well with MySQL, but that's not with PostgreSQL. I only found two class for postgresql and all of them not complete like MySQL. Maybe someone can give an suggest. 

For example, function MultiQuery just in MySQL, I can't find it in PostgreSQL whereas I need it with PostgreSQL.

**Comment by matthiaz** [comment]
I know Nick personally, I'm pretty sure he's no longer working with qcubed. closing.
