### ISSUE TITLE
new visible representation method

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1263]
I don't know if this is possible.
Let's think about connection between single table column value and visible representation of this value or values in form with possible edit . My idea is to do some additional codegen of db model and form controls so we can call model connector directly  like
` $newcontrol = new QVisibleControl(dbtable_model->column_name(id_value)); `
With this method we can change different types of control types , check box , radio button e.t.c  but only if visibility types are allowed .
`$newcontrol->Render->radiobutton;`
 If column is integer then only input type text is available.
Idea is to shorten a lot of code where we create input's,  buttons or select's and connect them with db orm's , and we create events for them. So when we initialize visible_control , we automatically have update event methods (ajax) on this control or form verification  . Dynamically created Update event  can be generated in form control codegen not in db orm. This is similar to model connector but in a little different manner to initialize only column model not all db controls. Visible_control types can be generated dynamically not statically and be used rarely when we need to change something not in working table or modify some settings stored in database e.t.c.

**Comment by vmakre** [comment]
With a little rethinking of same idea i can approve this: 
1. QVisibleControl object is like "QPanel" a parent of new generated control 
2. QVisibleControl  can handle validations and model connector selects.
3. Child control is like any other  form control QButton, QText ...  but inside QVisibleControl
4. All properties and methods from form control are accessible though QVisibleControl
so i can type:
```
$newcontrol = new QVisibleControl($this , dbtable_model->colum_name(id_value) )
$newcontrol->text = "new text"; 
```
is same as 
`$newcontrol->generated_object_control->name  = "new text"`

**Comment by spekary** [comment]
I don't quite understand. But I think you are asking for something that is already there in v3. 

> With this method we can change different types of control types , check box , radio button e.t.c but only if visibility types are allowed .

Currently, the control_registry files are the mechnanism that connects a database column type with a control type that could be edited. This becomes a dropdown list in the model connector editor that lets you select which kind of control that you want to edit that particular data column.

**Comment by vmakre** [comment]
No i don't want dropdown list because it is from model connector editor. What if i want to 
put some control from other table e.g. to change value of some column .
Something like Qpanel to be container of control but need to handle db connection and form validation .

**Comment by spekary** [comment]
Just create a model connector from inside the panel. A model connector does not have to be created in a form. In fact, in the new templates, the model connector is created from a main enclosing panel, not in the form. You can have more than one model connector in a panel if you need to manage multiple sql tables from the same panel. Perhaps I still don't understand what you are trying to do though.

**Comment by vmakre** [comment]
I want to write single line of code to represent column  in table as 
control automatically, not trying to create model controller .
for example if column type is boolean (true false)
$this->visiblecontrol = new QVisibleControl($this , "table->column");
and after
$this->visiblecontrol->Render() ;
to get checkbox with possibility of validation in form. 
So visiblecontrol need to know type of column to generate QCheckBox object inside it.
I am reading [http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other_controls/sample.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other_controls/sample.php)

**Comment by spekary** [comment]
Ahh. That will be a bit tricky. You will need a way to specify that certain controls match certain column types. How do you know whether to use a TextBox, an EmailTextBox, a PhoneTextBox, or a Bootstrap TextBox?

Adding the requirement to do validation and save, etc. I don't think so. Every control does the differently. That is the whole point of the ModelEditor. It defaults to a particular kind of control, but you can customize it easily. You also get all the connection for the control to load, update, save, reload etc. Is the ModelEditor not going to work for you?

**Comment by vmakre** [comment]
Yes it is tricky but very simple and powerful for custom forms with a lot of different controls. And main point is it is very flexible . Maybe extending db codegen can help a little in defining db models with additional properties as column schema types.

**Comment by spekary** [comment]
Some things to consider as you do this:
1) The latest versions, 3.0 and 4.0, support layered custom templates by simply pointing to them. So you can do whatever you want in templates and make it available to the community.
2) The ModelEditor is alread a mechanism for associating columns in the database with control types, but its static. You will need to come up with some other way of storing these associations.
3) You will find it more difficult than your realize to provide the CRUD functionality. Its not always straight forward. For example, an autocomplete is both a selection id and text to display. Its not just a simple value. 
4) As much as possible, utilize the Value property that I have added to many controls. It is an attempt at trying to unify an API for getting and setting the essential value of a control. For basic HTML controls, it should do the same thing as the .val() function in JQuery.
