### ISSUE TITLE
QDateTime::setTime not compatible with DateTime::setTime

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1265]
Warning: Declaration of QDateTime::setTime($mixValue, $intMinute = NULL, $intSecond = NULL) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) in /vendor/qcubed/qcubed/includes/framework/QDateTime.class.php on line 28
I am testing it on php7 , using qcubed 3.0 master. 
Just extend SetTime in QDateTime.class.php in line 509 with this line:
`		public function setTime($mixValue, $intMinute = null, $intSecond = null , $intMicroseconds = null ) {`

**Comment by spekary** [comment]
This has already been fixed in current master and other branches. Try doing a new pull. Doesn't look like you have the latest.

**Comment by vmakre** [comment]
where is fixed in qcubed vendor or project code??

**Comment by spekary** [comment]
https://github.com/qcubed/qcubed/blob/master/includes/framework/QDateTime.class.php#L509
