### ISSUE TITLE
htmlpurifier implementation

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1268]
I have a plan for one project with public users access to html editor. Is htmlpurifier active as maintained part of qcubed ? . Is it safe enough or we need to think for something other?

**Comment by spekary** [comment]
See http://htmlpurifier.org. It is a separate library apart from QCubed. If you are using QCubed v3 or above, you will be using Composer to bring it in to your project, and it will help you maintain your project to use the latest version.

QCubed uses HTML Purifier in the TextBox control and its subclasses.

**Comment by spekary** [comment]
However, if you are planning a public access html editor, you can consider using CKEditor, which I think has its own built-in XSS prevention mechanism.

**Comment by kukrik** [comment]
@vmakre, I do not know if my observation is relevant to you? But I'll say that the htmlpurifier must already be active.

Please look there https://github.com/qcubed/plugin_ckeditor/blob/master/includes/QCKEditorBase.php, there's one line: 
```php
 ...
$this->strCrossScripting = \QCrossScripting::Allow;
$this->strTextMode = \QTextMode::MultiLine;
...
```
