### ISSUE TITLE
Undefined SET property or variable "strObjectName" with qcubed 3.1

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1271]
I installed the new qcubed version (v3.1) in my machine. What can this problem be?
<img width="1270" alt="screen shot 2017-07-08 at 03 45 50" src="https://user-images.githubusercontent.com/2853034/27981138-156dd494-6390-11e7-92ca-61c717f09aab.png">
EDIT: I found one problem. @spekary, you have forgot to add to everyone Draft/ _ _ _edit.php 2 rows:
```php
protected $strObjectName;
protected $strObjectNamePlural;
```
You should fix this error as soon as possible 👍 !

**Comment by spekary** [comment]
Fixed in #1273. Thanks for letting me know. You will need to delete the contents of the forms directory and codegen again.
