### ISSUE TITLE
Autocomplete example not working

### ISSUE THREAD

**Issue by koopa** [qcubed/qcubed#1276]
I was just looking at the [JQ examples](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other_controls/jq_example.php) and noticed the autocomplete is not working.
Can someone else confirm this? Tried in Chrome + FF.

**Comment by spekary** [comment]
The autocompletes on that link is working for me. Check your javascript console for any errors.

Note that it is using ajax to populate the data, so a slow internet connection will cause problems.

**Comment by matthiaz** [comment]
Both seem to be working, although the autocomplete with autofocus feels
very slow.

2017-07-19 2:14 GMT+02:00 Shannon <notifications@github.com>:

**Comment by koopa** [comment]
Thanks for the infos! Didn't get any errors in the console - just nothing happened. I tried it on a different box and there it is working. So there must be something wrong with the other system.
