### ISSUE TITLE
Is there a second solution for multi-foreach and data storage at the same time?

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1279]
I understand that the framework allows only by one item to be saved, edited, updated or deleted. Maybe I get it wrong?

I have one small project at the moment. My concern is that I did not find a good or normal solution.

The thing is that I have three tables "sports_areas", "sports_statistics_folder" and "sports_areas_folders". The first and second tables are fine, no worries. The third table is also fine, but from the user's point of view, filling the table is not convenient.

I decided to make a multi foreach function to the table. I decided to make a multi-foreach function to the table. Then the user does not have to work repetitively.

The problem is this:
1.	The "Generate table" function (currently the wrong solution) stores only one item, and moreover, it is incorrect. One has to think like, for example, the SaveAll() function. After that, we also have to think about the functions UpdateAll(), DeleteAll().
This screenshot shows: 

<img width="1280" alt="screen shot 2017-08-18 at 12 47 03" src="https://user-images.githubusercontent.com/2853034/29477529-679b533e-8471-11e7-9621-9023c0541ae2.png">

2.	The foreach + foreach function works well for the first save. Must update the browser, which is not the right answer right now. It his been for the test (row 64: `$this->pnlSportsAreasFolders->Save();`), then after must take away.

Example of the first recording (correct):

<img width="1280" alt="screen shot 2017-08-18 at 13 56 48" src="https://user-images.githubusercontent.com/2853034/29477560-80d1c626-8471-11e7-8a6d-8207de74f4b7.png">

If you save the second time or more, then the expected result is not. It saves the same entries a second time or more.

I know this is not it. This is a partial solution. Below is my partial solution:

```php
// Load the QCubed Development Framework
require('../qcubed.inc.php');

require(__PANEL__ . '/SportsAreasFoldersEditPanel.class.php');

class Generate_Table_Form extends QForm {

    protected $pnlSportsAreasFolders;

    protected $btnGenerate;


    // Override Form Event Handlers as Needed
    protected function Form_Run() {
        parent::Form_Run();

        // Security check for ALLOW_REMOTE_ADMIN
        // To allow access REGARDLESS of ALLOW_REMOTE_ADMIN, simply remove the line below
        QApplication::CheckRemoteAdmin();
    }

    protected function Form_Create() {
        parent::Form_Create();

        $objSportsAreasArray = SportsAreas::LoadAll(QQ::Clause(
            QQ::OrderBy(QQN::SportsAreas()->Id)
        ));

        $objSportsStatisticsFolderArray = SportsStatisticsFolder::LoadAll(QQ::Clause(
            QQ::OrderBy(QQN::SportsStatisticsFolder()->Id)
        ));

        foreach ($objSportsAreasArray as $objSportsAreas) {
            foreach ($objSportsStatisticsFolderArray as $objSportsStatisticsFolder) {

                //Exemplary test
                //This is where the additional function should be implemented,
                //so if you save it a second or multiple times, each row should be checked
                //to see if there is or not a unique key pair in the database.
                //If it exists, it will not be saved and the check will go to the next row, etc.

                $unique_key_pair = [[$objSportsAreas, $objSportsStatisticsFolder]];

                foreach ($unique_key_pair as list($a, $b)) {

                    echo "<div style='width: 500px; margin-left: 200px;'>" . $a . " -- " . $b . "</div>";

                }

                //Exemplary test End

                $this->pnlSportsAreasFolders = new SportsAreasFolders($this);
                $this->pnlSportsAreasFolders->SportsAreasId = $objSportsAreas->Id;
                $this->pnlSportsAreasFolders->SportsStatisticsFolderId = $objSportsStatisticsFolder->Id;
                $this->pnlSportsAreasFolders->UploadPath = __APP_UPLOAD_ASSETS__ . '/spordialad/' .
                    QString::SanitizeForUrl($objSportsAreas) . '/' .
                    QString::SanitizeForUrl($objSportsStatisticsFolder);


                //For the test
                //After removing this line.
                //We use the button "Generate table".
                $this->pnlSportsAreasFolders->Save();

            }
        }
        $this->CreateButtons();

    }

    protected function CreateButtons() {
        // Create Buttons and Actions on this Form
        $this->btnGenerate = new QJqButton($this);
        $this->btnGenerate->Text = QApplication::Translate('Generate table');
        $this->btnGenerate->AddAction(new QClickEvent(), new QAjaxAction('btnGenerate_Click'));
        $this->btnGenerate->CausesValidation = true;
    }

    // Button Event Handlers
   /**
    * Process a click on the Save button.
    *
    * @param $strFormId
    * @param $strControlId
    * @param $strParameter
    */
    protected function btnGenerate_Click($strFormId, $strControlId, $strParameter) {
        try {

            //How to activate table generation?
            //Here is also the place where the Save() function does not fit.
            //We have to think about how to make SaveAll (), for example?
            //Some thoughts or ideas?

            $this->pnlSportsAreasFolders->Save();
        }
        catch (QOptimisticLockingException $e) {
            $dlg = QDialog::Alert (
                QApplication::Translate("Another user has changed the information while you were editing it. Would you like to overwrite their changes, or refresh the page and try editing again?"),
                ["Refresh", "Overwrite"]);
            $dlg->AddAction(new QDialog_ButtonEvent(0, null, null, true), new QAjaxAction("dlgOptimisticLocking_ButtonEvent"));
            return;
        }
        $this->RedirectToListPage();
    }

    /**
     * An optimistic lock exception has fired and we have put a dialog on the screen asking the user what they want to do.
     * The user can either overwrite the data, or refresh and start the edit process over.
     *
     * @param string $strFormId      The form id
     * @param string $strControlId   The control id of the dialog
     * @param string $btn            The text on the button
     */
    protected function dlgOptimisticLocking_ButtonEvent($strFormId, $strControlId, $btn) {
        if ($btn == "Overwrite") {
            $this->pnlSportsAreasFolders->Save(true);
            $this->GetControl($strControlId)->Close();
            $this->RedirectToListPage();
        } else { // Refresh
            $this->GetControl($strControlId)->Close();
            $this->pnlSportsAreasFolders->Refresh(true);
        }
    }

    protected function RedirectToListPage() {
        QApplication::Redirect(__VIRTUAL_DIRECTORY__ . __FORMS__ . '/sports_areas_folders_list.php', false);
        // Putting false here is important to preventing an optimistic locking exception as a result of the user pressing the back button on the browser
    }

}
Generate_Table_Form::Run('Generate_Table_Form');
```
Do you have a better thought or do you have some similar solutions? I would be very grateful.

PS. If interested, I put this file and 3 sql tables in here: 
[test_for_multi_foreach_and_save.zip](https://github.com/qcubed/qcubed/files/1235649/test_for_multi_foreach_and_save.zip)

**Comment by spekary** [comment]
This is not something we can automate through code generation. Save happens one at a time, no matter what you do. If you need to save multiple items, you still save them one at a time in SQL. Version 3.1 has implemented a detection so that the save only saves what has changed in each record, so it should be faster. This is simply something you have to do in your business logic. And it can be a little difficult.

If you create multiple items before saving, you likely have to create a fake Id indicating it is not saved. I have used negative ids. I also edit the model file to allow for assigning an id like this, and then the Save function can look, and if the id is negative, do an insert, otherwise do an update. After saving, you must make sure the new id is assigned to the record. Its tricky stuff, as you have to allow for someone adding, and then deleting records that are either saved or unsaved, and then updating the whole set of choices at the end. I think the best user experience will be obtained by creating a shadow of the data the user is looking at, and then creating a kind of synchronizer between the edited list, and the database.

**Comment by kukrik** [comment]
@spekary, thank you for sharing your thoughts.

It's a bit hard for me to understand your tips, but I'll try to understand your logic. Your suggestions are really interesting. Can you give some examples? For example, an fake id or a negative id etc...

I will explain a bit about the goals of the project, what my client wants. This third table is an intermediate step. The client wants a simple solution if it is necessary to upload the document and put it in the correct folder according to the correct sport.

This means after fourth table where need 2 listbox and uploads for a document. That's why in the third table upload_path and related folders.

In the third table, can not delete rows, can only turn off one or another folder in the edit view (that's why I added one column for is_activated), otherwise it's too complicated or meaningless business logic.

The first and second tables can be edited. The third table must respond according to the first and second tables.

That would be my point of view. I think it would be a logical approach. I understand that this solution will be tricky.

How do you recommend it?

**Comment by spekary** [comment]
Do not use a 3rd table as an intermediate step. Store that in memory as a list of documents in the form as a local variable. After the user clicks Save(), then walk the list and save each document.

**Comment by kukrik** [comment]
@spekary, wait, wait, this is a pretty simple and brilliant solution. I have to think a bit...

The first table is pretty simple when I create a single sports area, while the first level folder is automatically created.

Anyway have to think a bit about creating level 2 folders (e.g, Guide, Results, Timetable etc). Obviously, need to perform the checking function if there is no folder, then the subfolder will be created before uploading the document or if the subfolder exists, the document will be loaded directly into that folder etc.

I have to think a bit about how to do better. But look, why it's complicated to think if can go a little easier :)...

I will let you know if I have any questions. Anyway I thank you!
