### ISSUE TITLE
mysqli_real_escape_string on custom querry

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1280]
I want to put custom query : 
```
$value2 = "...   html string...."    ;
$strQuery="insert into table1 (column1 , column2) ('abcd' ,". $value2 ." );" ;
$objDatabase = QApplication::$Database[1];
$objDatabase->NonQuery($strQuery);
```
how to make mysql escape string using qcubed database connector ?

**Comment by matthiaz** [comment]
Why not use $objDatabase->SqlVariable($value2) ?

2017-09-15 11:35 GMT+02:00 Vladimir Makreski <notifications@github.com>:

**Comment by vmakre** [comment]
Yes @matthiaz  it is hard to find  something in documentation because it doesn't exist.
