### ISSUE TITLE
Hello, is there support for a field that takes currency values: € 100.000,50 or $ 100,000.50

### ISSUE THREAD

**Issue by tronics** [qcubed/qcubed#1282]
Hello, 

is there a qform for a field that takes currency values: € 100.000,50 or $ 100,000.50
I can remember there was something. But this was in the old forum which is not available anymore.
Looking at the code it seems this is not available.

But maybe someone could enlighten me. 
Thank you.

**Comment by spekary** [comment]
There is nothing built-in. The built-in stuff is going to give you whatever html can produce. If you want anything more, you will need to craft it yourself or create a plugin.

**Comment by kukrik** [comment]
The same concern. I saw post your referral but can not find anymore. I also have a plan for this issue, but have not yet reached...
Perhaps it is a great help to those links http://php.net/manual/en/function.money-format.php and https://stackoverflow.com/questions/4325363/converting-a-number-with-comma-as-decimal-point-to-float.

If we do, for example, the function `public function PriceFormatted(etc, etc, ...)`. But the value entered has to go to the database in the standard format.

**Comment by koopa** [comment]
In the past I used a text input with `min`, `max` and `step` attributes and some client side scripting.

Here's a [mini demo](https://output.jsbin.com/cacifosoru/1) that can do formatting of thousand separators and quantize to the closest step (or smallest coin if you will). And ultimately get back a float, of course. Feel free to use any part(s) of it.

Leaving the input causes the value to be split into groups of 3 digits, starting from the right side and inserting the defined separator between each group.

When the input has focus the up and down arrows step the value up or down respectively. Holding the modifier keys increases step size momentarily.

**Comment by tronics** [comment]
I found the solution that I used in 2009. 
It already existed.. and I crossposted this to qcodo.

http://www.qcodo.com/issues/view.php/9

Allow german komma in QFloat. 
This means that 12343,90 can be entered in a QFloat field and gets saved correctly.
Unfortunately it is a bit of a hack and the point for thousand is not supported.

I do have the correct regex for this and will post it currenctly it works only with str_replace

``<?php
    // A subclass of TextBox with its validate method overridden -- Validate will also ensure
    // that the Text is a valid integer and (if applicable) is in the range of Minimum <= x <= Maximum
    // * "Maximum" (optional) is the maximum value the integer can be
    // * "Minimum" (optional) is the minimum value the integer can be
    // To support , additional to . a 

    class QFloatTextBox extends QTextBox {
        ///////////////////////////
        // Private Member Variables
        ///////////////////////////

        // MISC
        protected $fltMaximum = null;
        protected $fltMinimum = null;

        protected $strLabelForInvalid;
        protected $strLabelForLess;
        protected $strLabelForGreater;
        
        protected $blnExtendedDecimalPointSupport;

        //////////
        // Methods
        //////////
        public function __construct($objParentObject, $strControlId = null) {
            parent::__construct($objParentObject, $strControlId);

            $this->strLabelForInvalid = QApplication::Translate('Invalid Float');
            $this->strLabelForLess = QApplication::Translate('Value must be less than %s');
            $this->strLabelForGreater = QApplication::Translate('Value must be greater than %s');
        }

        public function Validate() {
            if (parent::Validate()) {
                
                $arrLocales=array();
            $arrLocales=localeconv();
            if ($arrLocales['decimal_point']=="")$arrLocales['decimal_point']=".";
                if ($arrLocales['decimal_point']==",")$this->blnExtendedDecimalPointSupport=true;
                
                //set globally ;)
                //$this->blnExtendedDecimalPointSupport=true;
                
                if ($this->strText != '') {
                    try {
                        $this->strText = ($this->blnExtendedDecimalPointSupport) ? str_replace(",", ".", $this->strText) : $this->strText;
                        $this->strText = QType::Cast($this->strText, QType::Float);
                        $this->strText = ($this->blnExtendedDecimalPointSupport) ? str_replace(".", ",", $this->strText) : $this->strText;
                    } catch (QInvalidCastException $objExc) {
                        $this->strText = ($this->blnExtendedDecimalPointSupport) ? str_replace(".", ",", $this->strText) : $this->strText;
                        $this->strValidationError = $this->strLabelForInvalid;
                        return false;
                    }
                    
                    if ((!is_null($this->fltMinimum)) && ($this->strText < $this->fltMinimum)) {
                        $this->strValidationError = sprintf($this->strLabelForGreater, $this->fltMinimum);
                        return false;
                    }

                    if ((!is_null($this->fltMaximum)) && ($this->strText > $this->fltMaximum)) {
                        $this->strValidationError = sprintf($this->strLabelForLess, $this->fltMaximum);
                        return false;
                    }
                }
            } else
                return false;

            $this->strValidationError = '';
            return true;
        }

        /////////////////////////
        // Public Properties: GET
        /////////////////////////
        public function __get($strName) {
            switch ($strName) {
                // MISC
                case 'Maximum': return $this->fltMaximum;
                case 'Minimum': return $this->fltMinimum;
                case 'LabelForInvalid': return $this->strLabelForInvalid;
                case 'LabelForGreater': return $this->strLabelForGreater;
                case 'LabelForLess': return $this->strLabelForLess;
                case 'ExtendedDecimalPointSupport': return $this->blnExtendedDecimalPointSupport;



                default:
                 if (QApplication::$CommaFloats)
                         switch ($strName) {
                            case 'Text':
                                return str_replace(",",".",$this->strText);
                            case 'TextFloat':
                                return str_replace(",",".",$this->strText);
                            default:
                                try {
                                    return parent::__get($strName);
                                } catch (QCallerException $objExc) {
                                    $objExc->IncrementOffset();
                                    throw $objExc;
                                }
                        }
                else
                        try {
                            return parent::__get($strName);
                        } catch (QCallerException $objExc) {
                            $objExc->IncrementOffset();
                            throw $objExc;
                        }


    
            }
        }

        /////////////////////////
        // Public Properties: SET
        /////////////////////////
        public function __set($strName, $mixValue) {
            $this->blnModified = true;

            switch ($strName) {
                // MISC
                case 'Maximum':
                    try {
                        $this->fltMaximum = QType::Cast($mixValue, QType::Float);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }
                case 'Minimum':
                    try {
                        $this->fltMinimum = QType::Cast($mixValue, QType::Float);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }
                case 'ExtendedDecimalPointSupport':
                    try {
                        $this->blnExtendedDecimalPointSupport = QType::Cast($mixValue, QType::Boolean);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }

                case 'LabelForInvalid':
                    try {
                        $this->strLabelForInvalid = QType::Cast($mixValue, QType::String);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }

                case 'LabelForGreater':
                    try {
                        $this->strLabelForGreater = QType::Cast($mixValue, QType::String);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }

                case 'LabelForLess':
                    try {
                        $this->strLabelForLess = QType::Cast($mixValue, QType::String);
                        break;
                    } catch (QInvalidCastException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }

                default:                    
                    try {
                        $mixValue = (QApplication::$CommaFloats) ? str_replace(".",",",QType::Cast($mixValue, QType::String)) : $mixValue;
                        parent::__set($strName, $mixValue);
                    } catch (QCallerException $objExc) {
                        $objExc->IncrementOffset();
                        throw $objExc;
                    }
                    break;
                    

            }
        }
    }
?>


 ``

**Comment by kukrik** [comment]
Probably must be done QCurrencyTextBox class?
