### ISSUE TITLE
qcu.be and examples

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1285]
Something went down with examples. And second question is why examples aren't on github so we can update or modify  them ?

**Comment by spekary** [comment]
https://github.com/qcubed/examples.qcu.be

**Comment by jllabs** [comment]
The whole qcu.be site is down

**Comment by matthiaz** [comment]
Looks like the domain expired.

I'll send an email to Kristof to see if he wants to renew it, or if he
wants someone else to take over.

2017-10-30 10:14 GMT+01:00 JL <notifications@github.com>:

**Comment by vmakre** [comment]
@matthiaz  did you email Kristof ? . @spekary do you have time to make a little effort on making a new site? .  I have a time to  things but i need all documentations can be found online about qcubed and qcodo . Now I have time to sort things with your help. If someone want to participate  you can email me at vmakre@gmail.com.

**Comment by matthiaz** [comment]
I did, he isn't active in the community anymore but is willing to renew the
domain.

2017-11-01 18:35 GMT+01:00 Vladimir Makreski <notifications@github.com>:

**Comment by spekary** [comment]
I can provide space for a new web site if needed, but I can't renew a belgian domain, only he can.

**Comment by vmakre** [comment]
Maybe i will put it on temporary shared host for public preview and update, before move to real domain.

**Comment by kukrik** [comment]
This site has been down in recent years. I can try to talk with an Estonian service provider, maybe I get a discount. I know that good prices are being made for non-profit organizations and the community.
How about that? I looked at free domains, now it's qcubed.eu.
@spekary, what do you think of this? If yes, do not have access to the problem, because I'm not going to do it alone, etc.

**Comment by matthiaz** [comment]
I'm Belgian myself so if need be I can transfer it.
It will cost me less than 10euro's so price is not an issue ;-)

I forgot what exactly was on the website, I always go straight to github.

2017-11-01 21:10 GMT+01:00 Tiit Papp <notifications@github.com>:

**Comment by spekary** [comment]
The website at this point had just the examples and a little intro page I think. Everything else was pointing to Github. The website also had a script that reset the database running the examples every day, and possibly did a git pull of github of the code.

**Comment by matthiaz** [comment]
qcu.be is back online

2017-11-02 13:32 GMT+01:00 Shannon <notifications@github.com>:

**Comment by kukrik** [comment]
Very good to hear! However, there is one concern that the examples database should be cleaned up and restored with standard data. That would be fine!

**Comment by neuroticimbecile** [comment]
Please check.
The examples site is down again.

**Comment by kukrik** [comment]
@matthiaz, @spekary! An example site is down again! I can provide for example my help and I can also pay for accommodation and the domain. For example, the address of qcubed.eu? I give you full access to administration, etc. What do you think?

**Comment by spekary** [comment]
@olegabr was the last to work on the site. His work is checked in to the qcubed/examples.qcu.be here in the github repo. Hopefully it is not too difficult to move over. We can point to it from oru github pages.

**Comment by kukrik** [comment]
I will take time to set up a domain https://qcubed.eu. Of course, we do not need a website. Only examples :)...

I took it, it also means for you, the domain https://qcubed.eu.

PS.  I have you and @shannon addresses available, I will send later the exact details for accessing the administration of the server.

**Comment by shannon** [comment]
@kukrik wrong @shannon

**Comment by kukrik** [comment]
> @kukrik wrong @shannon

I'm sorry, I was wrong here ... I'm fixing it right away!

**Comment by kukrik** [comment]
> @olegabr was the last to work on the site. His work is checked in to the qcubed/examples.qcu.be here in the github repo. Hopefully it is not too difficult to move over. We can point to it from our github pages.

I know this @olegabr script, but I do not know this thing well. I give you full access, do what you need to ensure automatic upgrade from github etc ...

**Comment by matthiaz** [comment]
https://qcubed.eu
