### ISSUE TITLE
broken pages on examples 

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1287]
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/qcheckboxcolumn.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/datagrid/qcheckboxcolumn.php)
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/dynamic/inline_editing.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/dynamic/inline_editing.php)
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other/model_connectors.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other/model_connectors.php)
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/communication/soap.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/communication/soap.php)
[http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/basic_qform/xss.php](http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/basic_qform/xss.php)

**Comment by kukrik** [comment]
Yes, but I see that the examples should be upgraded to the latest version.
A very simple error to see is: http://.../.../vendor/qcubed/framework/assets/.../.../.../...

But it must be like here: http: //.../.../vendor/qcubed/qcubed/assets/.../.../.../...

Pointless mend. Easier to exchange to a new version.

**Comment by vmakre** [comment]
Examples need a good rework and also version upgrade. Better navigation and problem finder (tags).
I am always opening minimum 5 pages to find what i need. 
We need also versioning of examples , i am sure qcubed version 4 will not be same as version3 also examples .

**Comment by kukrik** [comment]
Right to say that qcubed version 4 will not be same as version3 also examples. I currently use the most recent version of qcubed 3 (3.1.0 Final Release).

I agree that the examples need a good rework and upgrade. I think it's high time to bring everything onto Bootstrap. I believe that developers customize their project after QCubed Bootstrap. Why work twice?

**Comment by matthiaz** [comment]
Check out https://qcubed.eu

**Comment by spekary** [comment]
The version 4 examples should work. I did extensive work on them to make them current with version 4. We simply need to make version 4 the master.

**Comment by kukrik** [comment]
> The version 4 examples should work. I did extensive work on them to make them current with version 4. We simply need to make version 4 the master.

Fits well!

**Comment by kukrik** [comment]
Is there not enough info in the footer for information about the version?

As has always been...

**Comment by spekary** [comment]
I think we need to decide whether we are going to publish version 4, or try to maintain both versions.

**Comment by kukrik** [comment]
I look forward to the opinions of others...

**Comment by vmakre** [comment]
We need different examples per version, like new functionalities. @spekary  can we  reorganize qcubed repos and regroup examples , plugins  ?. I am a bit confused about orm  , application , qcubed.
Having all subversions of v4 in one , and all plugins to be in one plugin repo .

**Comment by spekary** [comment]
These separate directories are here for a few reasons. But you can look at other frameworks, like Symphony, to see why. Some people asked for the ability to use parts of the framework without requiring the whole thing, like being able to use only the orm. I spent a lot of time removing the orm dependencies from the rest of the framework, but to do that, I also had to put the parts of the framework that the orm DOES depend on into its own repo (common). This approach also allows the modules to be updated independently. The orm can change versions without everything else needing to change versions. This approach was also required to create a starter (app-starter). This lets us create independent, supported, but not required modules too, like bootstrap. In general, this is simply the way that frameworks in PHP are being structured, and that was v4's main reason for being - to create a qcubed that was more consistent with modern PHP usage, including the PSR's.
