### ISSUE TITLE
I am looking for a hint or suggestion of a plugin to solve the problem

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1289]
Perhaps I'm too demanding and constantly looking for the right solutions. But I did not find the answer to the problem. Or is it actually a simple answer? I'm talking about making plugins. 

If we make a new plugin, then the new function names should be active, but I do not have these names active as the orange color in the example below.
<img width="862" alt="screen shot 2017-12-07 at 02 06 51" src="https://user-images.githubusercontent.com/2853034/33692773-abd5bcb0-daf7-11e7-90d0-ad10f521d6a7.png">
Or are they normal? I do not think they are normal. Something is missing... QCubed plugins names new functions are active.
You can get acquainted https://github.com/kukrik/counterup2 and https://packagist.org/packages/kukrik/counterup2.

@spekary, please give a hint or advice. I would be very grateful.

**Comment by spekary** [comment]
You must put property tags in the comment block for the class.

For example, this is in the PhoneTextBox plugin:
 * @property string $DefaultAreaCode The default area code to prefill with.

**Comment by spekary** [comment]
Looking at your plugin, I think you have everything else correct.

**Comment by kukrik** [comment]
@spekary, property tags is added. Hope I did not write wrong. I know my English language is weak. I made some corrections and added one small example. Now this plugin works properly for me. Hopefully...
This is at least my first contribution for QCubed 4v. Thank you!
