### ISSUE TITLE
Small observations faulty plugins from QCubed 4v

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1290]
I discovered that Bootstrap Nav.php and ListGroup.php are corrupted. Small and same mistake:

<img width="1280" alt="screen shot 2017-12-08 at 23 57 48" src="https://user-images.githubusercontent.com/2853034/33789857-3b84d016-dc84-11e7-9b49-8314b064ec6c.png">

The second error is also Phonetextbox, double feature:

<img width="503" alt="screen shot 2017-12-08 at 23 56 17" src="https://user-images.githubusercontent.com/2853034/33790055-ae0ca5c2-dc85-11e7-9b39-486a5c63db1f.png">

@spekary, I will let you know...

**Comment by kukrik** [comment]
@spekary, I was looking for a problem and could not find a reasonable explanation.
What do these lines do:
1) https://github.com/qcubed/bootstrap/commit/f24def81fe43a02aa1f6fb601360c1363a5a2516#diff-9f902c5f69c9662af7e4b9fc37b48681R122
2) https://github.com/qcubed/bootstrap/commit/f24def81fe43a02aa1f6fb601360c1363a5a2516#diff-bb160d52898b0d1631267962d986e75eR137

For the test I changed `$this->strSelectedItemId = $ params[ControlBase::ACTION_PARAM];`  to `$this->strSelectedItemId = $params;` and `$this->strActiveItemId = $ params[ControlBase::ACTION_PARAM];` to `$this->strActiveItemId = $params;` Then they work for me at least.

But I can not find any purpose for `ControlBase::ACTION_PARAM`. What should it do?

Surely you have other good plans, just missing something? Can you explain?

**Comment by spekary** [comment]
For v4 I changed how actions work. The old way had strFormId, which was never used, and the strControlId, which was used sometimes. The new way is to use an object. It looks like what you found was some kind of intermediate step I was experimenting with.

Those methods are simply recording what tab was clicked on. You should use: 
```
$this->strActiveItemId = $params->ActionParameter
```

**Comment by kukrik** [comment]
@spekary, currently, it is understandable for me! Please fix the changes in the code! It worked for me.

Secondly, the phonetextbox is an interesting story. The PhoneTextBox displays defaultAreaCode correctly at QCubed v3.1, not QCubed v4. Maybe it will give you a hint, you'll find a quick cause.
