### ISSUE TITLE
Sortable small tips (SOLVED)

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1295]
Basically, I would ask for help or advice as little as you can. This time I have to ask for tips and suggestions on how to use Sortable. If I take something new, I'll do a simple test to figure out how one or another thing works. I tried an example: http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other_controls/js_return_param_example.php. 
I have some questions:
1) How do you send the changed data to the database? Would be good without a button "Save"? We know that jQuery/Javascript cannot communicate directly with the MySQL database, our have to send the changed data to PHP first.  I was looking for solutions and did not find a good answer. 
2) I have one simple test page, you can find below. The table name is "sorter", with 3 columns: id, title, order. I have been  investigated from everywhere and will not find a reasonable explanation for how to say the hidden value of `$objSorter->Order`. I understand that this place is not looking for the correct hidden value (find ("div.item"), it looks for a visible value `$objSorter->Title`):
```
find ("div.item")
                map (function () {
                     return $ j (this) .html ()
                }) get () '
```
Do I have to understand that need to use something like this code: 
```
<div data-id = "'. $ ObjSorter-> Id. '"  data-sort ="' .  $ ObjSorter-> Order . '">' .  $objSorter-> Title . '</ div>
```
 etc?

 How have you solved this in QCubed projects? Please share your experience! Your tips, tips and recommendations are invaluable to me, so I can go ahead...

Thank you so much!

<img width="1280" alt="screen shot 2017-12-18 at 00 01 24" src="https://user-images.githubusercontent.com/2853034/34178703-cd6831b4-e510-11e7-9118-c86dc3b040a7.png">

```php
use QCubed\Query\Node;

use QCubed\Action\Ajax;
use QCubed\Action\ActionParams;
use QCubed\Jqui\Event\SortableUpdate;
use QCubed\Project\Jqui\Sortable;
use QCubed\Control\Panel;
use QCubed\Project\Application;
use QCubed\Project\Control\FormBase as Form;

class SortForm extends Form {

    protected $dlgSorter;
    protected $lblSortableResult;
    protected $lblSortableResult1;

    protected function formRun() {
        parent::formRun();
    }

    protected function formCreate() {
        parent::formCreate();

        $strServerActionJsParam = "";

        // Sortable
        $this->dlgSorter = new Sortable($this);
        $this->dlgSorter->AutoRenderChildren = true;
        $this->dlgSorter->CssClass = 'sortable';

        /* $objSorterArray = Sorter::LoadAll(QQ::Clause(QQ::OrderBy(
            QQN::Sorter()->Order)
        )); */

        $objSorterArray = Sorter::LoadAll();
        foreach($objSorterArray as $objSorter) {

            $pnl = new Panel($this->dlgSorter);
            $pnl->Text = $objSorter->Title; //  . ' //Order tracking: ' . $objSorter->Order;
            $pnl->CssClass = 'item';

            $this->lblSortableResult = new Panel($this);

            //print_r($this->dlgSorter->ActionParameter = $objSorter->Order); //For identification

            $strJsParam = '$j("#' . $this->dlgSorter->ControlId . '").
                find("div.item").
                map(function() {
                    return $j(this).html()
                }).get()';
            $this->dlgSorter->addAction(new SortableUpdate(),
                new Ajax("onSort", "default", null, $strJsParam));

            $strServerActionJsParam .= '"sortable": ' . $strJsParam . '}';
        }
    }

    public function onSort(ActionParams $params) {
        // stuff
        // ....????....

        $this->lblSortableResult->Text = print_r($params->ActionParameter, true);
    }
}

SortForm::run('SortForm');
```

**Comment by spekary** [comment]
See http://qcu.be/examples/vendor/qcubed/framework/assets/php/examples/other_controls/jq_example.php for a better example of how to get the data out. The example you stated is one way to interact with JS, but not necessarily the easiest. Draw the sortables in the order you want to display them initially.

All the JQuery UI controls interact with QCubed by sending data through `recordControlModification()` javascript call. This will wait until there is some kind of ajax call, and then on the PHP side call a parameter through __set() on the PHP control. For Sortable, you will see in SortableBase a _ItemArray set parameter. The JS eventually sets its sort order through that.

As mentioned before, it waits until an ajax call to set this on the PHP side. This is how QCubed works in general, since it assumes the PHP side doesn't care about what is going on in the javascript until it asks. So, to ask, you trigger on an event. If you want to know right away after a sort, add an action that triggers on the QSortable_UpdateEvent (SortableUpdate in v4) (see QSortableGen (v3) or the Sortable* files in the Event folder for v4 for all the events you can trigger on). If you don't care until an OK button is pushed, then in your click event handler,  ask for the sort order from the sortable control.

To find out the order, just call $objSortable->ItemArray. It will return a list of control ids in the currently sorted order.

**Comment by kukrik** [comment]
Thanks for the good suggestion! It was a great help for me... We know that ID queues do not change in database tables. We can change the values of other columns.

Now I ran into the deadlock, I could not figure out how to contact the database table and send the changed values to the $order. I was thinking of using the function `public function setOrder ($intOrder)`.

This can be a simple solution for you. But a difficult task for me. Maybe someone can offer a good (desirable) solution. I would be very grateful for any help.

Below are the last lines of the code:

```php
public function sortable_stop($strFormId, $strControlId, $strParameter) {

        $arr = $this->pnlSorter->ItemArray;
        natsort($arr);
        foreach ($arr as $order => $value) {
            $strItems = "$value => $order";

            //$this->??????????->setOrder($order); //This place is intended to update the "order" column of the database table "sorter"
            //$this->??????????->save();
            //$this->??????????->refresh();

            // to a table to update the order column etc...
            Application::displayAlert($strItems);
        }
    }
```
PS. After we remove these lines, of course:
```php
$strItems = "$value => $order";
Application::displayAlert ($strItems);
```

**Comment by kukrik** [comment]
@spekary, I took your recommendation to hear, it's a good solution. I have come closer to the solution, but one obstacle still remains to up.
 
But I have not found a good solution to bind $objSorter->Id from ItemArray. I solved differently, and one obstacle is more...

I entered foreach() below `$this->objIds = $pnl->ActionParameter = $objSorter->Id;`. For control, I looked at the result: `print_r($this->objIds) ;`. And it was a good fit. I got the changed Id queue every time. Now it was necessary to convert a string to an array (the string function str_split()), then I got the undesired result:
`Array ( [0] => 3 ) Array ( [0] => 2 ) Array ( [0] => 1 ) Array ( [0] => 4 ) Array ( [0] => 5 )  `.
It is necessary to get the kind of results: `Array ( [0] => 3 [1] => 2 [2] => 1 [3] => 4 [4] => 5 )  
`.

I realized that this is a foreach() negative effect. I have been looking for a suitable solution for several days but I have not been smarter. I ask your support and advice on how to get the desired result. Thanks in advance!

By the way, I have almost reached the solution, one more obstacle is, I'll show you the solution here:

```php
public function sortable_stop($strFormId, $strControlId, $strParameter) { 

        //$a = $this->pnlSorter->ItemArray;
        //$strItems = join(",", $a);
        //Application::displayAlert($strItems);

        //Before must receive raw string($this->objIds)???
        //$objIdRaws = str_split($this->objIds);
        //$objIdArray = array($objIdRaws);
        $objIdArray = array(3, 2, 1, 4, 5); //Tested and it works...

        foreach ($objIdArray as $key => $value) {
            $objSort = Sorter::load($value);
            $objSort->setOrder($key);
            //$objSort->Order = $key; //Same effect
            $objSort->save();
        }
        $this->pnlSorter->refresh();
    }
```

**Comment by kukrik** [comment]
@spekary, I would like to quote your words: To find out the order, just call $objSortable->ItemArray. It will return a list of control ids in the currently sorted order.
I understand that it yields a result such as: c3,c2,c1,c4,c5 etc. How to tie up ItemArray results with $objSorter->Id? I could not generate a decent idea right now. Perhaps my partial solution is not well suited?

How have you solved this issue? Or share with us experience or knowledge. Thanks in advance!

**Comment by spekary** [comment]
If you are asking how to save a sort order in a database of objects, there are a couple of ways. But generally you have to create field in the database to indicate the sort order of things. If there are different ways to look at the objects, this can get quite complicated, but this is really an implementation specific issue. 

The values returned from the sorter are the QControl object ids. Likely you would want to associate each of those with some kind of database id also and include that id in your objects. How you do that depends on how you are populating the divs inside of the sorter. To borrow from your example:

```
class SortForm extends Form {

    protected $dlgSorter;
    protected $lblSortableResult;
    protected $lblSortableResult1;

    protected function formCreate() {
        parent::formCreate();

        // Sortable
        $this->dlgSorter = new Sortable($this);
        $this->dlgSorter->AutoRenderChildren = true;
        $this->dlgSorter->CssClass = 'sortable';
        $this->dlgSorter->AddAction (new Q\Jqui\Event::SortableUpdate, new Q\Action\Ajax('sortUpdate');

         $objSorterArray = Sorter::LoadAll(QQ::Clause(QQ::OrderBy(
            QQN::Sorter()->Order)
        )); 

        foreach($objSorterArray as $objSorter) {

            $pnl = new Panel($this->dlgSorter);
            $pnl->Text = $objSorter->Title; //  . ' //Order tracking: ' . $objSorter->Order;
            $pnl->CssClass = 'item';
            $pnl->Id = 'sortable' . $objSorter->Id // associate the panel with a database object
        }
    }

    public function sortUpdate(ActionParams $params) {
        $cids = explode(",", $params->param)
        $order = 0;
        foreach($cids as $cid) {
             $order ++;
             $id = substr($cid, 8); // extract the database id from the panel id
             $objSorter = Sorter::Load($id);
             $objSorter->Order = $order;
             $objSorter->Save();
        }

    }
```

**Comment by kukrik** [comment]
@spekary, thank you for taking a little time to answer my questions. I understand that you wrote this example here, right now... 
I understand that you wrote this example right here. Then there are two error here will set out:
1) $pnl->Id = 'sortable_' . $objSorter->Id; // Undefined SET property or variable in 'QCubed\Control\Panel' class: Id
2) $cids = explode(",", $params->params); // Undefined GET property or variable in 'QCubed\Action\ActionParams' class: params

I already knew before that they were not quite right. But I tried them... I have very much searched these questions from Google. It is more or less recommended to use Id. We use ControlId, which makes solving difficult or difficult. I researched several days. I see that you have used one trick, for example, the Datagrid CellClick function.
I have to look into... 
For this, I have to do my `class MyPanel extends BlockControl` where we can get  Id:
```
<div class = "item" id = "c2_1"> One </div>
<div class = "item" id = "c3_2"> Two </div>
<div class = "item" id = "c4_3"> Three </div>, etc ...
```
And at the end write something about:
```php
$a = explode (",", $this->dlgSorter->ItemArray); // Do not know at the moment, must be tested
$b = explode ("_", $a); // Do not know at the moment, must be tested
$ cids = end ($b);
etc ...
```
This is about my vision, to be tested. What do you think of this?

**Comment by kukrik** [comment]
Okay, I have had a long study time, but it was useful to me. If logic is clear to me, then a more complex solution can go, etc.
The solution below works correctly. It is always possible to solve more complicated tasks.
```
CREATE TABLE `sorter` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `order` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```
```php
require('../qcubed.inc.php');

use QCubed as Q;
use QCubed\Exception\Caller;
use QCubed\Exception\InvalidCast;
use QCubed\Control\BlockControl;
use QCubed\Type;
use QCubed\Query\QQ;
use QCubed\Project\Control\FormBase as Form;

class MyPanel extends BlockControl {
    protected $intId = null;

    protected function getControlHtml() {

        if ($this->intId) {
            $strHtml = $this->renderTag('div', ['id'=>$this->strControlId . '_' . $this->intId], null, $this->strText);
        } else {
            $strHtml = $this->renderTag('div', ['id'=>$this->strControlId],  null, $this->strText);
        }
        return $strHtml;
    }

    public function __get($strName) {
        switch ($strName) {
            case "Id": return $this->intId;

            default:
                try {
                    return parent::__get($strName);
                } catch (Caller $objExc) {
                    $objExc->incrementOffset();
                    throw $objExc;
                }
        }
    }

    public function __set($strName, $mixValue) {
        switch ($strName) {
            case "Id":
                try {
                    $this->intId = Type::cast($mixValue, Type::INTEGER);
                    $this->blnModified = true;
                    break;
                } catch (InvalidCast $objExc) {
                    $objExc->incrementOffset();
                    throw $objExc;
                }

            default:
                try {
                    parent::__set($strName, $mixValue);
                } catch (Caller $objExc) {
                    $objExc->incrementOffset();
                    throw $objExc;
                }
                break;
        }
    }
}

class SortForm extends Form {
    protected $dlgSorter;

    protected function formCreate() {
        parent::formCreate();

        $objSorterArray = Sorter::LoadAll(QQ::Clause(QQ::OrderBy(
            QQN::Sorter()->Order)
        ));

        // Sortable
        $this->dlgSorter = new \QCubed\Project\Jqui\Sortable($this);
        $this->dlgSorter->AutoRenderChildren = true;
        $this->dlgSorter->CssClass = 'sortable';
        $this->dlgSorter->Items = 'div.item';

        foreach ($objSorterArray as $objSorter) {
            $pnl = new MyPanel($this->dlgSorter);
            $pnl->Text = $objSorter->Title;
            $pnl->CssClass = 'item';
            $pnl->Id = $objSorter->Id;
        }
        $this->dlgSorter->addAction(new \QCubed\Jqui\Event\SortableStop(), new \QCubed\Action\Ajax('sortable_stop'));
    }

    public function sortable_stop($strFormId, $strControlId, $strParameter) {
        $arr = $this->dlgSorter->ItemArray;
        foreach ($arr as $order => $cids) {
            $cid = explode('_',  $cids);
            $id = end($cid);

            $objSorter = Sorter::load($id);
            $objSorter->setOrder($order);
            //$objSorter->Order = $order; //Same effect
            $objSorter->save();
        }
    }

}
SortForm::run('SortForm');
```
It would be nice to put this solution in a wiki. I find it difficult to write in English correctly. Maybe someone will take it? Still, to popularize QCubed!
