### ISSUE TITLE
Last Insert ID bug in codegenerated panel 

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1302]
After $panelObject->Save()  I can't get Last Insert ID , so i think is codegen bug. 
In edit_save.tpl.php
```
	public function Save() {
		$this->mct<?= $strPropertyName ?>->Save<?= $strPropertyName ?>();
	}
```
should be
```
	public function Save() {
		return $this->mct<?= $strPropertyName ?>->Save<?= $strPropertyName ?>();
	}
```
I am using version 3

**Comment by kukrik** [comment]
I could not repeat your mistake. What caused your problem? Can you get some code here?

**Comment by vmakre** [comment]
Many times when I make insert I need last insert ID from database especially for panels. This is codegen panel.
```
$this->pnlObject = new QcubedPanel($this);
$this->pnlObject->mctQcubedPanel->TextControl->Value = 'test';
$insertID = $this->pnlObject->Save() ;
```
$insertID will be always null without "return" in public function Save() .

**Comment by kukrik** [comment]
I have not yet solved a similar solution. And I can not recommend immediately. I've solved one small plugin, half the way is done, and I feel that with the other side I can come up with a similar solution. I can not talk wisely at this time.

@spekary and @matthiaz are definitely better able to talk.

**Comment by spekary** [comment]
It could be enhanced, but Save in the database only returns an id on an insert. I recommend this:

```
$this->pnlObject->Save();
$insertId = $this->pnlObject->mctQcubedPanel->Thingy->Id
```

**Comment by matthiaz** [comment]
I agree with Shannon, never count on save to return anything. Simply use
the ->Id parameter. That will always be set.

2018-05-11 0:41 GMT+02:00 Shannon <notifications@github.com>:

**Comment by vmakre** [comment]
Then why is it 
QcubedPanelEditPanelGen.class.php
```
	public function Save() {
		$this->mctQcubedPanel->SaveQcubedPanel();
             
	}
```
and  QcubedPanelConnetorGen.class.php
```
		/**
		 * This will save this object'sQcubedPanel instance,
		 * updating only the fields which have had a control created for it.
		 */
		public function SaveQcubedPanel() {
			try {
				$this->UpdateQcubedPanel();

				// Save the QcubedPanel object
				$id = $this->objQcubedPanel->Save();
				// Finally, update any ManyToManyReferences (if any)
			} catch (QCallerException $objExc) {
				$objExc->IncrementOffset();
				throw $objExc;
			}
			return $id;
		}
```
public function SaveQcubedPanel()   returns $id  , why returns $id  when we loose value on first function?

**Comment by matthiaz** [comment]
Probably legacy.

Returning Id was done way back in QCodo, and noone really bother to change
this yet?

2018-05-11 14:58 GMT+02:00 Vladimir Makreski <notifications@github.com>:

**Comment by spekary** [comment]
Legacy pretty much. Its hard to take out once its there. If you know a Save will cause an insert, then you get back an id. If you know its going to just update, you will get back null. If older code was relying on this behavior, it would have broken a lot of code.

**Comment by vmakre** [comment]
My thinking
```
public function Save() {
$id = $this->mctQcubedPanel->SaveQcubedPanel()
if (is_null($id)){
return true ; }
else { return $id ; }
}
```
or codegen
```

	public function Save() {
		$this->mct<?= $strPropertyName ?>->Save<?= $strPropertyName ?>();
               if (is_null($id)){
               return true ; }
              else { return $id ; }
	}
```

**Comment by spekary** [comment]
It could just return the id and you can test for null. The problem is that people may expect that it will return the id whether doing an update or save. It should be strongly documented that is not the case.

**Comment by matthiaz** [comment]
I wouldn't recommend it doing it this way

You are returning a mixed typed (sometimes boolean, sometimes int). I'd
rather have consistent return types.

That said: @Shannon, can we afford a breaking change? QCubed 4 is already
breaking... so let's just change the Save handler to return true on success
and false on failure?
Or... let it always return the id.



2018-05-11 16:05 GMT+02:00 Vladimir Makreski <notifications@github.com>:

**Comment by spekary** [comment]
I think always returning the id would be fine. However, its been a while since I have seen that code. I vaguely remember that in order to do this, there may be times when we would have to do an additional query of the database. Hmm, that doesn't make sense though. Anyway, as long as we don't have to do an additional query, I am fine with returning the id.

**Comment by shannon** [comment]
@matthiaz I think you may have pinged the wrong shannon there. I'm not familiar with this project.
