### ISSUE TITLE
Qcubed autocomplete problems inside IDE

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#1303]
I have struggling past time a lot with using autocomplete  inside IDE .
Problems starts when we use custom objects in our Form . Without phpDoc comments we cannot achieve dynamic object to autocomplete methods and properties. Using /** @var   */  above every property is a good solution for me , making code clean and readable.
So putting this in Form class is a good practice  
```
/** @var SomeEditPanel */  // This is class of $pnlMyPanel
    protected $pnlMyPanel;
/** @var QJqButton  */
   protected $btnSave;

protected function Form_Create() {
		parent::Form_Create();
            $this->pnlMyPanel = new SomeEditPanel($this);
            $this->btnSave = new QJqButton($this);
```
Now I can use autocomplete on $this->pnlMyPanel   and $this->btnSave  .
Problems came when I used Jetbrains phpStorm . I solved this with installing plugin "DynamicReturnTypePlugin" and using phpDoc comments as I described above.

**Comment by matthiaz** [comment]
We use Netbeans internally and use the same PHPDoc style documentation.
Works fine.

You say there is a problem inside the IDE, but I'm not sure what problem,
since you are mentioning it works with phpdoc?



2018-05-10 22:20 GMT+02:00 Vladimir Makreski <notifications@github.com>:

**Comment by kukrik** [comment]
The @matthiaz is right, the default PHPDoc works well.

**Comment by vmakre** [comment]
Problem is mostly with phpStorm and i solved with plugin and phpDoc  , I rejected Netbeans because constantly crashes on debugging .
