### ISSUE TITLE
Quick question about using Html :: renderTag

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1304]
@spekary, I have a difficult task, how to maximize the use of HTML :: renderTag options. I make a dynamic menu with a deep hierarchy, such as the example here:
```
<ul>
  <li id="1" class="open">
    <a href="#">Home</a>
    <ul>
      <li id="2" class="open">
        <a href="#">Organisation</a>
        <ul>
          <li id="3" class="closed">
            <a href="#">Contacts</a>
           </li>
        </ul>
      </li>
    </ul>
  </li>
  <li id="4" class="open">
  <a href="#">Board</a>
  <ul>
    <li id="5" class="open">
      <a href="#">Statutes</a>
      <ul>
        <li id="6" class="closed">
          <a href="#">Reporting</a>
         </li>
       </ul>
     </li>
   </ul>
 </li>
 <li id="7" class="closed">
    <a href="#">Projects</a>
  </li>
  <li id="8" class="closed">
     <a href="#">News</a>
  </li>
</ul>
```
The quick question is that either opportunities of class Html is limited or not? Or do I need to use a custom solution?

Thank you for the fast response!

**Comment by spekary** [comment]
I think there is a back step function somewhere in there.

See the HList control for dynamically creating ul and ol lists.

**Comment by kukrik** [comment]
This is not a topical issue, I close it...
