### ISSUE TITLE
Codegen not consistently stripping table prefix

### ISSUE THREAD

**Issue by axcsrs** [qcubed/qcubed#1306]
I'm using v3.1.0, and when I run a codegen, the generated model classes do not have the table prefix consistently removed from referenced classnames.  My tables all have a "R_" prefix, as in "R_PEOPLE". This occurs in:
1. PHPDoc comments for member object declarations
`/*`
`* @var RDepartments objFKAWARDSHOMEDEPTIDObject`
`*/`
`protected $objFKAWARDSHOMEDEPTIDObject;`

2. Early binding methods for member objects
`// Check for FKAWARDSHOMEDEPTIDObject Early Binding
$strAlias = $strAliasPrefix . 'FK_AWARDS_HOME_DEPT_ID__PK_DEPARTMENTS_ID';
$strAliasName = !empty($strColumnAliasArray[$strAlias]) ? $strColumnAliasArray[$strAlias] : $strAlias;
if (isset ($strColumns[$strAliasName])) {
	$objExpansionNode = (empty($objExpansionAliasArray['FK_AWARDS_HOME_DEPT_ID']) ? null : $objExpansionAliasArray['FK_AWARDS_HOME_DEPT_ID']);
	$objToReturn->objFKAWARDSHOMEDEPTIDObject = RDepartments::InstantiateDbRow($objDbRow, $strAliasPrefix . 'FK_AWARDS_HOME_DEPT_ID__', $objExpansionNode, null, $strColumnAliasArray, false, 'awardsasfkawardshomedept', $objToReturn);
}`

3. PHPDoc comments in Get/Set methods for member objects
`    /**`
`     * Sets the value of the RDepartments object referenced by strFkAwardsHomeDeptId `
`     * @param null|RDepartments $objFKAWARDSHOMEDEPTIDObject`
`     * @throws QCallerException`
`     * @return Awards`
`     */`

`/**`
`     * Gets the value of the RAwardAccountType object referenced by intFkAwardAccountTypeId `
`     * If the object is not loaded, will load the object (caching it) before returning it.`
`     * @throws QCallerException`
`     * @return RAwardAccountType`
`     */`

I've only looked in the generated model classes; not sure if it is occurring elsewhere.  I'm mainly concerned about the PHPDoc comments because my IDE uses them for code completion insights.  I'm not super familiar with the codegen templates, but if someone can tell me where to look, I can try to figure out the issue.

**Comment by spekary** [comment]
vendor/qcubed/framework/includes/codegen/templates/db_orm/class_gen/

But I am guessing this is a bug in StripPrefixFromTable in QDatabaseCodeGen. Make sure that is working for you first. Looks like there is some confusion around the underscore in the prefix.

**Comment by axcsrs** [comment]
I think this might be an artifact of the Oracle adapter and the fact that Oracle table names come over in all caps.  I changed StripPrefixFromTable, line 1175 in QDatabaseCodeGen.class.php to
`(strtolower(substr($strTableName, 0, $this->intStripTablePrefixLength - strlen($strTableName))) == strtolower($this->strStripTablePrefix)))`

and that fixed the issue.

**Comment by spekary** [comment]
Yes, you are correct, and that is the right thing to do. That is also why names are changed from snake case to camel case when turned into ORM objects. Some dbs are not case sensitive in their names, and so you cannot just rely on camel case in the db names.
