### ISSUE TITLE
Please give a little help or guidance advice on how to get the necessary items from the array

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1308]
This time I'm having trouble making a new plugin that how to get the necessary items from the array. Before you need a little introduction, what solution I need.
Easy test what I did and got the correct output:
```php
require('../qcubed.inc.php');
$objMenuArray = Menu::loadAll([\QCubed\Query\QQ::expand(QQN::menu()->Content)]);
//$nodes = array();
foreach ($objMenuArray as $objMenu) {
    $nodes[] = [
        'id' => $objMenu->getId(),
        'depth' => $objMenu->getDepth(),
        'left' => $objMenu->getLeft(),
        'right' => $objMenu->getRight(),
        'text' => $objMenu->Content->getMenuText()
    ];
}

echo '<pre>';
var_export($nodes);
echo '</pre>';
```
I got the correct output as follows:
```php
array (
  0 => 
  array (
    'id' => 1,
    'depth' => 0,
    'left' => 2,
    'right' => 7,
    'text' => 'Home',
  ),
  1 => 
  array (
    'id' => 2,
    'depth' => 1,
    'left' => 3,
    'right' => 4,
    'text' => 'Organisation',
  ),
  2 => 
  array (
    'id' => 3,
    'depth' => 1,
    'left' => 5,
    'right' => 6,
    'text' => 'Contacts',
  ),
  3 => 
and so on ...
```
To build a plug've done a lot of things, but there are still many things to do... Currently I can not find the right solution for how to get the data and put it in an array.
```php
protected function getControlHtml()
    {
        $this->getInnerHtml();
        foreach ($this->objChildControlArray as $objChildControl) {
            $this->objNodes[] = [
                'id' => $objChildControl->intId,
                'depth' => $objChildControl->intDepth,
                'left' => $objChildControl->intLeft,
                'right' => $objChildControl->intRight,
                'text' => $objChildControl->strText
            ];
        };
        $this->varExport($this->objNodes);
        //var_dump($this->objNodes);
        //$this->renderMenuTree([$this->objNodes]);
    }
```
I know it will not work if I check var_dump. This gives empty values: NULL NULL NULL ...

If I check with VarExport, I have all the necessary information I'm looking for. I'll show you a screenshot:
<img width="1280" alt="screen shot 2018-06-14 at 18 46 14" src="https://user-images.githubusercontent.com/2853034/41427965-4dd4c70a-7011-11e8-9454-022f5679c0ec.png">
When varExport was able to display the data, I watched its code:
```php
public function varExport($blnReturn = true)
    {
        if ($this->objForm) {
            $this->objForm = $this->objForm->FormId;
        }
        if ($this->objParentControl) {
            $this->objParentControl = $this->objParentControl->ControlId;
        }

        // In order to make the control exportable, we can't have circular references or things that are not exportable.
        // We use the sleep helper as an aid to deep exporting the object.

        $vars = get_object_vars($this);
        foreach ($vars as $key => $val) {
            $this->$key = self::sleepHelper($val);
        }

        return var_export($this, $blnReturn);
    }
```
I was looking for long time and i cant decent solution found. If a new solution is able to extract the necessary data and put it in the right array, then I thank you. As soon as I get the plugin ready, I want to make it available to you.

Any ideas and suggestions?

EDIT: If you need to clarify the questions, I will reply as soon as possible.

**Comment by matthiaz** [comment]
Are you trying to integrate a jquery plugin into a qcubed plugin?
Is it https://github.com/ilikenwf/nestedSortable that one? Or something
else?

Would you be willing to share your full project on github so we can have a
look?

2018-06-14 19:48 GMT+02:00 Tiit Papp <notifications@github.com>:

**Comment by kukrik** [comment]
I've upgraded the nestedSortable repository: https://github.com/kukrik/nestedsortable.
You can also pull with composer: https://packagist.org/packages/kukrik/nestedsortable.

I will wait for your good thoughts and suggestions. Thanks in advance!

**Comment by kukrik** [comment]
PS. I forgot to warn that my one patch is not merged. Then errors can be displayed: https://github.com/qcubed/application/pull/17

**Comment by kukrik** [comment]
The first step of problem is solved :). The NestedSortable menu works well.

When I started researching after post, I did one experiment:
```php
$vars = get_object_vars($this);
        $someArray = [
            'id' => $vars['intId'],
            'depth' => $vars['intDepth'],
            'left' => $vars['intLeft'],
            'right' => $vars['intRight'],
            'text' => $vars['strText']
        ];
        echo '<pre>';
        //var_dump($someArray);
        print_r($someArray);
        echo '</pre>';
        //$this->varExport($someArray);
```
After the test, I understood very well that my first chosen path was wrong. I took a new path and the next solution worked as expected.

You can pull and test this application. Any suggestions and thoughts are always welcome.

There are more things to do in the queue.

I'm waiting for your thoughts. 

Links: 
https://github.com/kukrik/nestedsortable
https://packagist.org/packages/kukrik/nestedsortable

**Comment by matthiaz** [comment]
Looks cool. I don't know if I would let Menu_Draw return an array. I like
to use objects to clearly define what needs to be passed.
But I guess that's ok, it's well documented.

Thanks for sharing!


2018-06-19 11:31 GMT+02:00 Tiit Papp <notifications@github.com>:

**Comment by kukrik** [comment]
Now I ask again the stupid question of how to get the highest value from a table in one column. I know that you can use QCubed\Query\QQ::maximum() ...

```php
$objMenuArray = Menu::queryArray(
     \QCubed\Query\QQ::all(),
     [
         \QCubed\Query\QQ::groupBy(QQN::menu()->Id),
         \QCubed\Query\QQ::maximum(QQN::menu()->Right, 'max')
     ]
);
foreach($objMenuArray as $objMenu) {
     _p ('<p>' . $objMenu->getVirtualAttribute('max') . '</p>', false);
}
```
I do not need an array, but how to get one of the greatest value. How to do it?

**Comment by spekary** [comment]
First, make sure you aggregate on what you want to get the max out of. So doing a groupby on the id is bad, because every group will only have 1 item in it. But, some databases force you to use an aggregate function, making it tricky to get the max of everything. But this might work for you:

```
$objMenu = Menu::querySingle(
     \QCubed\Query\QQ::all(),
     [
         \QCubed\Query\QQ::maximum(QQN::menu()->Right, 'max')
     ]
);
_p ('<p>' . $objMenu->getVirtualAttribute('max') . '</p>', false);
```

**Comment by kukrik** [comment]
To @spekary, thank you! That was the right solution.

**Comment by kukrik** [comment]
Good @spekary, @vaibhav-kaushal, @matthiaz and others...
I have made much progress with the development of NestedSortable, but there are still some issues that I ask for your help and good suggestions or tips.

I wanted a solution that if we add a new item to the menu, after the recording, the new entry will automatically be added to the end of the menu.

I found a similar solution with "Datagrid with Inline Editing" http://localhost/qcubed-4/vendor/qcubed/application/assets/php/examples/dynamic/inline_editing.php.

I opted to use formPreRender() function. This example has only one specific class of DataGrid:
```php 
$this->dtgPersons = new DataGrid($this);
........................
........................
```
```php
protected function formPreRender()
     {
      // we make the call to refresh() in formPreRender
         $ this->dtgPersons->refresh();
         ........................
         ........................
     }
```
```php
protected function dtgPersons_Bind()
    {
        ........................
        ........................ 
        // If we are editing someone new, we need to add a new (blank) person to the data source
        if ($this->intEditPersonId == -1) {
            array_push($objPersonArray, new Person());
        }

        // Bind the datasource to the datagrid
        $this->dtgPersons->DataSource = $objPersonArray;
    }
```

I have a different problem that MenuPanel class and NestedSortable class works together:
```php
$this->tblSorterTable = new NestedSortable($this);
..........
..........

$this->pnl = new MenuPanel($this->tblSorterTable);
..........
..........
```
```php
protected function formPreRender()
    {
        //$this->tblSorterTable->refresh(); // It does not fit here because it only refreshed NestedSortable...
        $this->pnl->refresh(); // This should refresh MenuPanel because it draws a menu. But it works wrong...
..........
..........       
    }
```
```php
protected function Menu_Bind()
    {
        $objMenuArray = $this->pnl->DataSource = Menu::loadAll(
            \QCubed\Query\QQ::Clause(\QCubed\Query\QQ::OrderBy(QQN::menu()->Left),
                \QCubed\Query\QQ::expand(QQN::menu()->Content)
            ));

        if ($this->intEditMenuId == -1) {
            array_push($objMenuArray, new Menu);

            $this->pnl->DataSource = $objMenuArray;
        }
    }
```
I have a bit difficult to describe, I did a screenshot. You better understand...

![menupanel_refreshing](https://user-images.githubusercontent.com/2853034/43293339-6c7825b0-9142-11e8-9f6c-65551fc86516.jpg)

I could not find the right answer how to redirect the changing data to MenuPanel.

You may have more experience and suggestions that you can share.

I've updated NestedSortable changes here: https://github.com/kukrik/nestedsortable

Menu.php is here: https://github.com/kukrik/nestedsortable/blob/master/examples/menu.php

Thank you!

**Comment by spekary** [comment]
Why is the parent control of the menu = the nested sortable? Only do that if the nested sortable also draws the menu. Please attach your form template.

**Comment by kukrik** [comment]
Thread closed, a solution has been found to this issue.
