### ISSUE TITLE
Quick question about using the Bootstrap Tooltip

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1309]
@spekary, because I need a Bootstrap Tooltip and I've been exploring a few options. I found this place from qchim.php. I understand the conflict, but it remains unclear to me how or what I have to do.

It's written there:
```php
/**
 * This file will make it so bootstrap javascript plays nicely with jquery ui. They have some name conflicts,
 * but bootstrap has a name resolution mechanism.
 *
 * After this file, to call the bootstrap versions, you would use:
 * .bootstrapButton()
 * .bootstrapTooltip()
 *
 * Rather than the built-in versions.
 *
 * The load sequence should be:
 * jquery ui
 * bootstrap
 * this file
 */
jQuery.fn.bootstrapButton = jQuery.fn.button.noConflict();
jQuery.fn.bootstrapTooltip = jQuery.fn.tooltip.noConflict();
```
Once again what do I have to do? Thanks for the quick advice!

**Comment by spekary** [comment]
Include it (I think it is already by our bootstrap js. Afterwards, instead of calling tooltip(), you call bootstrapTooltip(). 

When the bootstrap doc says do this:
```
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
```
do this instead:
```
$(function () {
  $('[data-toggle="tooltip"]').bootstrapTooltip()
})
```

Or, from php, you can do this on every control you want to tooltip:
```
$control.execControlCommand($control.ControlId, "bootstrapTooltip")
```

**Comment by kukrik** [comment]
@spekary, thank you for the quick answer! My thoughts went up and down, I almost got close to this result, but I got the final solution thanks to your advice.
