### ISSUE TITLE
Codegen DB model __blnDirty and __blnValid type definition problem

### ISSUE THREAD

**Issue by ironiq** [qcubed/qcubed#1310]
Hi!
I wanted to customize the model insert/update functions generated by codegenerator, but ran into a problem: the TableGen class defines the $__blnDirty and $__blnValid variables as private, but the functions that use and update these are defined as protected. If i customize the GetValueClause function (in the Table class that extends TableGen), the fields will not be updated because the __blnDirty is private in the TableGen. These variable are defined in includes/codegen/templates/db_orm/class_gen/protected_member_variables.tpl.php by commit 0ee77aa13f182de887f14b2ad25dc04a7470efe9

If i change the private to protected (and rerun the codegenerator), the customized GetValueClause() function works perfectly.

**Comment by kukrik** [comment]
I would like to know why you made such a proposal. What a problem is that you had to come up with such a solution.

It is interesting to know at least.

**Comment by ironiq** [comment]
I have a table where there is a field that is not displayed on the webpage but has to be updated based on another field in the given table. Also there is a "lastupdate" field, modified by the program. This field is also not shown on the page but has to be updated (i know this is not the best solution but the db structure is a bit strict). I had to change the GetValueClause() to fit these requirements and ran into this problem.

**Comment by kukrik** [comment]
Clear! Let's see what @spekary says! He is currently the main ideologist and architect...
