### ISSUE TITLE
Textarea value beginning with newline - first character gets removed (chrome, win10)

### ISSUE THREAD

**Issue by koopa** [qcubed/qcubed#1311]
When entering text starting with a newline and then saving, the first newline gets removed in chrome on Win10.

I tracked it down to this:
https://github.com/qcubed/qcubed/blob/f5bf0bc6b938df48c2b08a53f0a0c9642fcd76a7/includes/base_controls/QTextBoxBase.class.php#L248

When I added the following right afterwards, the newlines are preserved:
```php
$strText = str_replace('&NewLine;', '&#13;', $strText);
```

***How to reproduce:***
Enter "\n\n1" into a QTextBox in multiline mode
```

1
```
save and reload - content is now "\n1"
```
1
```
Can anyone confirm this?

**Comment by matthiaz** [comment]
The HtmlEntities function is basically a wrapper on to of the native `htmlentities`. So it doesn't actually do anything with newlines as far as I know

```
        public static function HtmlEntities($strText) {
            return htmlentities($strText, ENT_COMPAT | ENT_HTML5, QApplication::$EncodingType);
        }
```
