### ISSUE TITLE
Quick advice on how or what to do - the need to make a new feature or use ControlBase's existing capabilities

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1316]
I've been looking, but can't find the right idea. I describe the following problem.

I've built it like this:
```php
       $this->tblSorterTable = new NestedSortable($this);
       $this->tblSorterTable->...................;
       etc ......................................;

       $this->pnl = new MenuPanel($this->tblSorterTable);
       $this->pnl->......................';
       etc ...............................;
```
If I do this, I get the following quick result:
```php
      $this->btnStatus = new Button($this->tblSorterTable);
      $this->btnStatus ->Text = 'Disable';

      $this->btnEdit = new Button($this->tblSorterTable);
      $this->btnEdit ->Text = 'Edit';

      $this->btnDelete = new Button($this->tblSorterTable);
      $this->btnDelete ->Text = 'Delete';
```
<img width="1252" alt="Screenshot 2019-04-30 at 01 29 52" src="https://user-images.githubusercontent.com/2853034/56932347-0332d580-6aec-11e9-8961-d9ef1eadc237.png">

These buttons are drawn with a red circle.

If I do that, then nothing will be shown:
 
```php
      $this->btnStatus = new Button($this->pnl);
      $this->btnStatus ->Text = 'Disable';

      $this->btnEdit = new Button($this->pnl);
      $this->btnEdit ->Text = 'Edit';

      $this->btnDelete = new Button($this->pnl);
      $this->btnDelete ->Text = 'Delete';
```
I even know that there is a need to do some functions or to use ControlBase functions. But how or what to do? I need to move the green circle buttons there to place.

I am very grateful for any advice and suggestion, it would help me quickly.

**Comment by kukrik** [comment]
@spekary and @matthiaz, can you share the advice?

**Comment by kukrik** [comment]
Long silence! I'm still working and I'm still looking for a solution... I changed my logic a bit, but something is missing. I describe the solution and the problem.

I made new functions... 
    
```php
    public function createRenderButtons(callable $objCallable, $mixParams = null)
    {
        $this->callback = $objCallable;
        $this->mixParams = $mixParams;
    }
```
Here I understand that variable $item is not correct, there must be something else...
```php
    public function fetchCellObject($item)
    {
        if ($this->mixParams) {
            return call_user_func($this->callback, $item, $this->mixParams);
        } else {
            return call_user_func($this->callback, $item);
        }
    }
```
```php
    protected function getRenderCellHtml()
    {
        $cellValue = $this->fetchCellObject($this->item);

        if (is_object($cellValue)) {
            $cellValue = (string)$cellValue;
        }
        if ($cellValue === null) {
            return '';
        }
        if (is_object($cellValue)) {
            $cellValue = (string)$cellValue;
        }
        return $cellValue;
     }
```
Currently know that $item is empty...
Here I want to get $cellValue data, then I can put it around like this: `$strHtml .= $cellValue` or need to do foreach etc...

```php
 /*$strHtml = '<section class="menu-btn-body center-button">' . _nl( );

            $strHtml .= <button title="Disable" class="btn btn-white btn-xs" data-toggle="tooltip" data-value="..." >Disable</button>' . _nl();
            $strHtml .= '<button title="Edit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-value="..." ><i class="fa fa-pencil"></i></button>' . _nl();
            $strHtml .= '<button class="btn btn-danger btn-xs" data-toggle="tooltip" title="Delete" data-value="..."><i class="fa fa-trash"></i></button>' . _nl();
            $strHtml .= '</section>';

            return $strHtml; */
```
I get error: Argument 1 passed to SampleForm::Buttons_Draw() must be an instance of Menu, null given.

>Call Stack:

> #0 [internal function]: SampleForm->Buttons_Draw(NULL)
> #1 /.../qcubed-4/vendor/kukrik/nestedsortable/src/MenuPanelBase.php(262): call_user_func(Array, NULL)
> #2 /.../qcubed-4/vendor/kukrik/nestedsortable/src/MenuPanelBase.php(359): QCubed\Plugin\MenuPanelBase->fetchCellObject(NULL)
> #3 /.../qcubed-4/vendor/kukrik/nestedsortable/src/MenuPanelBase.php(341): QCubed\Plugin\MenuPanelBase->getRenderCellHtml()

I have menu.php done like this:
```php
        $this->pnl = new Q\Plugin\MenuPanel($this->tblSorterTable);
        $this->pnl->TagName = 'ul';
        $this->pnl->setDataBinder('Menu_Bind');
        $this->pnl->setNodeParamsCallback([$this, 'Menu_Draw']);
        $this->pnl->createRenderButtons([$this, 'Buttons_Draw']);
```

```php
    public function Buttons_Draw(Menu $objMenu)
    {
        $objControlId = "statusButton" . $objMenu->Content->IsEnabled;

        $this->btnStatus = new Q\Plugin\Button($this->pnl, $objControlId);
        $this->btnStatus->Tip = true;
        $this->btnStatus->setDataAttribute('toggle', 'tooltip');
        $this->btnStatus->addAction(new Q\Event\Click(), new Q\Action\Ajax('btnStatus_Click'));

        if ($objMenu->Content->IsEnabled == 1) {
            $this->btnStatus->Text = t('Disable');
            $this->btnStatus->ToolTip = t('Disable');
            $this->btnStatus->removeCssClass('btn btn-success btn-xs');
            $this->btnStatus->addCssClass('btn btn-white btn-xs');
        } else {
            $this->btnStatus->Text = t('Enable');
            $this->btnStatus->ToolTip = t('Enable');
            $this->btnStatus->removeCssClass('btn btn-white btn-xs');
            $this->btnStatus->addCssClass('btn btn-success btn-xs');
        }

        // Later work
        $this->btnEdit = new Q\Plugin\Button($this->pnl);
        $this->btnEdit ->Text = 'Edit';

        $this->btnDelete = new Q\Plugin\Button($this->pnl);
        $this->btnDelete ->Text = 'Delete';
    }
```
The question here is how I have to do to fetch 'Draw_Buttons' data? 

Please your quick suggestion or tips on what to do. I am infinitely grateful if you find a quick time to make suggestions!

**Comment by matthiaz** [comment]
I think you need call_user_func_array in stead of call_user_func

**Comment by kukrik** [comment]
@matthiaz, Thank you for your quick opinion! I think it's not quite right. Maybe I'm not right?

Some ideas have been taken over by TableBase. The sure thing is that I have not fully understood... I use a lot of var_dump() to better understand.
This var_dump indicates that these buttons are partially available:
```
.......
'btnStatus' => NULL,
'btnDelete' => NULL,
'btnEdit' => NULL,
.....
```
But the available button should show about so:
```
...........
)),
'btnStatus' => 
  QCubed\Plugin\Button::__set_state(array(
     'strGlyph' => NULL,
     'blnTip' => false,
     'strButtonStyle' => 'btn-primary',
     'strCssClass' => 'btn btn-default',
     'strButtonSize' => '',
     'blnPrimaryButton' => true,
     'blnActionsMustTerminate' => true,
     'strTagName' => 'button',
     'mixCausesValidation' => true,
     'strText' => 'Disable',
     'strFormat' => NULL,
     'strTemplate' => NULL,
     'blnAutoRenderChildren' => false,
     'blnHtmlEntities' => true,
     ...... etc.....
```

@spekary 's probably very quick with his big project (goradd and stuff) and he doesn't have time. He has written around Tablebase, after DataGrid. She will certainly understand very well and will definitely be able to give good advice. But, unfortunately, he does not have time :(.

But I will start again and make it clear to myself. If you have good thoughts, let us know!

**Comment by matthiaz** [comment]
Tip: read up on using a php debug profiler. Like: xdebug.

This will help you find how your code works without var_dump

**Comment by kukrik** [comment]
Thread closed
