### ISSUE TITLE
I ask for your help to solve the last probleem of NestedSortable plugin

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1318]
I have solved many problems while developing the plugin but there is one more problem left to solve. Let me give you an overview of the problem. 

First thing, I solved two functions separately, if to apply functions separately 
createNodeParams([$this, 'Menu_Draw']) and createRenderButtons([$this, 'Buttons_Draw']), then they work properly apart. 

First screenshot is here, if I hide function in menu.php createRenderButtons([$this, 'Buttons_Draw']), then the menu shows the menu tree correctly and it is possible to  order and change menu and items of the menu. 

```php
        $this->pnl = new Q\Plugin\MenuPanel($this->tblSorterTable);
        $this->pnl->TagName = 'ul';
        $this->pnl->setDataBinder('Menu_Bind');
        $this->pnl->createNodeParams([$this, 'Menu_Draw']);
        //$this->pnl->createRenderButtons([$this, 'Buttons_Draw']);
        $this->pnl->SectionClass = 'menu-btn-body center-button';
```
<img width="1277" alt="Screenshot 2019-12-29 at 21 35 03" src="https://user-images.githubusercontent.com/2853034/71562632-bbee5180-2a8b-11ea-85d5-05772d6c2c18.png">

The second screenshot is here, if i hide the function createNodeParams([$this, 'Menu_Draw']), in menu.php then of course it is not possible to see the menu and it shows the buttons correctly „Enable“ or „Disable“, „Edit“ and „Delete“. Something was needed...

```php
        $this->pnl = new Q\Plugin\MenuPanel($this->tblSorterTable);
        $this->pnl->TagName = 'ul';
        $this->pnl->setDataBinder('Menu_Bind');
        //$this->pnl->createNodeParams([$this, 'Menu_Draw']);
        $this->pnl->createRenderButtons([$this, 'Buttons_Draw']);
        $this->pnl->SectionClass = 'menu-btn-body center-button';
```
<img width="1277" alt="Screenshot 2019-12-29 at 21 35 38" src="https://user-images.githubusercontent.com/2853034/71562634-c7417d00-2a8b-11ea-84a6-ab06eae95006.png">

Third screenshot is here, if i show both versions in menu.php, then it throws and error:

```php
        $this->pnl = new Q\Plugin\MenuPanel($this->tblSorterTable);
        $this->pnl->TagName = 'ul';
        $this->pnl->setDataBinder('Menu_Bind');
        $this->pnl->createNodeParams([$this, 'Menu_Draw']);
        $this->pnl->createRenderButtons([$this, 'Buttons_Draw']);
        $this->pnl->SectionClass = 'menu-btn-body center-button';
```
 
`Array to string conversion `

and this line shows: 
```php
Line 303: $strHtml .= $values;
```

<img width="1268" alt="Screenshot 2019-12-29 at 21 37 01" src="https://user-images.githubusercontent.com/2853034/71562636-d3c5d580-2a8b-11ea-8658-4ec2164bffbe.png">

I can’t think clearly and understand, where I went wrong. You are surely helpful and willing to help me with your experience and knowledge. Please check the code of **MenuPanelBase.php** and notice if you see any mistakes there. All comments are welcome. It’s even more helpful if you have any soluyions. I will try everything to ovrcome the last hurdle. 

I renewed the plugin https://github.com/kukrik/nestedsortable. 

It’s even better to download with composer with the following command:

`composer require kukrik/nestedsortable`

PS. Who has downloaded my plugin before, I recommend to renew database because I have edited the tables a bit: https://github.com/kukrik/nestedsortable/tree/master/database.

Thanks in advance!

**Comment by matthiaz** [comment]
Looks like you are passing an array to the function, so $values is an
array, not a string.

See:
https://github.com/kukrik/nestedsortable/blob/master/src/MenuPanelBase.php#L256

To be honest, I would just remove line 303
https://github.com/kukrik/nestedsortable/blob/master/src/MenuPanelBase.php#L303

I don't see what use it has? $values is maybe the wrong name. You are
passing a list of attributes.

**Comment by kukrik** [comment]
At the moment, I understand that arrays and strings do not work together.
The fact is that in the MenuPanel class, two functions output different contents: the function getItemRaw ($ objItem) gives an array, the function getObjectDraw($objItem) gives strings.

I already know that the function renderMenuTree($arrParams) code is locked and is only array oriented.

At this point, you need to think about how to slightly modify the function renderMenuTree($arrParams) so that the array and strings work separately.

Right now I'm figuring out how to make a loop independently of each other. Two foreach or for or while or whatever?

These problematic places (comments with slashes and asterisks ) must be removed from the first foreach and placed in the second foreach.


```php
protected function renderMenuTree($arrParams)
    {
        $strHtml = '';
        foreach ($arrParams as $arrParam) {

            if ($this->nodeParamsCallback) {
                $this->intId = $arrParam['id'];
                $this->intParentId = $arrParam['parent_id'];
                $this->intDepth = $arrParam['depth'];
                $this->intLeft = $arrParam['left'];
                $this->intRight = $arrParam['right'];
                $this->strMenuText = $arrParam['text'];
                $this->intStatus = $arrParam['status'];
            }
            $strRenderCellHtml = $this->getRenderCellHtml($arrParam); //**The place you need to take out of the loop and put it in another loop...**

            if ($this->intDepth == $this->intCurrentDepth) {
                if ($this->intCounter > 0)
                    $strHtml .= '</li>';
            } elseif ($this->intDepth > $this->intCurrentDepth) {
                $strHtml .= '<' . $this->strTagName . '>';
                $this->intCurrentDepth = $this->intCurrentDepth + ($this->intDepth - $this->intCurrentDepth);
            } elseif ($this->intDepth < $this->intCurrentDepth) {
                $strHtml .= str_repeat('</li>' . '</' . $this->strTagName . '>', $this->intCurrentDepth - $this->intDepth) . '</li>';
                $this->intCurrentDepth = $this->intCurrentDepth - ($this->intCurrentDepth - $this->intDepth);
            }
            $strHtml .= _nl() . '<li id="' . $this->strControlId . '_' . $this->intId . '"';
            if ($this->intLeft + 1 == $this->intRight) {
                $strHtml .= ' class="mjs-nestedSortable-leaf"';
            } else {
                $strHtml .= ' class="mjs-nestedSortable-expanded"';
            }
            $strHtml .= '>';

            $strCheckStatus = $this->intStatus == 1 ? 'enabled' : 'disabled';
            $strHtml .= <<<TMPL

    <div class="menu-row $strCheckStatus">
        <span class="reorder"><i class="fa fa-bars"></i></span>
        <span class="disclose"><span></span></span>
        <section class="menu-body">{$this->strMenuText}</section>
        $strRenderCellHtml //**The place you need to take out of the loop and put it in another loop...**
    </div>

TMPL;
            ++$this->intCounter;
        }
        $strHtml .= str_repeat('</li>' . '</' . $this->strTagName . '>', $this->intDepth) . '</li>';

        return $strHtml;
    }
```

But how? Do you have any better ideas?

**Comment by kukrik** [comment]
Good @matthiaz!

I know and say it is necessary, if both functions work separately, this or the other function works. I already wrote a previous post. The problem is function renderMenuTree($arrParams) with the closed code.

Today I finally understood how Qcubed TableBase and a subclasses work. All cells (between `<td> </td>` tags) work independently.

My renderMenuTree is not easy to work with because it has to consider parameters like `id, parent_id, depth, left and right`. renderMenuTree draws the menu tree correctly. That's why the code is locked.

At this point, we need to look at this function and make it possible for buttons to appear, but then the array and strings are separated.

Will you help me with this question?

**Comment by kukrik** [comment]
I thought the` getItemRaw($objItem)` and `getObjectDraw($objItem)` functions give different content. Please see the attachment!

Perhaps there is another way to modify the `getObjectDraw($objItem)` function and add one to convert the content output `$mixButtons` into an array. But I have no experience!

You have good thoughts?

[Var-Dump-Array.pdf](https://github.com/qcubed/qcubed/files/4010951/Var-Dump-Array.pdf)

**Comment by matthiaz** [comment]
Sorry, I don't understand the question :|

Please clarify clearly what you want to achieve.

**Comment by kukrik** [comment]
I've solved this problem a long time ago and I'm moving on... By now, about 75% of the nestedSortable class has been solved, there are still a couple of issues to solve. Next, I will make a new topic, before I have to understand for myself what the problems are, I can explain and ask for specific help.
