### ISSUE TITLE
A quick question about getting a Bootstrap Navbar ID

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1319]
I tried and researched for several days, but I couldn't find the right solution to get the clicked ID from the database.

I will briefly describe what is the problem. First of all I found a normal solution, I put a screenshot here. It's fine. But I couldn't find the right solution to get the ID I wanted. Code below:

<img width="1261" alt="Screenshot 2020-03-16 at 15 16 53" src="https://user-images.githubusercontent.com/2853034/76914787-04b3ea80-68c4-11ea-8706-da426ed45421.png">

```php
protected function sideMenu_Create()
    {
        $objMenuArray = Menu::loadAll(
            Q\Query\QQ::Clause(Q\Query\QQ::OrderBy(QQN::menu()->Left),
                Q\Query\QQ::expand(QQN::menu()->MenuContent)
            ));
        $this->sideMenu = new Bs\Navbar($this);
        $url = 'menu_examples.php';
        $this->sideMenu->HeaderText = Html::renderTag("img",
            ["class" => "logo", "src" => QCUBED_IMAGE_URL . "/qcubed_logo_footer.png", "alt" => "Logo"], null, true);
        $this->sideMenu->HeaderAnchor = $url;
        $this->sideMenu->StyleClass = Bs\Bootstrap::NAVBAR_INVERSE;
        //$this->sideMenu->addAction(new Q\Event\Click(), new Q\Action\Ajax('SubMenuList_Click'));

        $this->tblBar = new Bs\NavbarList($this->sideMenu);
        foreach ($objMenuArray as $objMenu) {
            if (!$objMenu->MenuContent->IsEnabled == 0) {
                if ($objMenu->ParentId == null && $objMenu->Right == $objMenu->Left + 1) {
                    $this->objListMenu = new Bs\NavbarItem($objMenu->MenuContent->MenuText, null, '#'
                    /*$objMenu->MenuContent->RedirectUrl*/); //Temporarily disabled $RedirectUrl for testing
                    $this->tblBar->addMenuItem($this->objListMenu);
                    $this->tblBar->ActionParameter = $objMenu->Id;
                    $this->tblBar->addAction(new Q\Event\Click(), new Q\Action\Ajax('SubMenuList_Click'));
                    print $this->tblBar->ActionParameter . "\n";
                } elseif (!in_array($objMenu->ParentId, $this->ControllableValues($objMenuArray, 'Id')) &&
                    $objMenu->Right !== $objMenu->Left + 1) {
                    $this->objListSubMenu = new Bs\NavbarDropdown($objMenu->MenuContent->MenuText);
                    $this->tblBar->addMenuItem($this->objListSubMenu);
                    //$this->tblBar->ActionParameter = $objMenu->Id;
                    //$this->tblBar->addAction(new Q\Event\Click(), new Q\Action\Ajax('SubMenuList_Click'));
                    //print $this->tblBar->ActionParameter . "\n";
                }
            }
        }
    }
```
I needed to get an ID so that I could work on the data from the database using that ID.

I liked to use this solution to get this ID: 

```php
...............................................
$this->tblBar->ActionParameter = $objMenu->Id;
$this->tblBar->addAction(new Q\Event\Click(), new Q\Action\Ajax('SubMenuList_Click'));
..............................................
```
Even it shows the desired ID: `print $this->tblBar->ActionParameter . "\n";`
But this `$intMenuId = intval ($ params-> ActionParameter); ` does not fetch the desired ID.

 ```php
   protected function SubMenuList_Click(ActionParams $params)
    {
        $intMenuId = intval($params->ActionParameter);
        //$intMenuId = $this->sideMenu->Value; // Or SelectedId
        $objMenuArray = Menu::loadAll();

        $strTempArray = [];
        foreach ($objMenuArray as $objMenu) {
            if ($intMenuId == $objMenu->Id) {
                $strTempArray[] = $objMenu->ParentId;
            }
        }
        // Unfinished code...
        // Before step by step with each condition check,
        // then the following code finish...

        //$test = implode(',', $strTempArray);
        Application::displayAlert($intMenuId);

    }
```
I understand that there is a problem, but I cannot find another solution.

If enabled: `$intMenuId = $this->sideMenu->Value; // Or SelectedId` It will issue to me like `c6_0` or `c6_1` or `c6_2` and so on... 

I also understand that data is not visibly be issued from the database for security reasons. This is also the right approach.

Here's the next question, so please share your experience or knowledge on how to get the ID you want.

I would appreciate any quick help!

**Comment by spekary** [comment]
You cannot use tblBar->ActionParameter. You are changing it every time you make a menu. What you should do instead is something like:

new Q\Action\Ajax('SubMenuList_Click').ActionParameter(Javascript::Var("ui.id"));

You need to have the action set the parameter based on Javascript that gets the id from the menu item that was clicked. I am sorry, its been a while since I worked on that code, so its not exactly that, but something like that.

**Comment by kukrik** [comment]
Hi @spekary! I haven't heard from you in a long time. Thank you for taking a moment to answer here.

I have to say right away that your solution was too interesting and non-standard. I didn't believe it, but I tried it. They are not suitable because there are no such classes in the QCubed core.

But I didn't give up and searched. Your Bootstrap class has one option, which is `\Event\NavbarSelect()`. It worked fine. I'll put this snippet of code here:
```php
$this->sideMenu->addAction(new Bs\Event\NavbarSelect(), new Q\Action\Ajax('SubMenuList_Click'));`
```
It was now necessary to activate the NavbarItem null value:
```php
$this->objListMenu = new Bs\NavbarItem($objMenu->MenuContent->MenuText, null, '#'); 
```
to
```php
$this->objListMenu = new Bs\NavbarItem($objMenu->MenuContent->MenuText, $objMenu->Id, '#');
```
Before it was: (these are not data-values)
```php
<span id="c6_ctl">
          <ul class="nav navbar-nav" id="c6">
            <li id="c6_0">
              <a href="#">Home</a>
            </li>
            <li id="c6_1" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Organisation <span class="caret"></span></a>
            </li>
            <li id="c6_2">
              <a href="#">News</a>
            </li>
            ..................
            ...................
            ...................
          </ul>
        </span>
```
After that it was: (these data-value now exist)
```php
<span id="c6_ctl">
          <ul class="nav navbar-nav" id="c6">
            <li id="c6_0" data-value="1">
              <a href="#">Home</a>
            </li>
            <li id="c6_1" data-value="2" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Organisation <span class="caret"></span></a>
            </li>
            <li id="c6_2" data-value="8">
              <a href="#">News</a>
            </li>
           ...................
           ...................
           ...................
          </ul>
        </span>
```
Now the question remains that how to get the ID value and I found a solution, it works fine.

```php
protected function SubMenuList_Click(ActionParams $params)
{
      $intMenuId = $params->ActionParameter['value'];
      //$intMenuId = $this->sideMenu->SelectedId; // or Value
       
      Application::displayAlert($intMenuId);
}
```
I suggest one idea that one option could be added to the NavBar class. We have this SelectedId or Value. Could add a new option, SelectedValue.

I suggest now, but I couldn't think and find the right solution...

```php
protected $intSelectedValue;
//or
protected $strSelectedValue; 

case "SelectedValue":
                return $this->intSelectedValue;
//or
case "SelectedValue":
                return $this->strSelectedValue;

```
I couldn't think of a setter, I don't have enough experience. This snippet should allow you to derive:

Should include here like `ActionParams $params` and `$params->ActionParameter ['value']`

Following is a good idea to fetch data like a fast coding:
```php
$intMenuId = $ this->sideMenu->SelectedValue;`
```
To start with, I put the unfinished SET code part:
```php
case "SelectedValue":   // Internal only. Do not use.
                try {
		     ????????????????????
                    $this->intSelectedValue = Type::cast($mixValue, Type::INTEGER);
                    // or
                    $this->strSelectedValue = Type::cast($mixValue, Type::STRING);
                     ????????????????????
                    break;
                } catch (InvalidCast $objExc) {
                    $objExc->incrementOffset();
                    throw $objExc;
                }
```
I am ready to test and report the proposed solution. Then the Navbar class can be upgraded.

Any thoughts?

**Comment by spekary** [comment]
Since it could be either, I would not cast it. Let it be just selectedValue. But honestly, I think you should fork qcubed and make your own version. I don't think anyone is supporting it at this point.

I am continuing to work on the goradd framework, which is a Go version of QCubed. I have a number of projects working now based on it. Its extremely fast, since its compiled, and it catches many errors during compilation. Also, typical compiled executables are only around 50MB in size, so very quick and easy to deploy. There are lots more advantages. I need to work on the documentation still. Some of the examples pages are done though, and there are quick start instructions that get you to a working website quickly just like QCubed.

**Comment by kukrik** [comment]
@spekary I understand you. Let's leave it as I found the working code. I have to finish this project.

Yeah, well, but I like QCubed and the code generator, Orm and the like. Well, it has its strengths and weaknesses.

I had long been following the development of your GO. This is your great frantic job. GO is an unknown language to me, I've read a bit. Your talk made me excited and curious. I have to get to know it soon.  But I need to get to know the GO language a little bit.

**Comment by spekary** [comment]
Goradd is very similary to QCubed. It has code generation for the ORM and the Forms. Code generation is even a part of the Go language. Goradd has a bootstrap library too.

You can learn Go here: https://tour.golang.org/
