### ISSUE TITLE
Composer problem, need to be solved quickly

### ISSUE THREAD

**Issue by kukrik** [qcubed/qcubed#1326]
Since I regularly update the composer dependencies, today I could not download one of the plugins, there is a warning:
*******************************************
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - qcubed/composer is locked to version dev-qcubed4 and an update of this package was not requested.
    - qcubed/composer dev-qcubed4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - qcubed/composer dev-qcubed4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - qcubed/application dev-master requires qcubed/composer dev-qcubed4 -> satisfiable by qcubed/composer[dev-qcubed4].
    - qcubed/application is locked to version dev-master and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
*******************************************
I don't have access to specify a minimum version of Composer (or currently "qcubed/composer": "^ 1.0.5"), at least in QCubed v4. Currently, Composer is version 2.0.8.

Good friends @spekary and @matthiaz, you have access to the upgrade. Probably need to upgrade in a few places "qcubed/composer": "something about 2.0. *" ... 

It shouldn't be very time consuming, for sure.

Thank you in advance!
Tiit / kukrik

**Comment by matthiaz** [comment]
Check again, should be ok now.
