### ISSUE TITLE
Update Checker

### ISSUE THREAD

**Issue by scottux** [qcubed/qcubed#165]
/assets/_core/php/_devtools/update_checker.php

It is supposed to check for new versions of QCubed and make it easy to update the core framework as well as plugins. I think it just links to a few old plugins.

It really needs to be reworked, but I don't know much about how it is working or how we could go about making it easy to check diffs from github against an installation. It may be as easy as checking the version installed against the version on examples...but then can we just link to the latest on github, list github pull commands for the user, or actually update the installation? Ideas?

**Comment by vaibhav-kaushal** [comment]
I think namespacing is being discussed in another thread. We might be able to close this. 

About the original update checker script, we can have one file/address on the github page (with a URL like: http://qcubed.github.io/version.txt). The script might just be able to fetch the data in that file and compare it with the current installation's version!

If a new update is detected, we can tell the user how to get it and what things to keep an eye on.
