### ISSUE TITLE
template bundles

### ISSUE THREAD

**Issue by vakopian** [qcubed/qcubed#205]
As discussed in #132, we should have the ability to handle multiple template bundles. The installation wizard can show the list of available bundles, and the developer can pick one or more bundle to codegen.

To avoid conflicts between bundles I think we should start using php namespaces.
Also, as with plugins, I think template bundles should be installed through composer.

**Comment by spekary** [comment]
This is done, though its not as automated as desired. You have to hand-edit the QCodeGen.class.php file. There is a comment there that shows you what to do.
