### ISSUE TITLE
qcu.be website unused but doesn't redirect to github

### ISSUE THREAD

**Issue by matthiaz** [qcubed/qcubed#411]
Is the qcu.be website still used? I doesn't look like it is since the forum is mostly inactive, trac is nolonger used, etc... 

It would be great to have a nice web 2.0 marketing page on qcu.be (not that I'm volunteering, I suck at design). But in the meanwhile we might want to consider simply redirecting it to github where all the action is.

**Comment by vaibhav-kaushal** [comment]
Moved to GitHub. Closing.
