### ISSUE TITLE
qcu.be examples page broken

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#434]
Get message:

Comments starting with '#' are deprecated in /etc/php5/apache2/conf.d/mcrypt.ini on line 1

**Comment by vaibhav-kaushal** [comment]
Is this completed? 
Also, should be move our examples server some other place? 

I tried to open qcu.be and it seems to be down completely.

**Comment by kukrik** [comment]
@vaibhav-kaushal , following your signal, I also saw that the site is down :(. Bad publicity for us, so can not be...

**Comment by olegabr** [comment]
@spekary have updated the OS on the server and it becomes inaccessible. waiting for @spekary to have time to fix it. This update was required because PHP version was outdated (5.3). The qcubed 3.0 is targeted on the 5.4 at minimum.

**Comment by vaibhav-kaushal** [comment]
Should we move it to another server? I have one which keeps running. I can use that one, if everyone is okay with it.

**Comment by vaibhav-kaushal** [comment]
Or we can ask Linode or DigitalOcean if they are ready to donate one. They do (at least DigitalOcean does) that for some open source projects already.

**Comment by spekary** [comment]
This one is the same as the others. Working on it.

**Comment by vaibhav-kaushal** [comment]
http://qcu.be/examples/ is the new URL and it works well for now. We can always create a new issue if it re-surfaces.
