### ISSUE TITLE
don’t use @import

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#451]
The article: http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

It's main point: use `<link>` enstead of `<style>@import`

qcubed uses `<style>@import` now. Is there some strong opinions to not change it to `<link>`?
I'm going to do that for my own project now to guaranty the style application order in all browsers. It is not the same right now with current qcubed scheme.

**Comment by spekary** [comment]
This has been fixed. In order to not use an @import, the css has to be included in the header. You can call 
```<?php $this->RenderStyles() ?>```
 in your form template in the head tag to do this. If you don't do it, the styles will be rendered with @import.

**Comment by spekary** [comment]
Actually, I am going to reopen this so that the default form templates do this.

**Comment by spekary** [comment]
This is fixed in 4.0 in the header.inc.php file that is installed
