### ISSUE TITLE
Protect Qcubed libraries from public access in hosting service

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#516]
I am making some tests on hosting service platform , putting project assets in public_html but i want vendor/qcubed/....     to protect from  public access but i have a problem. When i am loading page there are some js and css files needed from vendor qcubed libraries, but this path is out of public_html and there is no relative path that can point to theese files. Relative root  is pointing to public_html  I know that i can simple copy qcubed in public_html but is this possible without doing this?. Second solution is to copy qcubed assets to project assets but i am asking for best practices instead of manually moving files . Or is there possibility to put something like '../../assets/qcubed.js'  in document header to one folder upper from public_html ?

**Comment by spekary** [comment]
Again, part of creating a solution for deployment. Some good ideas above. Moving to 3.2

**Comment by matthiaz** [comment]
solved in qcubed 4 IIRC
