### ISSUE TITLE
New qcu.be web page

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#558]
Hi all. I have blank platform (wordpress) site for new qcubed web site. 
I am collecting materials (there are a lot of them) but there is a lot of job  , as all old sites were total disaster with fragmented informations. 
What is done 
1. Template
2. Blog page (blank)
3. documentation and navigation with versioning ( ver 2  and new ver 3) , do we need two versions now or we will work only on version 2 ??  (blank).  There is a lot of work to do but most important part is docs. 
4. Examples are working in iframe 

What to do
1. Api documentation generator https://github.com/FriendsOfPHP/Sami  this is good api doc generator (laravel uses it) , can someone help in this?
2. Screecasts on old http://qcu.be/content/video-screencasts   , hard to make a new ones  ?. Better to put them on youtube and link .
3. Tutorials (i can get them from old posts ) .
@vaibhav-kaushal can you share informations and content from qcubed.in ? 
If some people interesting in help i can put web site online .
@spekary  i have backup from old vps server . But we won't  upgrade OS now  i need old site live for easy content download.

**Comment by vaibhav-kaushal** [comment]
We have redirected qcu.be to github.
