### ISSUE TITLE
Change the effect of QGridLines?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#561]
QGridLines in QDataGridBase is used to create the 'rules' attribute for the 'table' tag which is presented on the page. However rules attribute has been removed from HTML5.  Should we switch to the newer 'column-rule' CSS property instead?

**Comment by spekary** [comment]
See #577

**Comment by spekary** [comment]
This is done. Table grid lines should be styled with CSS. You can do that programmatically using the QHtmlAttributeBase class which is the base of all QControls.
