### ISSUE TITLE
Error in Informix DB handling code

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#570]
In this line: https://github.com/qcubed/framework/blob/alpha-3.0/includes/database/QInformixPdoDatabase.class.php#L576

The exception class used is an abstract one! What should be done about it? 

Also, on this line: https://github.com/qcubed/framework/blob/alpha-3.0/includes/database/QInformixPdoDatabase.class.php#L528 and for the next two lines, the variables $strColumnNameArray, $strReferenceTableName and $strReferenceColumnNameArray are not declared inside the function/method (and are out of scope). 

These errors were reported by PhpStorm. I suspect there might be a few others.

**Comment by olegabr** [comment]
@vaibhav-kaushal there are no active informix qcubed users now, I believe. Fix these issues in some way. If you'll made a mistake, it can be addressed later when someone opens an issue against that.
