### ISSUE TITLE
Refactoring array variables with a consistent naming convention

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/qcubed#576]
QCubed normally follows a very good set of coding standards and I like them a lot. Prefixing the variables with types is great. 
1. One of the biggest advantage is that when using an IDE, the prefix allows the developer to get full advantage of IDE's auto-complete features. 
2. A second advantage is that looking at a variable's name's starting gives you the hint about what it would contain during its scope of existence (str = string, obj = some Php object, int = integer). 

However we tend to break the consistency when it comes to arrays. Now, PHP's arrays can behave like 'dictionaries' too (like they are said in Python and some other languages) and it makes a little difficult to find out what a variable contains. 

During my attempt of writing the API documentation, I have found the following patterns spread all across the framework code: 
1. <VarName>Array
2. arr<VarName>Array
3. ary<VarName>
4. <VarName>_Array (e.g. intUserIdArray)
5. <TypeName><VarName>Array (e.g. obj_UserArray)
6. <TypeName><VarName>_Array (e.g. objUser_Array)

This much is enough of confusion but I think I have encountered more styles. 

Here is what I am proposing the style to be - `arr<TypeName>_<VarName>`

So if you have an array of Integers, it should be like this: `arrInt_UserId`
For array of array of objects: `arrArrObj_User`
For array of strings: `arrStr_Table`

Considering the example `arrStr_Table`, this would help identify the format in which tables are represented - are they table names, or QTable objects or something? 

Right now, the most dominant format for array is something like this: objTablesArray (format = <TypeName><VarName>Array. This not only breaks the overall naming convention, first look at the variable name gives the impression that it is an object (the 'obj' prefix) thought it is treated as array. 

The naming convention I am proposing would have two advantages: 
1. It keeps the current convention and first look at a variable name would not confuse you. 
2. It makes sure that the variable is easily identified as an array; both the prefix 'arr' and a Underscore separating the name and variable type - assuming you need to store a array of something like "int_reference_num" (which can stand for Internal Reference Number, where the reference number is a _string_), your corresponding variable would be named as **arrStr_IntReferenceNum** which is clear to read and easy enough to interpret in first look. 

I will attempt to modify the variable names when I encounter them. However, i would like to know if this is okay with members.

**Comment by spekary** [comment]
I applaud the desire for consistency. We already had a discussion on this at #306 . 

The postfix 'Array' is used the most in the current implementation. I did a brief survey of other frameworks, and many are using the plural form of the object name (which mostly ends in 's'). I would prefer to allow either, as I have found situations where the plural form is awkward, and its better to end it with 'Array'.  I am not in favor of inserting an underscore in variable names.

The only situation where 'arr' should be the prefix is if we have an array of arrays (i.e. a two dimensional array). All other instances of starting with 'arr' should be removed and changed to either a postfix 'Array' or a plural ending.

**Comment by spekary** [comment]
In general, our style guide should move towards the PSR-1 and PSR-2 standards. However, for this situation, they do not specify a particular naming convention for class properties.

**Comment by vaibhav-kaushal** [comment]
I agree. Now take this: ```objLetterArray```. Is it an object made of arrays of letters or is it an array of Letter objects? Can you clearly judge it? Give it a thought. 

Arrays are containers and objetcs are containers as well. Combining them *can* get confusing. Plural form is definitely not good but attaching array at the end can be worse in cases. Any new person who is readin our code will get wrapped inside his head. This is the reason I proposed that naming convention (and bring in an underscore). I am not fond of underscore a lot myself but in this case they solve the problem, which I believe is more important.

**Comment by spekary** [comment]
Well, every naming convention takes some getting used to. I don't think we need to go to great lengths to make a complicated convention that will not get used that often. This is a naming convention for the core code, not for everyone else's. And it doesn't need to be 100% descriptive. objLetterArray in our naming convention could describe either situation, but more likely an array of objects. If instead it describes an object that describes an array of letters, then I would challenge the developer to pick a different name, like objLetterList or objLetterGroup. Are there any particular situations in the core that are currently confusing?

**Comment by vaibhav-kaushal** [comment]
No, the bigger problem is inconsistency.

**Comment by olegabr** [comment]
@vaibhav-kaushal, I'm happy with `$objTypeArray`. The corner case you are talking about is just corner case. I'm sure that we don't have even one such a case in the whole qcubed codebase ;-)
Let's choose simplicity for the cost of this one corner case.

**Comment by vaibhav-kaushal** [comment]
So no underscores either (something like ```$objLetter_Array``` ). And the reason I am putting in this much weight on naming is because I use the same naming convention throughout. So the entire codebase looks very much similar and things are easy to read for everyone in team. If we are finalising on a convention here, then I am going to adapt it through and through in my own codebase and will start renaming the previously set names as well.

**Comment by spekary** [comment]
This needs to be consistent with PSR-1 and PSR-2 first.
