### ISSUE TITLE
Implement PSR-1, PSR-2, PSR-4 with exceptions

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#578]
Some things these PSRs do will not work for us. This issue can be a repository of the exceptions we are going to have before we do the work.

**Comment by spekary** [comment]
Exception: They require that class constants be all upper case. QCubed uses class constants to create enumerated values, and it would be really dumb to force these to be all upper case.

**Comment by spekary** [comment]
Exception: They require only one class per file as part of the autoloading scheme. Some classes have small little support classes. This would mean putting these title support classes in their own files. Kind of a dumb idea, but we would have to think of how to deal with the autoloading issue.

**Comment by olegabr** [comment]
Exception: use CamelCase  instead of javaStyle ;-)

**Comment by spekary** [comment]
I have created and committed some new repositories for v4:
- common
- orm
- i18n

These are all namespaced, and implement PSR-4. Orm implements PSR-1 and 2 as well. They have unit tests, and the unit tests function on Travis. They are designed to be fairly standalone, with minor dependencies on other projects.

The orm implementation was requested many years ago by @scottux . The orm repo is now completely separate from forms, controls and QApplication, though it does use some code found in the common repo. Also, for this implementation, I had to remove Cache support in the database. This could potentially be put back in as middleware after the 5.0 work of disconnecting QQuery from the Database implementation.

**Comment by spekary** [comment]
application repository is now passing travis build.

If you want to try the new version, issue this command:

```
composer create-project -sdev qcubed/app-starter "your-dir" dev-qcubed4
```

substitute your directory name for your-dir

**Comment by spekary** [comment]
By the way, this new version has some new capabilites. In particular, plugins have gone away. All qcubed repos will have type "qcubed-library". Whatever is in the install directory will get merged into the installation directory. Some directories of note there:
* project is project directory, like in v3
* project/includes/configuration/active contains active configuration files. Configuration files are broken out by behavior, and different repos can inject their own configuration files by simply putting one in its own install/project/includes/configuration/active directory
* project/qcubed contains override files for the framework itself, and is organized by sub namespace
* project/qcubed/Jqui contains all the JQueryUI controls, and has been updated to the latest version of JQuery UI
* project/includes/configuration/templates contains pointers to template directories. This allows other repositories to inject templates easily
* project/includes/configuration/control_registry conatins control registry files. Again, this allows other repositories to inject control registries, specifying controls that can edit common database field types, and make those available to the ModelConnector editor

Moving forward, we will have a small group of community maintained add-on repos. I think the following will be about it:
* bootstrap
* datatables
* ckeditor

Other "plugins" should be in the private repos of contributors, allowing them to maintain them at will. All they need to do is mae the type "qcubed-library" in the composer.json, and the qcubed composer installer will take care of merging the install directory found in the repo with the current installation. This will make qcubed easier to maintain, since we don't have to maintain a growing list of add-ons.

Add-on authors can announce their contributions on the wiki.

I suggest as many people as can to take a look at the new structure. This will be the future of qcubed moving forward. Hopefully this is the last large-scale refactoring for some time, allowing us to get down to the business of documenting this thing without worrying about major name changes.

**Comment by spekary** [comment]
Closing this because this is implemented in the core
