### ISSUE TITLE
Moving examples out of framework into plugin?

### ISSUE THREAD

**Issue by var-foo** [qcubed/qcubed#60]
I'm beginning to think that the examples package should be a plugin (all examples in the same plugin, of course). Most people aren't going to use the local examples if they're published somewhere already, and they could be coded much cleaner as a plugin with a corresponding database dump. This way, if anyone wants to run the example locally or create a new example, they can just install the examples plugin and import the tables.

The reason I'm saying this is because there is a lot of text embedded into the views, and I feel like it would be better served in a database and maybe have some sort of admin package in the plugin that allows us to easily create/edit examples. This would help us to streamline the template for examples and have much less code to update next time around as well as significantly cutting down the footprint of the framework's file system. This will also make it a bit easier to install a minimal framework package. I'm sure most people wouldn't want the examples to be on a production site, so I see no reason to force their inclusion into the base framework.

Does anyone else share this feeling? If so, I'm willing to take this on.

**Comment by spekary** [comment]
This is covered by #1118
