### ISSUE TITLE
class call and namespaces

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#624]
What about namespaces and direct class call with some autoload mechanism? In some situations we need to make widgets and call them via direct call we do not need to put always require() in header. Just call what we need and don't care where it is. Is there PSR-4 class loader implemented? .

**Comment by spekary** [comment]
We have discussed this and decided to move this to 3.1. There is already an autoloader implementation for the core, so PSR-4 for the core is not necessary for now. Plugins are free to implement PSR-4, and the current plugin_bootstrap repo does that. It will just use composer's built-in autoloader, which the core autoloader calls as part of its load process.

**Comment by spekary** [comment]
namespaces will use PSR-4 in v4

**Comment by spekary** [comment]
This is now complete in the 4.0 repo
