### ISSUE TITLE
Project sample in alpha 3

### ISSUE THREAD

**Issue by vmakre** [qcubed/qcubed#638]
When i studied qcubed at first time everything went smooth and fine and i never cared  how 
this works and what is inside. Just look at examples and everything is fine , make simple copy paste and code works, but now i am trying to make things to be more  organized and coding to be more funny.
Maybe you can say this is more personally how everyone organize project himself , but it is good to have some ideas and share them with other people. I am saying this because we started to use composer as plugin installer , so next time we'll talk about maybe modules or widgets or whatever will come , and we confirmed that all things we need to download will go to plugin folder  . So what after that if we have project folder moved to public directory , where will go plugin assets ?. I have some ideas of dividing project folder to controllers, views, codegen, includes ....  to some logical way because now this is trend and frameworks are made for better code organization .  If we think about this a lot of configuration options will disappear and a lot of things will be more clear and simple. For example if we know that assets are in Project-Public-Assets we don't need configuration variable for this. Looking at other frameworks they have simple configuration files, some good folder logic and i think we should think about this. For compatibility reason we can use old fashion configuration.php file but all variables will be filled with default parameters.Of course we are building professional business logic and security  is another point of view so putting everything in public_html in shared hosting can be bad idea. And there is apache mod_rewrite of course , we have apache rewrite option but don't have  good index routing engine. So instead of asking "Where is it" i think we can make sample project to have folders with known locations , and this is good for tomorrow we can make good batch scripts for whatever ,  for example using composer for installing or uninstalling modules , update plugin assets etc..

**Comment by spekary** [comment]
The current configuration appears at first glance complicated, but it really isn't all that complicated. It needs a little cleanup, but I did a round of cleanup when switching to the new structure for composer. Some of the defines that are there are for backwards compatibility, but most of it is there because of the issue you brought up on deployment. I believe there has already been some discussion about deployment strategies.

Feel free to propose some new folder logic. I personally think the folders are organized pretty logically for development purposes. For deployment, you currently have to define your own folder structure, with the assets in doc_root, and the rest outside of docroot. The discussion so far has been to create a tool that will take the current folder structure and do that for you for deployment. I don't see any good way around this, since composer wants everything it controls to be in one directory (vendor by default, but you can change that), and everything else outside of that directory.

**Comment by vmakre** [comment]
I made this folder structure but sometime i have problem debugging with mod rewrite so this is problem with development  for now. I can't make xdebug to stop at desired line , this is known xdebug problem i dont know why. So folder structure which i want must be good for development and for deployment also. I don't prefer  folders to be different as i am uploading my projects always with ftp and with same folder structure. 
* /MAIN HTDOCS can be used for many projects
    *  /PROJECT FOLDER
         * /app
               *  /controller
               *  /generated
               *  /includes
               *  /views
         *   public    
               * /css
               * /js
               * /images
               * /documents
               * index.php
               * .htaccess
    *  /vendor
       * /qcubed  
              *  ......
       * /ezyang
             *   ...... 

I can make this working and package all into plugin as package . I tested this structure in live hosting as only public folder was in public_html and it is ok . but htaccess and mod_rewrite must be configured for both local and remote site . For now i am trying to test locally without mod rewrite with index.php (xdebug)  and enable rewrite only in deployment with simple htaccess configuration. Controller and views can be expanded into subfolders for better organization.

**Comment by spekary** [comment]
The goal of deployment should be to move unnecessary code out of docroot. In particular, the configuration.inc.php file, with its database passwords, needs to be moved out.

We don't currently have controllers and views per se. The controller responsibility is divided between QForms and ModelConnectors. That would be good, but we need to resolve whether a view will be different from a QForm, which I think it should be, so that a view can be inside a dialog too.

The public directory is the same as the current assets directory? What about the qcubed assets directory, and the qcubed plugin assets?

**Comment by vmakre** [comment]
I know that qforms are controllers also or i am wrong? . And what about widgets ,where they will go ?.
> "The public directory is the same as the current assets directory? What about the qcubed assets  
> directory, and the qcubed plugin assets?"   

I am asking you too , in laravel they have command line "artisan" script for updating assets from plugin to public_html , very nice idea but this is only for development and every plugin have defined class for command line operations with parameters like install, update, dbinstall etc... but it's complicated and we don't need this. We can for the first time to define something like project plugin classes definition , what plugins will be enabled for project (if i don't like everything to load). In Laravel in config there is section for enabled plugins .  After this we can make some php script for assets update from plugin to public folder , for example after plugin composer update. With one command like "update_qcubed_assets" .instead of copying all files manually. I have one qcubed library and a lot of plugins installed in vendor and i am using what i need in my projects , will be good option to enable and disable plugins.

**Comment by spekary** [comment]
Composer uses an auto-loader. So, everything is brought into memory when it is called. "Enabling" and "Disabling" plugins is a matter of installing them and uninstalling them. It sounds like all you are doing is trying not to have to deploy all the plugins you have installed on your development machine. That would be up to whatever deployment system you have. QCubed currently does not have a deployment system. I don't think we need a plugin management system for development outside of what Composer provides, unless you can think of a reason.

If we were to create a deployment system for QCubed, I think it would be simply a matter of gathering up all the assets directories in various places, and putting them under docroot, and all the other stuff and putting it somewhere outside of docroot. Configuration.inc.php would need to have just a few defines set for deployment specifically, and everything should flow from those root defines. configuration.inc.php is already setup to work that way (at least, in alpha3). 

As I type this, I realize that we probably need to specify that plugins should have an "assets" directory, where all the js, css, and anything else that needs to be directly accessible by he browser should go. That will make it easy for the deployment system to know what to get. That would be a change to the plugins, but now is a good time to make that change moving forward.

**Comment by vmakre** [comment]
> As I type this, I realize that we probably need to specify that plugins should have an "assets" directory, where all the js, css, and anything else that needs to be directly accessible by he browser should go. That will make it easy for the deployment system to know what to get. That would be a change to the plugins, but now is a good time to make that change moving forward.

Yes that's the point , also qcubed assets can be defined as plugin assets and they will go to public assets after deployment. Another thing i am thinking of is why we don't have many configuration.inc.php files one for deployment one for testing one for development. All three are different  and are specific for the project .

**Comment by olegabr** [comment]
IMHO, it is all about moving qcubed-based project to production. Much work should be done here to make it easy for user.

**Comment by spekary** [comment]
Moving this to version 4.0. The new folder structure definitely needs to worry about how to do deployment.

**Comment by vmakre** [comment]
4.0 must use mod_rewrite because it is not recommended  application files to stay in public access.  But this can be made when we hide all app folder from public access. Public_html folder with assets and index.php will be enough , i think this is easy achievable but we need mod rewrite simple route logic .
my example:
```
require('../project/includes/configuration/prepend.inc.php');
// define routes , you can use aliases but not tested
$route=array('home'=>'home.php' , 'dashboard'=>'dashboard.php' , 'about'=>'about.php'); 
// check file with form class exist
if (file_exists($strFilePath = sprintf('%s%s', __PROJECT__. '/forms', $route[substr($_SERVER['PATH_INFO'],1)]))) {    
require($strFilePath); 
 }  else  {
// else goto index page 
require(__PROJECT__. '/forms/index.php');
}
```
Url is  `http://domain.com/index.php/ClassName`   or `http://domain.com/ClassName`  
or if we don't want to use route array then this line can be:
`if (file_exists($strFilePath = sprintf('%s%s.php', __PROJECT__. '/forms', $_SERVER['PATH_INFO']))  { `

Only small problem is location of template file because we are outside of forms folder ,  i use VIEW variable e.g. if you have different folder for all template files or use default  like: 
`define( '__VIEW__' , __PROJECT__ . '/forms') ;`
// modify form run
`MyForm::Run('MyForm', __VIEW__.'/myform.tpl.php' )`
