### ISSUE TITLE
Autoloading is not available if using PHP in CLI interactive mode.

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#66]
@jamescmunro,  in an issue #32 you were forced to include model files into tests in order to make it work, since "Autoloading is not available if using PHP in CLI mode".

But documentation states that "Autoloading is not available if using PHP in CLI interactive mode." Note the "interactive" part (php -a) - http://php.net/manual/en/features.commandline.interactive.php

Is it the case of tests execution on the travis server? Can it be run in a non-interactive CLI mode?

**Comment by spekary** [comment]
v4 fixes this. There is a separate autoloading service you can create and it will handle composer autoloading after that.
