### ISSUE TITLE
QSqlServer2005Database.class.php - Codegen fails if the table has no index column and no primary key

### ISSUE THREAD

**Issue by ubs** [qcubed/qcubed#692]
I encountered this issue while trying to debug a connection to Microsoft SQL Server DB.
### Issue

When a table has no indexes, the code gen fails with an unclear error. It turns out that it fails when an undefined function is called to get the error information from the DB resource. This rogue piece of code can be found in 

`QSqlServer2005Database.class.php line 553 (QSqlServer2005DatabaseResult->FetchArray())` 

I believe this is a copied and pasted code as the `GetErrorInformation()` method does not exist within the scope specified.
### Resolution
1. Solve the immediate issue of undefined `GetErrorInformation()` method by slightly altering the line as follows:

`$this->objDb->GetErrorInformation($strErrorinformation, $strErrorCode);`

Also, the variable `$strNonQuery` does not exist on line 554 so I altered that as follows:

`throw new QSqlServer2005DatabaseException($strErrorinformation, $strErrorCode, null);`
1. Solve the NO INDEX problem pre-emptively.
   As it turns out, Qcubed requires at least one index (e.g. the primary key) in order to successfully generate the ORMs. I added additional code to `QSqlServer2005Database.class.php` to check if the table being analysed has at least one index. If not, it should fail gracefully or NOT, as you may decide it to be. 

See lines 440 - 496 of attached code file `QSqlServer2005Database.ProfNoTime.class.php`

I hope this gets corrected in the latest branch/version.

**Comment by vaibhav-kaushal** [comment]
You can make a pull request for the same :)

**Comment by ubs** [comment]
Done. Pull request created.
