### ISSUE TITLE
QDatepickerBox allows selection of date outside of MinDate and MaxDate (defaults to current year)

### ISSUE THREAD

**Issue by tracyaichele** [qcubed/qcubed#749]
QCubed version 2.2.3

I am trying to use a QDatepickerBox to select dates restricted to a past year, using date format of "m/d" (the user should not be able to choose the year in this box, as it is restricted by other inputs).  

When I retrieve the DateTime from the QDatepickerBox, it is defaulting to current year.

Here is a sample page to show the situation:
<?php

```
ini_set('display_errors','1');
error_reporting(E_ALL);

require('includes/configuration/prepend.inc.php'); 


class testForm extends QForm 
{
    public $dlstTest;

    protected function Form_Create() 
    {
        $earlyDate = new QDateTime('3/1/2007');
        $lateDate = new QDateTime('9/20/2007');

        $this->dlstTest = new QDatepickerBox($this);
        $this->dlstTest->MinDate = $earlyDate;
        $this->dlstTest->MaxDate = $lateDate;
        $this->dlstTest->Required = false;
        $this->dlstTest->ChangeMonth = true;
        $this->dlstTest->ChangeYear = false;
        $this->dlstTest->JqDateFormat = 'm/d';
        $this->dlstTest->AddAction (new QChangeEvent(), new QAjaxAction('dlstTest_Change'));

        QApplication::DisplayAlert("early".$earlyDate);
        QApplication::DisplayAlert("late".$lateDate);
    }

    public function dlstTest_Change()
    {
        //QApplication::DisplayAlert('test');
        QApplication::DisplayAlert("early".$this->dlstTest->MinDate);
        QApplication::DisplayAlert("late".$this->dlstTest->MaxDate);
        QApplication::DisplayAlert($this->dlstTest->DateTime);

    }

}

testForm::Run('testForm', 'test_datepickerbox.tpl.php');
```

?>

And the tpl file:

<?php

$this->RenderBegin();

$this->dlstTest->Render();

$this->RenderEnd();

?>

**Comment by tracyaichele** [comment]
Problem is resolved if:

$this->dlstTest->JqDateFormat = 'm/d/y';

But - is there a way to force the year with format 'm/d'?  It appears to be selecting 2007 in the calendar popup, but when we get the DateTime, it is set to the current year.

**Comment by kukrik** [comment]
If I understand your problem, then try to fix the code:

```
<?php

	ini_set('display_errors','1');
	error_reporting(E_ALL);

	//require('../qcubed.inc.php');
	require('includes/configuration/prepend.inc.php');


	class testForm extends QForm {
		protected $dlstTest;

		protected function Form_Create()
		{
			$earlyDate = new QDateTime('03/01/2007');
			$lateDate = new QDateTime('09/20/2007');

			$this->dlstTest = new QDatepickerBox($this);
			$this->dlstTest->MinDate = $earlyDate;
			$this->dlstTest->MaxDate = $lateDate;
			$this->dlstTest->Required = false;
			$this->dlstTest->ChangeMonth = true;
			$this->dlstTest->ChangeYear = false;
			$this->dlstTest->AddAction (new QChangeEvent(), new QAjaxAction('dlstTest_Change'));

			QApplication::DisplayAlert("early " .$earlyDate);
			QApplication::DisplayAlert("late " .$lateDate);
		}

		public function dlstTest_Change() {
			QApplication::DisplayAlert("early " .$this->dlstTest->MinDate->qFormat('MM/DD'));
			QApplication::DisplayAlert("late " .$this->dlstTest->MaxDate->qFormat('MM/DD'));
		}
	}

	testForm::Run('testForm', 'test_datepickerbox.tpl.php');

?>
```
Good luck to you!

**Comment by tracyaichele** [comment]
Thank you for your response!  It's not that I want them to have the same format, but it's not carrying the year from the datepicker widget to the QCubed framework.  I am looking for the QDatepickerBox to always return a year/full date.  

I think I found the problem in the class QDatepickerBoxBase:
<?php
public function ParsePostData() {
			// Check to see if this Control's Value was passed in via the POST data
			if (array_key_exists($this->strControlId, $_POST)) {
				parent::ParsePostData();
				$this->dttDateTime = new QDateTime($this->strText);
				if ($this->dttDateTime->IsNull()) {
					$this->dttDateTime = null;
				}
			}
}
?>

If you set the JqDateFormat to 'm/d', $this->strText has a null year, and the QDateTime constructor supplies the current one.

I realize that I could fix this with a custom validator, but I think it's more than that.

I'm thinking that the way to solve this might be to have the QDatepickerBox not only have the calendar and text box, but a non-visible QLabel that stores the full date returned by the Datepicker widget.  If the date is linked with the QTextBox, we run into the formatting issues.

Does this seem a reasonable fix?  If so - should I try to work on this for version 3?  I just haven't worked with the QJsClosures and the intersection with jquery ui.  But willing to play with it.

The other case would be if the user sets the Text in the QTextBox - if JqFormat is set to 'm/d', it does not accept a user's year input.  In this case, the date is set with the setter in QDatepickerBoxBase class.  So far, I think that has to be handled with a custom validator, but open to ideas.

**Comment by tracyaichele** [comment]
Still working through.

I think I need to use the altField: http://jqueryui.com/datepicker/#alt-field

If the AltField property is assigned to a given QDatepickerBox, the class should generate a new QTextBox  (AltControl?) with that id (how to keep the id from conflicting?  Not sure yet).  The default should be that this text box will be rendered with display = false and default AltFormat should include a year.  This must be a QDateTime-friendly format.

 The Text value of the AltControl will be used in Validate(), ParsePostData(), and the getter for DateTime.

**Comment by tracyaichele** [comment]
I give up - I can't add a control in the class and have it render without rewriting to have a QPanel class.

**Comment by kukrik** [comment]
I have great difficulty understanding the English language because I do not have a very, very good.
Whether you want a calendar next to a textbox or something else??? If so, you want to get the output desired format (m/d)??? Or do I misunderstand???

Refine intelligibly!

PS. Why do you care so much popups? Whether for test?

**Comment by tracyaichele** [comment]
The popups were just to test the values that I was getting out.  I wanted to take a simple case out of what I was doing to verify that the QDatepickerBox was not returning the expected value.

I want the date that I select on the calendar to become the DateTime of the QDatepickerBox control.  In this case, I want $this->dlstTest->DateTime to equal the value that I select on the calendar.  

Because I used the 'm/d' format in setting up the QDatepickerBox, the year is truncated off.  When the value of a text box (in format 'm/d') is passed to the QDateTime constructor, the QDateTime constructor assumes current year.  In this test case, I had selected a date in 2007 on the calendar, but the DateTime of the QDatepickerBox is set to a date in 2015.

This line in QDatepickerBoxBase in the setter for DateTime:
parent::__set('Text', $this->dttDateTime->qFormat($this->strDateTimeFormat));

calls the setter for Text with a string version of the date (no year).
					
And the setter for Text:
case 'Text':
parent::__set($strName, $mixValue);
$this->dttDateTime = new QDateTime($this->strText);
break;

This DateTime will not be correct unless the year is part of the format of the textbox.  

We had the correct date in the setter for DateTime, but discard the year information to set the Text.  Then we create a new DateTime for the control from the text, which is missing the year.

The rest of the comments are me trying to figure out the most proper way to solve the problem in the most general way.

**Comment by kukrik** [comment]
Do you think that this is the one?
![screen shot 2015-08-05 at 14 44 50](https://cloud.githubusercontent.com/assets/2853034/9085062/3195fc6a-3b82-11e5-9068-0779f9fa455a.png)
Then try it
```
<?php
	ini_set('display_errors','1');
	error_reporting(E_ALL);

	//require('../qcubed.inc.php');
	require('includes/configuration/prepend.inc.php');

	class testForm extends QForm {

		protected $dlstTest;

		protected function Form_Create() {
			$earlyDate = new QDateTime('03/01/2007');
			$lateDate = new QDateTime('09/20/2007');

			$this->dlstTest = new QDatepickerBox($this);
			$this->dlstTest->MinDate = $earlyDate;
			$this->dlstTest->MaxDate = $lateDate;
			$this->dlstTest->Required = false;
			$this->dlstTest->ChangeMonth = true;
			$this->dlstTest->ChangeYear = false;
			/*$this->dlstTest->JqDateFormat = 'mm/dd';*/ /** This line removed  **/
			$this->dlstTest->AddAction (new QChangeEvent(), new QAjaxAction('dlstTest_Change'));

			QApplication::DisplayAlert('Early: ' .$earlyDate);
			QApplication::DisplayAlert('Late: ' .$lateDate);
		}

		public function dlstTest_Change() {
			/**  Much options, here's one simple example  **/

			$dtt = $this->dlstTest->DateTime;
			if ($dtt) {
				QApplication::DisplayAlert('Early: ' . $this->dlstTest->MinDate->qFormat('MM/DD/YYYY') . "\n" .
					'Late: ' . $this->dlstTest->MaxDate->qFormat('MM/DD/YYYY') . "\n" .
					'Selected: ' . $dtt->qFormat('MM/DD/YYYY'));
			}
		}
	}

	testForm::Run('testForm', 'test_datepickerbox.tpl.php');

?>
```

**Comment by tracyaichele** [comment]
Yes, thank you.  I realize that this would work if I set the JqDateFormat to something that includes the year.  I am trying to have it just show the month and day, since the user should not be able to change the year.  

It's the interaction of the date format with the control, or the interaction of the control with the altField, that need to be solved.
