### ISSUE TITLE
ExpandAsArray not compatible with Count and Limit

### ISSUE THREAD

**Issue by spekary** [qcubed/qcubed#753]
A basic flaw in the overall system has us counting lines and limiting the number of lines displayed in a grid AFTER the query but BEFORE the expanded lines are combined. This causes the count and limit to be incorrect when expanding as arrays.

For the count, the right way to do this would be to remove all array expansions before counting.

The limit is much more difficult, Likely we would need to do the query without the array expansions in order to select which lines to display, and then add additional queries for each line chosen by the first set to add the array expansions and add the results to each line. Would take some work to implement, but this is doable.

**Comment by spekary** [comment]
> The limit is much more difficult, Likely we would need to do the query without the array expansions in order to select which lines to display, and then add additional queries for each line chosen by the first set to add the array expansions and add the results to each line. Would take some work to implement, but this is doable.

I thought of another way to do this. Do the query selecting only the keys in each record, but remove all array expansions first. Then do the query again with all the fields and array expansions, but select only the keys that were found in the first query. Then let the current code assemble the results into the required arrays. That results in only two queries to get what is needed.

**Comment by lackovic10** [comment]
`For the count, the right way to do this would be to remove all array expansions before counting`

i agree here, and i think it should not be considered as a bug for the count query
i'll look into the select query if i find a bit more time

**Comment by lackovic10** [comment]
i'm pretty sure you need to use a subquery for this, which means that a different query would need to be used if `ExpandAsArray` (LEFT JOIN) is used compared to the same query without the left join.
that is a lot of complexity in my opinion, and i think one should know when using the query builder, what kind of queries are created. Maybe adding this example to the `ExpandAsArray` docs and explaining how the query build should be used, but i don't really see this as a bug.
i think that this would be very hard to code with multiple left joins so i vote for it staying as simple as it currently is

**Comment by spekary** [comment]
The problem is when trying to use this with a datagrid and a paginator. If you have a column that you use to display an array of related data by using an array expansion, then you can't use the COUNT function to figure out how many rows there are in the table, and you can't use LIMIT to get only the rows shown. The expansion causes each item of the array to become a row in the SQL result, which is not the same as a row in the html data. At a minimum, we need to document this.

The way to do it today is to make a custom callback column, and do a query whenever a cell in that column is drawn. The result is that if you are showing 20 rows, you get 20 extra queries. In the end, that might be fine, because the alternative is 2 queries with a lot of redundant data, so more data is transferred, but with fewer queries. One or the other might be more efficient depending on what is being shown.

**Comment by lackovic10** [comment]
i know, but i vote for documenting this and letting it rest :)

**Comment by spekary** [comment]
OK

**Comment by lackovic10** [comment]
i just ran into this issue at work and i couldn't resist playing with it :)
let me show what i was talking about with some examples:
```
TABLE team
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| team_id  | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| creator_id | int(10) unsigned | NO   |     | NULL    |                |
+------------+------------------+------+-----+---------+----------------+
```
```
TABLE user
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| user_id  | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| team_id | int(10) unsigned | NO   |     | NULL    |                |
+------------+------------------+------+-----+---------+----------------+
```
QQuery:
```
$teams = Team::QueryArray(
    QQ::Equal(QQN::Team()->CreatorId, $creator->UserId),
    QQ::Clause(
        QQ::ExpandAsArray(QQN::Team()->User),
        QQ::LimitInfo(5, 0)
    )
);
```
Constructed $sql:
```
SELECT
    `t0`.team_id as a0,
    `t0`.creator_id as a1,
    `t1`.user_id as a2,
    `t1`.team_id as a3
FROM
    `team` AS `t0`
    LEFT JOIN `user` AS `t1` ON `t0`.`team_id` = `t1`.`team_id`
LIMIT 0, 5
```
In order for the limit to work properly the query needs to be something like:
```
SELECT
    teams.a0 as a0,
    teams.a1 as a1,
    `t1`.user_id as a3,
    `t1`.team_id as a4,
FROM
    (
        SELECT
            `t0`.team_id as a0,
            `t1`.creator_id as a1,
        FROM
            `team` AS `t0`
        LIMIT 0, 5
    ) AS teams
LEFT JOIN `user` AS `t1` ON teams.a0 = `t1`.`team_id`;
```
This is only one join! Didn't explore how this needs to work with multiple left joins.
As i said before, i recommend the usage of a custom query, it's nice and simple with qcubed
A custom query example with a datagrid should be added to show how this needs to work and to explain better how the query builder works

**Comment by spekary** [comment]
Custom query can work of course. The problem is that its behavior that someone might try and get unexpected results, especially if they try to do a limit query to paginate a QDataGrid, and then include an ExpandAsArray item to show in a column. They will not get what they expect.

I think ultimately the best answer is to move the problem to the database adapters. I have a long-term feature there that does not generate SQL in the code generated ORM, but rather the ORM generates a database request, and then the database adapters figure out how to handle it. Moving this to v5, since its low priority anyway.

**Comment by matthiaz** [comment]
After the rewrite of the database adapters, this can be looked at again. But no point in keeping this open for now.
