### ISSUE TITLE
json and jsonb database fields support for postgresql 9.3 and 9.4

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#774]
postgresql 9.3 supports json table field type, and 9.4 introduces one more - jsonb type. It needs to be supported by qcubed.

**Comment by spekary** [comment]
What do you propose? In the past, QCubed has tried to only support standard SQL and stay away from DB specific things. That is why MySQL's SET field is not supported. 

I suppose you can just put whatever support you need into the Postgresql database adapter, with a note that its not supported elsewhere. Codegen is just going to return the field as a string, I don't see any way around that.

**Comment by vaibhav-kaushal** [comment]
I was discussing this about an hour ago with my colleagues. I think the way around is: we can write these extra data type handlers as plugins. In the ```default``` case of the data type handler, we write something like:

```
if(class_exists('QPgDatabaseExtension')){
// call a method in QPgDatabaseExtension to resolve the type
} else {
// throw exception
}
```

And put this in all adapters. That should make the system flexible enough.

**Comment by spekary** [comment]
Why not just put it directly in the adapter? Just because its in one adapter, doesn't mean it must be in the others.

Either that, or subclass the adapter and put the extensions in the subclass if you really want to separate them out, but I think just putting it in the adapter is fine. The adapter is defined in the config file, so its very specific to each application.

**Comment by olegabr** [comment]
This patch solves the problem for json type in 9.3:
```patch
From e1c436f573d1e05d07cf74e21df6eadd2a093829 Mon Sep 17 00:00:00 2001
From: deadka <daniil.kamenskiy@gmail.com>
Date: Wed, 2 Sep 2015 15:48:39 +0600
Subject: [PATCH] =?UTF-8?q?see=20#2213=20=D0=94=D0=BE=D0=B1=D0=B0=D0=B2?=
 =?UTF-8?q?=D0=B8=D1=82=D1=8C=20=D0=B2=20ORM=20QCubed=20=D0=BF=D0=BE=D0=B4?=
 =?UTF-8?q?=D0=B4=D0=B5=D1=80=D0=B6=D0=BA=D1=83=20Json?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

---
 includes/qcubed/_core/codegen/QCodeGenBase.class.php                  | 2 ++
 .../_core/codegen/templates/db_orm/class_gen/object_save.tpl.php      | 3 +++
 .../templates/db_orm/meta_control/control_create_string.tpl.php       | 3 +++
 includes/qcubed/_core/database/QPostgreSqlDatabase.class.php          | 4 +++-
 includes/qcubed/_core/framework/QDatabaseBase.class.php               | 1 +
 5 files changed, 12 insertions(+), 1 deletion(-)

diff --git a/includes/qcubed/_core/codegen/QCodeGenBase.class.php b/includes/qcubed/_core/codegen/QCodeGenBase.class.php
index 4e5a172..cfe5685 100644
--- a/includes/qcubed/_core/codegen/QCodeGenBase.class.php
+++ b/includes/qcubed/_core/codegen/QCodeGenBase.class.php
@@ -1335,6 +1335,8 @@
 					return QType::DateTime;
 				case QDatabaseFieldType::VarChar:
 					return QType::String;
+				case QDatabaseFieldType::Json:
+					return QType::String;
 				throw new Exception("Invalid Db Type to Convert: $strDbType");
 			}
 		}
diff --git a/includes/qcubed/_core/codegen/templates/db_orm/class_gen/object_save.tpl.php b/includes/qcubed/_core/codegen/templates/db_orm/class_gen/object_save.tpl.php
index 85962cb..5b90887 100644
--- a/includes/qcubed/_core/codegen/templates/db_orm/class_gen/object_save.tpl.php
+++ b/includes/qcubed/_core/codegen/templates/db_orm/class_gen/object_save.tpl.php
@@ -23,6 +23,9 @@
 			$strCol = '							' . $strEscapeIdentifierBegin.$objColumn->Name.$strEscapeIdentifierEnd;
 			$strCols .= $strCol;
 			$strValue = '\' . $objDatabase->SqlVariable($this->'.$objColumn->VariableName.') . \'';
+			if ( "Json" == $objColumn->DbType ) {
+				$strValue = '\' . ($this->' . $objColumn->VariableName . ' == self::'.$objColumn->PropertyName.'Default ? $this->'. $objColumn->VariableName . ' : $objDatabase->SqlVariable($this->' . $objColumn->VariableName . ')) . \'';
+			}
 			$strValues .= '							' . $strValue;
 			$strColUpdates .= $strCol .' = '.$strValue;
 		}
diff --git a/includes/qcubed/_core/codegen/templates/db_orm/meta_control/control_create_string.tpl.php b/includes/qcubed/_core/codegen/templates/db_orm/meta_control/control_create_string.tpl.php
index 18654ad..ce6738c 100644
--- a/includes/qcubed/_core/codegen/templates/db_orm/meta_control/control_create_string.tpl.php
+++ b/includes/qcubed/_core/codegen/templates/db_orm/meta_control/control_create_string.tpl.php
@@ -14,6 +14,9 @@
 <?php if ($objColumn->DbType == QDatabaseFieldType::Blob) { ?>
 			$this-><?php echo $strControlId  ?>->TextMode = QTextMode::MultiLine;
 <?php } ?>
+<?php if ($objColumn->DbType == QDatabaseFieldType::Json) { ?>
+			$this-><?php echo $strControlId  ?>->TextMode = QTextMode::MultiLine;
+<?php } ?>
 <?php if (($objColumn->VariableType == QType::String) && (is_numeric($objColumn->Length))) { ?>
 			$this-><?php echo $strControlId  ?>->MaxLength = <?php echo $strClassName  ?>::<?php echo $objColumn->PropertyName  ?>MaxLength;
 <?php } ?>
diff --git a/includes/qcubed/_core/database/QPostgreSqlDatabase.class.php b/includes/qcubed/_core/database/QPostgreSqlDatabase.class.php
index 4a7039a..fe49101 100644
--- a/includes/qcubed/_core/database/QPostgreSqlDatabase.class.php
+++ b/includes/qcubed/_core/database/QPostgreSqlDatabase.class.php
@@ -767,6 +767,7 @@
 					return $strColumnValue;
 				case QDatabaseFieldType::Char:
 				case QDatabaseFieldType::VarChar:
+				case QDatabaseFieldType::Json:
 					return stripslashes($strColumnValue);
 //					return stripslashes(QType::Cast($strColumnValue, QType::String));
 
@@ -931,7 +932,8 @@
 					$this->strType = QDatabaseFieldType::VarChar;
 					break;
 				case 'json':
-					// NOTE: basic support for postgresql json type
+					$this->strType = QDatabaseFieldType::Json;
+					break;
 				case 'text':
 				case 'bytea':
 					$this->strType = QDatabaseFieldType::Blob;
diff --git a/includes/qcubed/_core/framework/QDatabaseBase.class.php b/includes/qcubed/_core/framework/QDatabaseBase.class.php
index 673a3b0..af2ba0e 100644
--- a/includes/qcubed/_core/framework/QDatabaseBase.class.php
+++ b/includes/qcubed/_core/framework/QDatabaseBase.class.php
@@ -1055,5 +1055,6 @@
 		const Time = "Time";
 		const Float = "Float";
 		const Bit = "Bit";
+		const Json = "Json";
 	}
 ?>
-- 
1.9.1
```

But it made for the qcubed v2.2.3

I have no opinion how to do it correctly for the qcubed in general, but let it stay here to help someone else that needs it.

**Comment by vaibhav-kaushal** [comment]
@spekary I think that would be fine. Let me see when I can work on that. Putting the code in adapter makes sense if we have to go beyond the basic data types for each database.

(By the way, I have rarely seen people changing Databases, anyway!)

**Comment by spekary** [comment]
Agreed. @olegabr can you do a pull request?

**Comment by olegabr** [comment]
`qcubed-qquery-pgsql` package like here: https://github.com/qcubed/framework/issues/816#issuecomment-170385944

**Comment by vaibhav-kaushal** [comment]
Update: I have started working on this and given how important JSON has become recently, I was thinking, we can start supporting JSON in the core. I am testing it by creating a new QType. That would allow deeper support in the core. My work surrounds JSON Schema and generating code for Schema Validation on JSON documents. This could be exceptionally useful in PostgreSQL as JSON has become a part of PostgreSQL. I will be creating a pull request for the same, soon. 

@olegabr It is a little different from what you are doing in here.

**Comment by spekary** [comment]
OK. Think also about a general architecture that can support database specific functions, data types, etc. This seems to me to be a big change. Can it wait until 3.1?

**Comment by vaibhav-kaushal** [comment]
It can, probably. However, I have also started work on a Separate Query class for PostgreSQL. I have named it `QPgQ` and a file for various conditions. I have already created `QPgQConditionILike` for case-insensitive searches and `QPgQJsonContains` for searches within a JSONB document. These are tested and I found them working.

**Comment by spekary** [comment]
Sounds cool. Also sounds like a good candidate for a plugin. The composer architecture lends itself to inserting classes into the framework like this.

**Comment by vaibhav-kaushal** [comment]
Yeah, I am okay with the plugin thing (and which is why I kept them separate). Now, QCubed has long been DB agnostic and that is something great. However, there are powerful features in every major database out there. For example, there are so many data types which we just infer as text because the DB driver for PHP gives us text. Take for example - IP Address. There are certain known operations on IP address beyond its treatment as a number or string. JSON is a huge candidate - there is JSON data everywhere, especially on the web. All the APIs I build for any of my project use JSON too. If we were to take QCubed to next level (think - automated API code generation), we will need better JSON support. 

On the other hand - I believe that the core must have ready features to utilize database specific features as well - think about *tsvector* type in PostgreSQL - it is a beast and at least 50 times faster to implement and configure, when you need the feature handy. We could keep QQuery where it is (it is great) and extend it for DB specific workloads. I haven't seen someone switching DBs later in the project anyway; if they do, QCubed cannot solve those cases because the causes for DB migration are many. 

For that reason, I would rather like to see more query support in the core itself.

**Comment by vaibhav-kaushal** [comment]
@olegabr and @spekary Please see #1024

**Comment by olegabr** [comment]
@vaibhav-kaushal great work!
I vote for plugin and namespaces, e.g. `\QQ\Pg\Something`. There is no reason to not use namespaces in 3.0 plugins now.

As for the core json type support, IMO, let it be for now to evaluate consequences. MySql 5.7 have the json type too. It is a mainstream now.

**Comment by spekary** [comment]
That sounds like a good approach to me. Not sure about the QType of JSON though. Seems like that should just be a string. But the QDatabaseType I am fine with.

**Comment by vaibhav-kaushal** [comment]
I think this has been taken care of.

**Comment by olegabr** [comment]
need to add tests for it
