### ISSUE TITLE
getJson doesn't use jsonserializable

### ISSUE THREAD

**Issue by matthiaz** [qcubed/qcubed#854]
The current implementation of getJson isn't taking advantage of the newer features PHP offers.
At the moment it simply does the following. 

``` php
    class ObjectGen extends QBaseClass implements IteratorAggregate
    ....
    public function getJson() {
        return json_encode($this->getIterator());
    }
```

In newer PHP version however, you can do something like this

``` php
    class ObjectGen extends QBaseClass implements IteratorAggregate, JsonSerializable
    ...
    public function getJson() {
        return json_encode($this);
    }
    public function jsonSerialize() {
        return $this->getIterator();
    }
```

This does exactly the same thing (I'm well aware of this...) but has the added benefit that it allows you to do a json_encode on the object itself, in stead of calling getJson. It also ties in better with what php currently has to offer. 

This also has the advantage that you can cascade through objects. getJson always returns a string. But jsonSerialize returns a version of the object you are going to serialize. 

if I do in ObjectA:

``` php
   public function jsonSerialize() {
        return array('id'=>$this->intId, 'subobject'=>$this->SubobjectB);
    }
```

and in ObjectB

``` php
    public function jsonSerialize() {
        return array('id'=>$this->intId, 'name'=>$this->strName);
    }
```

then I can do a json_encode($objectA) on ObjectA and the json will be cascaded down to ObjectB.

Is this something worth pursuing? Or am I just nitpicking?

**Comment by matthiaz** [comment]
I updated my original issue with additional info and correct formatting.

**Comment by spekary** [comment]
Yes, worth pursuing. You are correct. It should be changed.

**Comment by olegabr** [comment]
good catch, @matthiaz!
could you, please, do a pool request with some tests included?

**Comment by matthiaz** [comment]
I cloned the beta3 of qcubed and it is only then that I noticed JsonSerializable is already implemented in that version. I looked up the code and it looks @spekary added this on 20feb.
So.... is it still a good idea to change the getJson method to json_encode($this)? Because then I will be changing what it outputs.

**Comment by spekary** [comment]
I forgot that. Lots has changed. Looking at what I did, it should probably be reworked. I think I was headed down a path, and then stopped.

My version does not look like its currently in use anywhere. I was thinking of something similar to toJsObject, that would be used in drop down lists and autocompletes to describe an object selection. But again, its not currently being used, so can be replaced.

Could you give your use case for needing to serialize an entire database object? That way we can make it work, and also document why its needed so future versions protect that. Also, do you need to deserialize at all, converting json back into a db object?

**Comment by matthiaz** [comment]
Use case: I would like to convert a database object to JSON to expose it via an API.

I'm currently working with a heavily modified version of qcubed 2, do take this into account. But I have finished the export to JSON and the import from JSON to a database object in my local code base.

**Comment by spekary** [comment]
V3.1 now makes the model objects implement jsonserializable interface, and you can use QQSelect clauses to specify exactly what parts of an object to fill with data, and when converting to json, only data fields that are valid will end up in the json.

**Comment by spekary** [comment]
Oh, and incidentally, getJson is now deprecated.
