### ISSUE TITLE
Examples application should be a qcubed application

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#871]
For now, examples are special. But it should be just a qcubed application that can be installed stand alone. And the qcubed core should not include it by default.

This change would simplify the examples application structure. For now it is bloated with some artifacts that just duplicate the core qcubed functionality, like `includes` or `images` folders.

Target it to the 3.1 milestone.

**Comment by spekary** [comment]
Perhaps the examples site is just poorly named. It is not supposed to be an example of how to create a qcubed application, but rather it serves as a tutorial and point of documentation for all of QCubed's major features. I don't see how an example application could really fit that role.

Perhaps we need a separate example application, and then rename the "examples" to "tutorials".

**Comment by olegabr** [comment]
+1

**Comment by vmakre** [comment]
Yes qcubed vendor should be only for library . As we are going to use composer more and more we need to have clean and simple qcubed vendor code. Also i will suggest qcubed assets and some codegen  code to move to project folder. Or create some installation folder in project only for development with setup wizard and some db sql with data  for examples ,codegen   etc.

**Comment by spekary** [comment]
THis is covered under #1118. In process.
