### ISSUE TITLE
How to create a virtual host for a QCubed project in xampp on Windows?

### ISSUE THREAD

**Issue by olegabr** [qcubed/qcubed#937]
@eu127

in httpd-vhosts.conf I added:

NameVirtualHost *:80

<VirtualHost *:80>

DocumentRoot "C:/xampp/htdocs/tef_ticketing/workspace/htdocs"

ServerName tef_ticketing.dev

ServerAlias www.tef_ticketing.dev

<Directory "C:/xampp/htdocs/tef_ticketing/workspace/htdocs">

DirectoryIndex home.php

AllowOverride All

Require all Granted

</Directory>

</VirtualHost>

In C:\Windows\System32\drivers\etc\hosts:

127.0.0.1 localhost

127.0.0.1 www.tef_ticketing.dev

in configuration.inc.php

$url = "tef_ticketing.dev";

define("**DOCROOT_URL**", $url);

in home.php

<?php

require_once (dirname(**FILE**) . '/qcubed.inc.php');

\QApplication::Redirect('test_page');

in .htaccess

<IfModule mod_rewrite.c>

RewriteEngine on

RewriteRule ^$ home.php [L,QSA]

RewriteRule ^$ ajax.php [L,QSA]

RewriteRule ^home$ home.php [L,QSA]

RewriteRule ^test_page$ form.php?form=TestForm [L,QSA]

In TestForm.class.php

<?php

namespace Tef_Ticketing\Presentation\Web\Forms;

use Tef_Ticketing\Presentation\Web\Forms\Form;

class TestForm extends Form {

protected $btnTest1;

protected $btnTest2;

protected $btnTest3;

protected $lblTest1;

protected function Form_Create() {

parent::Form_Create();

$this->btnTest1 = new \QButton($this);

$this->btnTest1->Text = 'save1';

$strJavaScript = "qc.pA('TestForm', 'btnTest2', 'QClickEvent', '', 'QFormWaitIcon');";

$this->btnTest1->AddAction(new \QClickEvent(), new \QAjaxAction('btnTest1_click'));

$this->btnTest1->AddAction(new \QClickEvent(), new \QJavaScriptAction($strJavaScript));

$this->btnTest2 = new \QButton($this, 'btnTest2');

$this->btnTest2->Text = 'save2';

$this->btnTest2->AddAction(new \QClickEvent(), new \QAjaxAction('btnTest2_click'));

$this->btnTest3 = new \QButton($this);

$this->btnTest3->Text = 'save3';

$this->btnTest3->AddAction(new \QClickEvent(), new \QAjaxAction('btnTest3_click'));

$this->lblTest1 = new \QButton($this);

$this->lblTest1->Text = 'init';

}

public function btnTest1_click() {

sleep(5);

$this->lblTest1->Text = 'a';

}

public function btnTest2_click() {

}

public function btnTest3_click() {

$this->lblTest1->Refresh();

}

}

When I access in browser the following link www.tef_ticketing.dev I am redirected to http://www.tef_ticketing.dev/test_page , and it is ok. But I have an error:

Fatal error: Class 'Tef_Ticketing\Presentation\Web\Forms\Form' not found in C:\xampp\htdocs\tef_ticketing\workspace\tef_ticketing-presentation\src\Web\Forms\TestForm.class.php on line 5

http://stackoverflow.com/questions/36113279/how-to-create-a-virtual-host-for-a-qcubed-project-in-xampp-on-windows

**Comment by nlomb** [comment]
don't think it has to do with virtual host at all
but I did not (yet) use mod_rewrite, so not absolutely sure ...

shouldn's it be
```
class** TestForm extends QForm {
```
instead of 
```
class** TestForm extends Form {
```
BTW: I'm using port_based virtual hosts for development, saves editing "/etc/hosts" on each machine

**Comment by vmakre** [comment]
I am using vagrant with puphpet . And i don't want to go back to xampp . Windows is nightmare for development and when you make upload to linux  you don't know what to expect :). I use a lot of shared hosting platforms for production. You need to have good pc with min 4 cores and some memory. 
Advantages of using vagrant (with puphpet) are:
1. you don't need to write even single line of command in linux , everything is automated.
2. everything you need as php modules , mysql , mariadb, xdebug , mailer, is configurable and after some changes in config file you make "vagrant provision" and everything is installed (removed) automatically (where are they in XAMPP??).
3. You can use MailHog for locally testing mail system (you don't need mail server) , this saves me a lot of headaches.
4. Hosts are defined in config file (where is apache vhosts???? i don't care) , so when i need new host , I make copy from existing config and modify to my requirements.
5. You can have many platforms for testing php5, php7 ... 
6. Access to virtual machine is via putty and everything is like on production server  , so you are developing on production like server , that is great.
7. you modify project locally and you don't need ftp to virtual machine everything is synced .
8. You can develop in everything you want , mongodb , nginx , etc...
9. you can access to database via HEIDISQL for example via opened firewall port , or via ssh .
10. you can make cron jobs ( cron jobs in XAMPP? ). 
11. Upload , download paths are "same" as production .
12. Speed of php is better in linux .
13. Your development IDE is in windows , you have a lot of choices. 
Disadvantages? yes:
1. you need some time till you setup everything , vbox, vagrant, puphpet , firewall ports for web , xdebug , ssh .
2. debugging in netbeans need some configuration as your project path and server paths are different , for example server path "/var/www/html/project"  and local project path "D:\vagrant\machine1\html\project" 

This is from my experience so it is personally choice but now i don't have headaches and i sleep peacefully  :) .

**Comment by matthiaz** [comment]
@vmakre All very good tips!

> Windows is nightmare for development and when you make upload to linux you don't know what to expect :). 

This one especially. I solved this by not using windows for anything. None of my teammembers use windows. It makes sense... your application will run on a linux server eventually, so might as well develop on it. 

If you have the time and a bit of patience, you can give linux a try. Linuxmint is a nice linux distribution if you're coming from Windows. If not, using vagrant as @vmakre suggest is a nice alternative.

**Comment by nlomb** [comment]
@matthiaz, @olegabr 

I'm also a linux-only user Desktop, several Notebooks, Servers, all Ubuntu 16.04 LTS, works fine ...

You can gat an inexpensive netbook with LAMP as a development server,
e.g. Acer Aspire with 160 GB Disk and 1 GB RAM will do.

You can also share your apache DOCUMENT-ROOT via samba to work with windows desktop / editors etc.

As most servers are LAMP it's easy to deploy eg. via "weex".

If I can help with that just contact me here.

**Comment by vmakre** [comment]
@nlomb  yes but you are limited to one platform , that is installed and if you want to change php version or mysql this becomes a big problem.  In Vagrant you can change everything and you can have any number of virtual machines . One virtual machine with php5 another with php7 so you have multiplatform testing environments . For me best choice is to install php version same as production server , then chances for incompatibility are small.

**Comment by spekary** [comment]
Ditto. Vagrant with puphpet. A pain to setup initially, but pretty good after that. There are bugs to work around. Maybe we should make our own vagrant file?

**Comment by nlomb** [comment]
@vmakre 
right, one platform for development wíth up-to-date system a nd tools ... 
But for me not a problem in deployment, so far everything has been backward compatible.
Also deployment on XAMPP made no prpblems except "\\"instead of "/" in some config files.

**Comment by vmakre** [comment]
@nlomb  , i know myself how bad was setting javascript library for image upload and wysiwyg editor from xampp to production. This is not qcubed dependency but we always want to make easy transfers , as sometime we need to debug errors on production sites , this task is much difficult  if you have xampp like local environment.

**Comment by nlomb** [comment]
@all 
sorry, did not want to start a platform / development discussion, just my kind of view ...

thanks fo all the work ...
QCubed ROCKS !
